<?php

$lang = array(
	'antivirus'	=> '杀毒软件',
    'msg_antivir_status'	=> '不工作',
    'msg_antivir_err_login'	=> '您没有足够的权限访问此页面',
    'msg_antivir_folder_not_faund'	=> '目录不存在',
    'msg_antivir_err_process'	=> '进程执行错误。最后一行执行:',
    'msg_antivir_ok_process'	=> '该过程已完成.',

    'tpl_antivir_common'	=> '一般',
    'tpl_antivir_check_folder'	=> '检查目录',
    'tpl_antivir_setting'	=> '设置',
    'tpl_antivir_install'	=> '安装杀毒软件',
    'tpl_antivir_auto_del'	=> '自动删除',
    'tpl_antivir_auto_isolation'	=> '自动隔离',
    'tpl_antivir_scan'		=> '扫描',
    'tpl_antivir_more'		=> '了解更多',
    'tpl_antivir_hidden'	=> '隐藏',
    'tpl_antivir_log_scan'	=> '扫描历史',
    'tpl_antivir_show_file'	=> '显示文件',
    'tpl_antivir_settingss'	=> '设置',
    'tpl_antivir_auto_update_db'	=> '自动更新反病毒数据库',
    'tpl_antivir_last_update'	=> '最近更新',
    'tpl_antivir_save'		=> '保存',
    'tpl_antivir_update'	=> '更新',
    'tpl_antivir_more'		=> '了解更多',
    'tpl_antivir_hidden'	=> '隐藏',

    'tpl_antivir_go_process'	=> '该进程正在进行中。请等待',
    'tpl_antivir_begin_process'	=> '扫描过程正在进行中。请等待',
    'tpl_antivir_save_conf'	=> '保存设置',
	'antivirus_not_root'	=> '你没有足够的权限.',
	'antivirus_scan_susspend'	=> '扫描完成.',	
	'antivirus_scan_nosusspend'	=> '扫描失败',		
	'antivirus_scan_check'	=> '请求完成',
	'antivirus_scan_histiry'	=> '扫描历史记录已检索.',	
	'antivirus_scan_histiry_null'	=> '扫描历史数据为空',
	'antivirus_not_data'	=> '正在查看的文件为空.',
	'antivirus_not_id_history'	=> '没有这样的历史ID.',	
	'antivirus_not_root1'	=> '你没有足够的权限.',	
	'antivirus_update_susspend'	=> '更新成功.',
	'antivirus_update_nosusspend'	=> '更新失败',	
	'antivirus_update_limit'	=> '超过更新时间.',
	'antivirus_clear_history'	=> '清除扫描历史记录',
	'antivirus_run_clear_history'	=> '清除历史',
	'antivirus_clear_history_sus'	=> '历史已被清除.',
	'antivirus_move_carantyn'	=> '转移到隔离区',
	'antivirus_delete'	=> '已删除',
	'antivirus_searche_bad_files'	=> '发现受感染的文件:',
	'antivirus_virus'	=> '病毒',	
	'antivirus_karantine'	=> '隔离',
	'antivirus_delete_qw'	=> '删除',
	'antivirus_all'	=> '全部',
	'antivirus_delete_all'	=> '全部删除',	
	'antivirus_file'	=> '文件',
	'antivirus_karantine_all'	=> '全部隔离',
	'antivirus_karantine_out'	=> '隔离中',
	'antivirus_perfom'	=> '执行',	
	'antivirus_path_karantine'	=> '各路路径:',
    'antivirus_no_history'	=> '历史是空的',
    'antivirus_not_install'	=> '服务未安装',
    'antivirus_stopscan'	=> '停止',
    'antivirus_checkrunprocess'	=> '检查正在运行的进程...',
    'antivirus_processrun'	=> '搜索中...',
    'antivirus_scan_terminate'	=> '扫描中断',
    'antivirus_update_start1'	=> '更新开始',
    'antivirus_update_finish1'	=> '更新完成',
    'antivirus_manage'	=> '管理',
    'antivirus_viewfile'	=> '查看文件',
    'antivirus_update_title'	=> '更新',
);

?>
