<?php

$lang = array (
	'apacserver' => 'Управление вебсервером',
	'directory_password' => 'Установка пароля на директорию',
	'apacserver_pass_selectdom' => 'Выберите домен',
	'apacserver_pass_nodominacc' => 'Сначала нужно добавить домен в аккаунт',
	'apacserver_dir_safe' => 'Директории не существует или неверный формат',
	'apacserver_pass_safe' => 'Слабый пароль',
	'apacserver_add_dir_failed_already_exist' => 'Пароль на данную папку уже существует.',
	'apacserver_add_www_redir_ok' => 'Переадресация успешно добавлена',
	'apacserver_delete_www_redir_ok' => 'Переадресация успешно удалена',
	'apacserver_add_www_failed_exist' => 'Такой тип переадресации уже существует.',
	'apacserver_add_www_failed_bad_from' => 'Неверный формат имени сайта',
	'apacserver_add_www_failed_bad_to' => 'Неверный формат назначения',
	'apacserver_add_www_failed_not_perm' => 'Нет прав для данной операции!',
	'apacserver_add_http_failed_exist' => 'Переадресация для данного сайта уже существует.',
	'apacserver_add_http_redir_ok' => 'Переадресация успешно добавлена',
	'apacserver_delete_http_redir_ok' => 'Переадресация успешно удалена',
	
	'tpl_apac_delete' 	=> 'Удалить',
	'msg_apac_ok' 		=> 'Успешно',
	'msg_apac_not_perm' 	=> 'Не выполнено',
	
	'tpl_apac_jmp_site' 	=> 'Переадресация сайтов',
	'tpl_apac_add_site' 	=> 'Добавить сайт',
	'tpl_apac_site' 	=> 'Cайт',
	'tpl_apac_www' 		=> 'www',
	'tpl_apac_nowww' 	=> 'без www',
	'tpl_apac_both' 	=> 'оба',
	'tpl_apac_pattern' 	=> 'По шаблону',
	'tpl_apac_destination' 	=> 'Назначение',
	'tpl_apac_add_jpm' 	=> 'Подождите, добавляется переадресация... ',
	'tpl_apac_forwarding' 	=> 'Переадресация',
	'tpl_apac_forwarding_listhttp' 	=> 'Список переадресаций',
	'tpl_apac_action_list' 	=> 'Сайт, Пользователь, Назначение, Переадресация, Действие',
	
	'tpl_apac_user' 	=> 'Пользователь',
	'tpl_apac_action' 	=> 'Действие',

	'tpl_apac_jmp_far' 	=> 'Переадресация HTTP — HTTPS',
	'tpl_apac_add_folder' 	=> 'Установить пароль на директорию',
	'tpl_apac_jmp_type' 	=> 'Тип переадресации',
	'tpl_apac_select_http' 	=> 'https в http',
	'tpl_apac_select_https' 	=> 'http в https',
	'tpl_apac_folders' 	=> 'Директории',
	'tpl_apac_folder' 	=> 'Директория',
	'tpl_apac_action_list1' 	=> 'Сайт, Пользователь, Переадресация, Действие',
	'tpl_apac_action_list2' 	=> 'Директория, Пользователь, Пароль, Действие',

	'tpl_apac_set_pass_folder' 	=> 'Установка пароля на директорию',
	'tpl_apac_passwd' 	=> 'Пароль',
	'tpl_apac_nopass_folder' 	=> 'Ни на одну папку не установлен пароль',

	'tpl_apac_select_www' 		=> 'в www.',
	'tpl_apac_select_nowww' 	=> 'в .',
	'tpl_apac_jmp_www' 	=> 'Переадресация WWW',


	'js_apac_jmp_table' 	=> 'Таблица уже содержит массовую пересылку для этого сайта',
	'js_apac_add_domain' 	=> 'Требуется добавить домены в аккаунт',
	'apacserver_list_directory' 	=> 'Список запароленых директорий',
	'apacserver_list_not_directory' 	=> 'Список запароленых директорий пуст',
	'apacserver_list_http' 	=> 'Список доменов',
	'apacserver_none_list_http' 	=> 'Список доменов пуст',
	'apacserver_list_directory_http' 	=> 'Список Директорий',	
	'apacserver_none_list_directory_http' 	=> 'Список Директорий пуст',
	'apacserver_not_remove' 	=> 'Это не ваше',
	'apacserver_not_type' 	=> 'Не существующий тип',
	'apacserver_list_forwarding' 	=> 'Список переадресаций',
	'apacserver_not_list_forwarding' 	=> 'Список переадресаций пуст',	
	'apacserver_not_unic_id' 	=> 'unic_id введен не правильно. Или этой переадресации уже нет.',		
	'apacserver_not_domain' 	=> 'Не существующий домен.',
	'apacserver_not_forward' 	=> 'Не правильно назначена переадресация',
	'apacserver_not_path_forward' 	=> 'Не указан путь переадресации',	
	'apacserver_del_process' 	=> 'Удаляется...',

	'apacserver_setpass_login' 	=> 'Логин',
	'apacserver_notset_any_redir_site' 	=> 'Не установлена переадресация ни на один сайт.',
	'apacserver_notset_any_redir_http' 	=> 'Не установлена HTTP переадресация ни на один сайт.',
	'apacserver_seluser' => 'Выберите пользователя',
	'apacserver_http_failedadd' => 'Ошибка параметров. Пользователь не выбран. ',
	'apacserver_error_pages' => 'Страницы ошибок',
	'apacserver_list_error_pages' 	=> 'Свои страницы ошибок',
	'apacserver_error' 	=> 'ошибка',
	'apacserver_code_error' 	=> 'Код ошибки',	
	'apacserver_file' 	=> 'Расширение файлов',	
	'apacserver_fild_load' 	=> 'Поле для загрузки',
	'apacserver_download' 	=> 'Загрузить',
	'apacserver_visible_file' 	=> 'Посмотреть',
	'apacserver_delete' 	=> 'Удалить',
	'apacserver_save' 	=> 'Сохранить',	
	'apacserver_not_site' 	=> 'У пользователя нет сайтов',	
	'apacserver_not_file_download' 	=> 'Не поддерживаемое тип файла',
	'apacserver_error_file_download' 	=> 'Ошибка в загрузке файла',
	'apacserver_optimization' 	=> 'Оптимизация работы сайта',	
	'apacserver_optimization_gzip' 	=> 'Включить gzip сжатие',
	'apacserver_optimization_cesh' 	=> 'Включить кэширование статики в браузере',
	'apacserver_successfully' 	=> 'Изменения сохранены',
	'apacserver_time_cash' 	=> 'Время кэширования: ',
	'apacserver_day' 	=> 'дней',
	'apacserver_incorecly' 	=> 'Не корректное значение',
	'apacserver_optimisation_files' 	=> 'Оптимизировать файлы',
	'apacserver_bacup_copy' 	=> 'Путь для резервных копий',
	'apacserver_save_bacup_copy' 	=> 'Сохранить резервные копии',
	'apacserver_not_files_optimisation' 	=> 'Не найдены файлы для оптимизации',	
	'apacserver_error_directory' 	=> 'Директория не соответствует регулярному выражению',		
	'apacserver_action' 	=> 'Действие',			
	'apacserver_action_restore' 	=> 'Восстановить',	
	'apacserver_path' 	=> 'Директория',		
	'apacserver_date' 	=> 'Дата',
	'apacserver_error_id' 	=> 'Ошибка id bacup',
	'apacserver_error_domain' 	=> 'Домен не соответствует регулярному выражению',	
	'apacserver_error_user' 	=> 'Пользователь не соответствует регулярному выражению',
	'apacserver_restore_succesfully' 	=> 'Файлы восстановлены из резервных копий',	
	'apacserver_remove_succesfully' 	=> 'Резервные копии удалены',
	'apacserver_empty_path' 	=> 'Для создания резервных копий укажите путь.',
	'apacserver_empty_path_1' 	=> 'Для создания резервных укажите папку',

    'apacserver_wrongdest1' 	=> 'Неверный формат назначения. Указывать в формате без http.',
	'apacserver_gpagespeed_link_text' 	=> 'Проверить в Google PageSpeed Insights',
    'apacserver_extCache' 	=> 'Расширения для кэширования: ',
    'apacserver_extCacheEx' 	=> 'Укажите расширения через ; , | или пробел. Например: ttf|jpg|jpeg|png|ico|css|bmp|swf|js|txt|tar|zip|pdf|tar.gz|woff|woff2',
    'apacserver_extCacheTimeMin' 	=> 'минут',
    'apacserver_extCacheTimeHour' 	=> 'часов',

    'apacserver_cacheHintWrongExt' => 'Список расширений указан в неверном формате',
    'apacserver_cacheHintWrongExtExp' => 'Время кэширования указано в неверном формате',
    'apacserver_cacheHintSaveok' => 'Сохранено успешно',
    'apacserver_cacheWaitPlease' => 'Пожалуйста, подождите',
    'apacserver_dostatforthisext' => 'Обрабатывать статику через nginx для этих расширений',
    'apacserver_error_reserv_directory' => 'Ошибка. Директория зарезервирована системой.',
    'apacserver_error_type_files' => '<br>Поддерживаемые типы файлов html, htm, php',
    'apacserver_optimization_off_nginx' => 'Отключить кеширование динамики в nginx',
    'apacserver_empty_ssl_domain' => 'Ошибка переадресации. На домен не установлен ssl сертификат.',
    'apacserver_addredir' => 'Добавить переадресацию',
    'apacserver_optimiz_title' => 'Оптимизация',
    'apacserver_addpasstitle' => 'Добавить пароль',
	'apacserver_extCacheEx_1' 	=> 'Список часто использованных расширений: ttf|jpg|jpeg|png|ico|css|bmp|swf|js|txt|tar|zip|pdf|tar.gz|woff|woff2',	
	
	
);