<?php

$lang = array(
    'api_code_1002'		=> '您无权管理该用户',
    'api_code_1000'		=> '您无权管理该用户',
    'api_code_1001'		=> 'Brainy 中不存在此类用户',
    'api_code_1003'		=> '您没有管理员权限',
    'api_code_1004'		=> '未检测到输入数据',
    'api_code_2'		=> '参数错误!',
    'api_code_addmail_3'	=> '添加邮箱时出错:',
    'api_code_addmail_0'	=> '已成功添加新邮箱: ',
    'api_code_addmail_1'	=> '这样的邮箱已经存在: ',
    'api_code_addmail_4'	=> '在系统上找不到指定的邮箱域: ',
    'api_code_delmail_0'	=> '邮箱已成功删除: ',
    'api_code_delmail_1'	=> '删除邮箱时出错: ',
    'api_code_delmail_3'	=> '没有什么可以删除的，没有找到这样的邮箱: ',
    'api_code_delforwardmail_0'	=> '邮箱重定向已成功删除 ',
    'api_code_delforwardmail_1'	=> '删除邮箱重定向时出错: ',
    'api_code_addforwardmail_0'	=> '邮箱重定向成功: ',
    'api_code_addforwardmail_1'	=> '添加邮箱重定向时出错: ',
    'api_code_addforwardmail_3'	=> '邮箱地址错误: ',
    'api_code_dkim_0'	=> 'OpenDkim 已成功激活 ',
    'api_code_dkim_1'	=> '没有找到该用户的域 ',
    'api_code_dkim_3'	=> 'OpenDkim 已经在运行 ',
    'api_code_offdkim_0'	=> 'OpenDkim 已成功禁用 ',
    'api_code_offdkim_1'	=> '没有找到该用户的域 ',
    'api_code_spf_0'	=> '已成功为域激活 SPF ',
    'api_code_spf_1'	=> '没有找到该用户的域 ',
    'api_code_spf_3'	=> '已为域启用 SPF ',
    'api_code_offspf_0'	=> '已成功为域禁用 SPF ',
    'api_code_offspf_1'	=> '没有找到该用户的域 ',
    'api_code_offspf_3'	=> '已为域禁用 SPF ',
    'api_code_getlistmail_0'	=> '已成功检索到以下邮箱列表 ',
    'api_code_getlistmail_1'	=> '没有找到邮箱 ',
    'api_code_getforwardmail_0'	=> '已成功检索到以下邮箱列表 ',
    'api_code_getforwardmail_1'	=> '找不到邮箱重定向 ',

    'api_code_cron_min_1'      => '分钟格式无效',
    'api_code_cron_hours_1'    => '时钟格式无效',
    'api_code_cron_days_1'     => '日期格式无效',
    
    'api_code_cron_add_0'     => '已成功为用户添加新的 cron 任务: ',
    'api_code_cron_add_1'     => '为用户添加新的 cron 任务时出错: ',
    'api_code_cron_edit_0'     => '已成功为用户编辑 cron 任务: ',
    'api_code_cron_edit_1'     => '为用户编辑任务时出错 ',
    'api_code_cron_edit_2'     => '找不到用户的任务 ',
    'api_code_cron_edit_4'     => '没有值，没事做!',
    'api_code_cron_del_0'     => '已成功为用户删除 cron 任务: ',
    'api_code_cron_del_1'     => '删除用户的任务时出错 ',
    'api_code_cron_del_2'     => '找不到用户的任务 ',
    'api_code_cron_list_0'     => '已成功为用户检索到任务列表 ',

    'api_code_cert_add_0'     => '已成功为用户添加新证书: ',
    'api_code_cert_add_1'     => '为用户添加证书时出错: ',
    'api_code_cert_list_0'     => '已为用户成功获取证书列表: ',
    'api_code_cert_list_1'     => '检索用户的证书列表时出错: ',
    'api_code_cert_del_0'     => '已成功为用户删除密钥和证书: ',
    'api_code_cert_del_1'     => '无法删除所需的证书，因为主机正在使用它.',
    'api_code_cert_del_2'     => '没有这样的密钥和证书。无需删除',
    'api_code_cert_savedomain_0'     => '已成功为域安装证书 ',
    'api_code_cert_deldomain_0'     => '已成功删除域的证书 ',
    'api_code_cert_listdomain_0'     => '已安装证书的域列表已检索到: ',


    'api_code_ftp_add_0'     => '已成功添加新的 FTP 用户: ',
    'api_code_ftp_add_1'     => '此 FTP 用户已存在: ',
    'api_code_ftp_add_2'     => '没有安装 FTP 服务器',
    'api_code_ftp_add_3'     => '面板中缺少用户名',
    'api_code_ftp_add_4'     => '添加新用户时发生错误 ',
    'api_code_ftp_del_0'     => 'FTP用户删除成功 ',
    'api_code_ftp_del_1'     => '没有找到这样的用户 ',
    'api_code_ftp_del_2'     => '没有安装 FTP 服务器',
    'api_code_ftp_del_3'     => '删除用户时出错 ',
    'api_code_ftp_quota_0'     => '已成功为用户更改配额 ',
    'api_code_ftp_quota_1'     => '未找到用户 ',
    'api_code_ftp_quota_2'     => '没有安装 FTP 服务器',
    'api_code_ftp_quota_3'     => '更改用户配额时出错 ',
    'api_code_ftp_pass_0'     => '密码已成功更改 ',
    'api_code_ftp_pass_1'     => '找不到 FTP 用户 ',
    'api_code_ftp_pass_2'     => '没有安装 FTP 服务器',
    'api_code_ftp_pass_3'     => '更改用户密码时出错 ',
    'api_code_ftp_list_0'     => '已成功为用户检索到 FTP 用户列表 ',
    'api_code_ftp_list_2'     => '没有安装 FTP 服务器',
    'api_code_ftp_list_3'     => '获取 FTP 用户列表时出错 ',


    'api_code_prop_getinfo_0'     => '信息已成功获取',
    'api_code_prop_getinfo_1'     => '检索信息时出错',
    'api_code_prop_newtime_0'     => '时间已成功更改为: ',
    'api_code_prop_newtime_0'     => '更改时间时发生错误.',
    'api_code_prop_tz_0'     => '时区已成功更改',
    'api_code_prop_tz_1'     => '更改时区时出错',
    'api_code_prop_tz_2'     => '指定的时区无效',
    'api_code_prop_host_0'     => '新的主机名设置',
    'api_code_prop_host_1'     => '设置新主机名时出错',
    'api_code_prop_host_2'     => '指定的主机名无效',
    'api_code_prop_rootps_0'     => '已成功更改root密码',
    'api_code_prop_rootps_1'     => '更改 root 密码时发生错误',
    'api_code_prop_rootps_2'     => '新的 root 密码太短，至少 8 个字符',
    'api_code_prop_brainyps_0'     => 'Brainysql 的密码已成功更改',
    'api_code_prop_brainyps_1'     => '更改brainysql密码时发生错误',
    'api_code_prop_brainyps_2'     => '新的brainysql密码太短，至少8个字符',
    'api_code_prop_lang_0'     => '所选语言已成功设置: ',
    'api_code_prop_lang_2'     => '语言设置不正确: ',
    'api_code_prop_mail_0'     => '新参数应用成功',
    'api_code_prop_mail_1'     => '应用新参数时发生错误',
    'api_code_prop_mail_2'     => '指定的邮箱无效',
    'api_code_prop_mail_3'     => '指定的主机名无效',
    'api_code_prop_mail_4'     => '端口未定义或无效',
    'api_code_prop_mail_5'     => '指定的邮件发件人无效。必须是 smtp 或 phpmail',


    'api_code_acc_changeshell_0'     => '外壳访问已更改。当前状态: ',
    'api_code_acc_changeshell_1'     => '尝试更改外壳访问权限时出错',
    'api_code_acc_changeshell_2'     => 'shell 参数包含无效值。允许值：是/否',
    'api_code_acc_changeshell_3'     => '',
    'api_code_acc_changelang_0'     => '所选语言已成功更改。当前语言: ',
    'api_code_acc_changelang_1'     => '尝试更改语言时出错',
    'api_code_acc_changelang_2'     => 'lang 参数包含无效值。允许值：ru / en',
    'api_code_acc_edituser_err_info'     => '没有错误',
    'api_code_acc_edituser_0'     => '用户数据已成功编辑',
    'api_code_acc_edituser_1'     => '编辑用户数据时发生错误: ',
    'api_code_acc_edituser_2'     => '未找到群组',
    'api_code_acc_edituser_3'     => '未找到指定的组',
    'api_code_acc_edituser_4'     => '登录名必须至少包含 3 个字符',
    'api_code_acc_edituser_5'     => '密码必须至少为 7 个字符',
    'api_code_acc_edituser_10'     => ' - 参数错误。只允许数字 0-9',
    'api_code_acc_edituser_6'     => 'Shell 包含无效值。允许值 是/否',
    'api_code_acc_edituser_7'     => '未找到资费方案',
    'api_code_acc_edituser_8'     => '指定的资费方案不存在',
    'api_code_acc_edituser_9'     => '指定的语言无效。允许值 ru / en',
    'api_code_acc_deluser_0'     => '用户已成功删除',
    'api_code_acc_deluser_1'     => '删除用户时出错',
    'api_code_acc_deluser_2'     => '没有定义要删除的用户',
    'api_code_acc_adduser_0'     => '已成功添加新用户',
    'api_code_acc_adduser_1'     => '添加用户时发生错误',
    'api_code_acc_adduser_2'     => '未找到指定的组',
    'api_code_acc_adduser_3'     => '找不到指定的计划',
    'api_code_acc_adduser_4'     => '登录名必须至少包含 3 个字符',
    'api_code_acc_adduser_5'     => '密码必须至少为 7 个字符',
    'api_code_acc_listuser_0'     => '已成功检索到用户列表',
    'api_code_acc_listuser_1'     => '没有找到用户',
    'api_code_acc_listgroup_0'     => '已成功接收群组列表',
    'api_code_acc_listgroup_1'     => '未找到群组',
    'api_code_acc_listplan_0'     => '已成功收到资费方案清单',
    'api_code_acc_listplan_1'     => '未找到资费方案',
    'api_code_acc_editplan_0'     => '资费计划已成功编辑',
    'api_code_acc_editplan_1'     => '在修改资费计划时发生错误',
    'api_code_acc_editplan_2'     => '指定的计划不存在',
    'api_code_acc_editplan_3'     => 'Shell 包含无效值。允许值 y / n',
    'api_code_acc_editplan_4'     => '指定的语言无效。允许值 ru / en',
    'api_code_acc_editplan_10'     => ' - 参数错误。只允许数字 0-9',
    'api_code_acc_addplan_0'     => '新资费方案创建成功',
    'api_code_acc_addplan_1'     => '创建资费计划时出错',
    'api_code_acc_addplan_2'     => '计划已经存在',
    'api_code_acc_addplan_3'     => '显示错误的资费计划名称',
    'api_code_acc_addplan_4'     => 'Shell 包含无效值。允许值 y / n',
    'api_code_acc_addplan_5'     => '指定的语言无效。允许值 ru / en',
    'api_code_acc_addplan_10'     => ' - 参数错误。只允许数字 0-9',
    'api_code_acc_delplan_0'     => '计划已成功删除',
    'api_code_acc_delplan_1'     => '删除计划时发生错误',
    'api_code_acc_delplan_2'     => '没有计划',
    'api_code_acc_delplan_3'     => '未指定计划名称或不正确',

    'api_code_acc_viewplan_0'     => '计划数据已成功获取',
    'api_code_acc_viewplan_1'     => '检索计划数据时发生错误',
    'api_code_acc_viewplan_2'     => '没有计划',
    'api_code_acc_viewplan_3'     => '未指定计划名称或不正确',
    'api_code_acc_viewgroup_0'     => '已成功检索到组数据',
    'api_code_acc_viewgroup_1'     => '检索组数据时出错',
    'api_code_acc_viewgroup_2'     => '未找到或未定义指定的组: ',
    'api_code_acc_editgroup_0'     => '群组编辑成功',
    'api_code_acc_editgroup_1'     => '编辑组时出错',
    'api_code_acc_editgroup_2'     => '未找到或未定义指定的组',
    'api_code_acc_editgroup_3'     => ' - 参数错误。可以是 y/n/（空字符串）',
    'api_code_acc_addgroup_0'     => '已成功添加新组',
    'api_code_acc_addgroup_1'     => '添加新组时发生错误',
    'api_code_acc_addgroup_2'     => '组已经存在',
    'api_code_acc_addgroup_3'     => '指定的新组名不正确',
    'api_code_acc_addgroup_4'     => ' - 参数错误。可以是 y/n/（空字符串）',
    'api_code_acc_delgroup_0'     => '该组已成功删除',
    'api_code_acc_delgroup_1'     => '删除组时出错',
    'api_code_acc_delgroup_2'     => '没有这样的组',
    'api_code_acc_delgroup_3'     => '没有指定要删除的组',
    'api_code_acc_suspend_0'     => '锁已成功应用于用户: ',
    'api_code_acc_suspend_1'     => '用户无需锁定: ',
    'api_code_acc_unsuspend_0'     => '已为用户成功释放指定的锁: ',
    'api_code_acc_unsuspend_1'     => '用户无需释放: ',

    'api_code_ipm_listip_0'     => '成功获取IP地址列表',
    'api_code_ipm_listip_1'     => '未找到 IP 地址',
    'api_code_ipm_addip_0'     => '已成功添加新 IP 地址',
    'api_code_ipm_addip_1'     => '添加 IP 地址时出错',
    'api_code_ipm_addip_2'     => '指定的 IP 地址无效',
    'api_code_ipm_addip_3'     => '指定的掩码无效',
    'api_code_ipm_delip_0'     => '指定的IP地址已成功删除',
    'api_code_ipm_delip_1'     => '删除指定的 IP 地址时发生错误',
    'api_code_ipm_delip_2'     => '指定的 IP 地址无效',

    'api_code_hostacc_manaer2'     => '未找到操作',

    'api_code_acc_setplan_ok'     => '计划成功应用于用户',
    'api_code_acc_setplan_failed'     => '更改用户的资费计划时发生错误',

    'apiCode401'     => '通过 htpasswd 拒绝面板访问. <br/>选择操作: <br/>检查上面 htpasswd 的授权详细信息;<br/>在服务器设置中，禁用身份验证 htpasswd;<br/>将 IP 添加到允许<br/>',
    'apiCode403'     => '您的 IP 地址已关闭对 api 面板的远程访问. <br/>请联系管理员.<br/>',
    'apiCodeXXX'     => '访问api时出错.',
    
);

?>


