<?php
$lang = array(
'autoins' => '自动安装程序',
    'cms' => '内容管理系统',
    'selectapptoinstall' => '选择要安装的应用程序',
    'installapp' => '安装',
    'install_app_pleasewait' => '请稍候',
    'install_app_finished' => '完成',
    'install_app_choose_protocol' => '选择协议',
    'install_app_choose_domain' => '选择一个域',
    'install_app_choose_domain_desc' => '请选择一个域来安装软件',
    'install_app_choose_dir' => '请选择一个目录',
    'install_app_choose_dir_desc' => '该目录与您的域相关，例如：要安装到 http://mydomain/dir/ 只需输入dir，要安装到 http://mydomain/ 请留空.',

    'install_app_sitename' => '站点名称',
    'install_app_sitedesc' => '说明',
    'install_app_importexample' => '导入示例',

   'install_app_adminarea' => '管理员',
     'install_app_adminarea_username' => '账号',
     'install_app_adminarea_pass' => '密码',
     'install_app_adminarea_realname' => '你的名字',
     'install_app_adminarea_email' => '电子邮件',

     'install_app_chooselang' => '选择语言',

     'install_app_plugins' => '选择插件',

     'install_app_wp_loginizer' => '授权尝试限制 (Loginizer)',

     'install_app_forumname' => '论坛名称',

     'install_app_dbhost' => '数据库主机',
    'install_app_installedapp' => '已安装的应用程序',
    'install_app_path_install' => '路径',
    'install_app_domain_install' => '域',
    'install_app_name_install' => '应用程序',
    'install_app_path_delete' => '删除',
    'install_app_path_edit' => '编辑',
    'install_app_option_install' => '选项',
    'install_app_path_ins_failed' => '无效路径',
    'install_app_path_inuse' => '给定的路径已经存在，请检查目录 ',
    'install_app_install_success' => '安装成功',
    'install_app_install_progress' =>' 请稍候，正在安装。',
    'install_app_delete_success' => '应用程序已被删除',
    'install_app_no_installed_app' => '没有安装的应用程序',
    'install_app_client_autoins_stat' => '为客户端激活自动安装程序',
    'autoins_client_stat_complete' => '配置保存成功',
    'autoins_client_stat_message' => '自动安装程序已禁用，请联系您的管理员.',

   'autoins_listautoins' => '应用程序列表',
    'autoins_listautoins_type' => '应用程序类型',
    'autoins_listautoins_name' => '应用程序名称',
    'autoins_listautoins_version' => '版本',
    'autoins_listautoins_option' => '选项',
    'autoins_listautoins_selectapp' => '选择',

    'autoins_listautoins_enable' => '可用',

    'autoins_preg_match_dirins' =>' 无法访问安装目录，请仅使用英文字母、数字和 / ',
    'autoins_preg_match_sitename' => '请输入站点名称',

    'autoins_preg_match_sitedesc' => '请输入网站描述',
    'autoins_preg_match_login_admin_short' => '登录管理面板的最小长度是英文字母的 6 个字符',
    'autoins_preg_match_pass_admin_short' => '管理区密码的最小长度为 6 个字符',
    'autoins_preg_match_realname' => '输入您的名字（名称必须至少包含2个字母，仅有数字和英文字母a-zA-Za-yo）',
    'autoins_preg_match_emailadm' => '输入管理员邮箱',
    'autoins_preg_match_email' => '请输入有效的管理员邮箱',
    'autoins_saveactiveapp' => '保存',
    'autoins_saveactiveapp_res' => '更新成功',

    'autoins_indirexistfiles' =>' 指定文件夹中已存在文件.确认覆盖安装',
     'autoins_indirexistfiles_yes' => '是',
     'autoins_indirexistfiles_no' => '否',
     'autoins_install_error' => '错误',
     'autoins_install_wait_user' => '等待用户选择',

    'autoins_deleteapp_inprogress' =>' 正在删除，请等一下',
    'autoins_cms' => '选择分布',
    'autoins_install' => '选择发行版',
    'autoins_error_connect' => '错误连接 mysql',
    'autoins_error_not_you' => '不是你的！',
    'autoins_blog_english' => '英文博客',
    'autoins_blog_no' => '不',
    'autoins_brochure_english' => '小册子英语',
    'autoins_default_english' => '默认英文',
    'autoins_learn_joomla' => '学习 Joomla',
    'autoins_test_english' => '测试英语',
    'autoins_ru' => '俄语',
    'autoins_en' => '英语',
    'autoins_clear_cache' => '清除应用程序缓存',
    'autoins_clear_cache_bl' => '正在清除缓存',
    'autoins_clear_cache_ok' => '清除缓存成功完成',
    'autoins_not_select_cms' => '没有选择 CMS',
    'autoins_not_write_cms' => 'CMS 没有正确写入',
    'autoins_not_version_cms' => '没有 CMS 版本',
    'autoins_not_vers_incorecly_cms' => 'CMS 版本没有正确写入',
    'autoins_not_protocol' => '未选择协议',
    'autoins_not_incorecly_protocol' => '协议不正确',
    'autoins_not_domain' => '这个域名不属于你',
    'autoins_not_dir' => '这个目录很忙',
    'autoins_susspended' => '安装成功',
    'autoins_not_version_lang' => '语言版本不正确',
    'autoins_list_cms' => '已安装的 CMS 列表',
    'autoins_not_list_cms' => 'CMS 列表为空',
    'autoins_list_cmsnot_install' => 'CMS 列表',
    'autoins_list_not_arr' => 'CMS 数组为空',
    'autoins_list_not_id_arr' => '没有删除 CMS 的 id',
    'autoins_suspended_dell' => 'CMS 成功删除',
    'autoins_error_dell' => '删除 CMS 时出错',
    'autoins_not_root' => '您没有足够的权限删除 user_edit.',
    'autoins_error_mysql' => '错误 mysql 查询',
    'autoins_user_cms' => '为用户安装 CMS',
    'autoins_user_config_acc' => '访问',
    'autoins_name_admin' => 'CMS 自动安装程序',
    'autoins_please_wait' => '请稍候',
    'autoins_notexist_conf_cmsinputdata' => '缺少 CMS 配置文件 inputdata',
    'install_app_adminarea_realname_latin' => '你的名字必须是英文字符',
    'autoins_path_admin' => '管理面板的路径',
    'autoins_path_admin_error' => '输入管理面板路径时出错，最小长度为 4 个字符',
    'autoins_incorrect_ip' => 'IP 地址无效',
    'autoins_incorrect_forum' => '论坛名称无效',
    'autoins_findcapt' => '搜索',
    'autoins_findcapt_wait' => '正在搜索...',
    'autoins_findcapt_nothingfound' => '没有找到',
    'autoins_import_sample' => '导入示例，产品',
    'autoins_domain_not_select' => '域未选择或添加到用户',
    'autoins_userhavenotdomain' => '域未添加',
    'autoins_data_admin_panel' => '登录数据到管理面板',
    'autoins_brainy' => 'Brainy',
    'autoins_login_admin' => '登录管理面板',
    'autoins_redirect_login_admin' => '转到管理面板',
    'autoins_failed_copy' => '无法复制 CMS 源文件 ',
    'autoins_failed_user_config' => '不幸的是，远程 CMS 的配置文件不可用',
    'autoins_user_config' => '自定义 CMS',
    'autoins_incl_user_config' => '连接自定义 CMS',
    'autoins_url_user_incl' => 'http://list.txt 的路径',
    'autoins_url_user_add' => '添加',
    'autoins_url' => 'url',
    'autoins_not_include_cms' => '没有连接的 cms',
    'autoins_error_remote_url' => '错误网址',
    'autoins_error_import_cms' =>' 导入第三方 CMS 时出错。检查远程 list.txt是否存在',
    'autoins_error_paranetrs' => '参数错误',
    'autoins_cms_error' => 'CMS',
    'autoins_version_error' => '版本',
    'autoins_not_null_cms' => 'cms 包含列表存在',
    'autoins_confirm_remove_cms' => '确认删除连接的 cms 列表',
    'autoins_yes' => '是',
    'autoins_not' => '否',
    'autoins_error_remove_list_txt' => '删除 cms 列表时出错',
    'autoins_succp' => '成功',
    'autoins_install_cms' => '通过自动安装程序安装 CMS',
    'autoins_availcms' => '可用的 CMS',
    'autoins_addowncms' => '添加您的 CMS',

);
?>
