<?php
$lang = array(
    'autoins' => 'Автоустановщик',
    'cms' => 'Система управления контентом',
    'selectapptoinstall' => 'Выберите приложение для установки',
    'installapp' => 'Установить',
    'install_app_pleasewait' => 'Пожалуйста, подождите',
    'install_app_finished' => 'Завершено',
    'install_app_choose_protocol' => 'Выберите протокол',
    'install_app_choose_domain' => 'Выберите домен',
    'install_app_choose_domain_desc' => 'Пожалуйста, выберите домен для установки программного обеспечения.',
    'install_app_choose_dir' => 'Укажите директорию',
    'install_app_choose_dir_desc' => 'Каталог относительно вашего домена и он не должен существовать. т.е. Для установки на http://mydomain/dir/ просто введите dir. Для установки только в http://mydomain/ оставьте поле пустым.',

    'install_app_sitename' => 'Название сайта',
    'install_app_sitedesc' => 'Описание',
    'install_app_importexample' => 'Импортировать пример',

    'install_app_adminarea' => 'Администратор',
    'install_app_adminarea_username' => 'Логин',
    'install_app_adminarea_pass' => 'Пароль',
    'install_app_adminarea_realname' => 'Ваше имя',
    'install_app_adminarea_email' => 'Емейл',

    'install_app_chooselang' => 'Выберите язык',

    'install_app_plugins' => 'Выберите плагины',

    'install_app_wp_loginizer' => 'Лимит попыток авторизации (Loginizer)',

    'install_app_forumname' => 'Название форума',

    'install_app_dbhost' => 'Хост базы данных',

    'install_app_installedapp' => 'Установленные приложения',
    'install_app_path_install' => 'Путь',
    'install_app_domain_install' => 'Домен',
    'install_app_name_install' => 'Приложение',
    'install_app_path_delete' => 'Удалить',
    'install_app_path_edit' => 'Редактировать',
    'install_app_option_install' => 'Опции',
    'install_app_path_ins_failed' => 'Неверный путь',
    'install_app_path_inuse' => 'Данный путь уже существует. Проверьте содержимое каталога',
    'install_app_install_success' => 'Успешно установлено',
    'install_app_install_progress' => 'Пожалуйста, подождите. Установка в процессе.',
    'install_app_delete_success' => 'Приложение удалено',
    'install_app_no_installed_app' => 'Установленных приложений нет',
    'install_app_client_autoins_stat' => 'Активировать автоустановщик у клиентов',
    'autoins_client_stat_complete' => 'Конфигурация успешно сохранена',
    'autoins_client_stat_message' => 'Автоустановщик отключен. Пожалуйста, обратитесь к администратору.',

    'autoins_listautoins' => 'Список приложений',
    'autoins_listautoins_type' => 'Тип приложения',
    'autoins_listautoins_name' => 'Имя приложения',
    'autoins_listautoins_version' => 'Версия',
    'autoins_listautoins_option' => 'Опции',
    'autoins_listautoins_selectapp' => 'Выбрать',

    'autoins_listautoins_enable' => 'Доступный',

    'autoins_preg_match_dirins' => 'Недоступный каталог для установки. Пожалуйста используйте только латиницу, цифры и /',
    'autoins_preg_match_sitename' => 'Пожалуйста, введите название сайта',

    'autoins_preg_match_sitedesc' => 'Пожалуйста, введите описание сайта',
    'autoins_preg_match_login_admin_short' => 'Минимальная длина логина в админку сайта 6 символов Латинского алфавита',
    'autoins_preg_match_pass_admin_short' => 'Минимальная длина пароля в админку сайта 6 символов',
    'autoins_preg_match_realname' => 'Введите Ваше имя (Имя должно содержать минимум 2 буквы, только латиница и кирилица a-zA-Zа-яёЁ)',
    'autoins_preg_match_emailadm' => 'Введите Email администратора',
    'autoins_preg_match_email' => 'Введите корректный Email администратора', 
    'autoins_saveactiveapp' => 'Сохранить',
    'autoins_saveactiveapp_res' => 'Обновлено успешно',

    'autoins_indirexistfiles' => 'В указанной папке уже существуют файлы. Подтвердите установку с перезаписью файлов.',
    'autoins_indirexistfiles_yes' => 'Да',
    'autoins_indirexistfiles_no' => 'Нет',
    'autoins_install_error' => 'Ошибка',
    'autoins_install_wait_user' => 'Ожидание выбора пользователя',

    'autoins_deleteapp_inprogress' => 'Выполняется удаление. Пожалуйста, подождите',
    'autoins_cms' => 'Выбрать дистрибутив',
    'autoins_install' => 'Выбрать дистрибутив',
    'autoins_error_connect' => 'error connect mysql',	
    'autoins_error_not_you' => 'is not your!',
	'autoins_blog_english' => 'Blog English',
	'autoins_blog_no' => 'Нет',
	'autoins_brochure_english' => 'Brochure English',
	'autoins_default_english' => 'Default English',	
	'autoins_learn_joomla' => 'Learn Joomla',
	'autoins_test_english' => 'Test English',	
	'autoins_ru' => 'Русский',	
	'autoins_en' => 'English',	
	'autoins_clear_cache' => 'Очистить кеш приложений',		
	'autoins_clear_cache_bl' => 'Идет очистка кеша',
	'autoins_clear_cache_ok' => 'Очистка кеша успешно завершена',
	'autoins_not_select_cms' => 'Не выбрана CMS',
	'autoins_not_write_cms' => 'Не правильно написана CMS',
	'autoins_not_version_cms' => 'Нет версии CMS',
	'autoins_not_vers_incorecly_cms' => 'Не корректно написана версия CMS',
	'autoins_not_protocol' => 'Не выбран протокол',
	'autoins_not_incorecly_protocol' => 'Не корректно написан протокол',
	'autoins_not_domain' => 'Этот домен вам не принадлежит',
	'autoins_not_dir' => 'Эта директория занята.',
	'autoins_susspended' => 'Успешно установлено',	
	'autoins_not_version_lang' => 'Не правильно выбрана версия языка',
	'autoins_list_cms' => 'Список установленных CMS',
	'autoins_not_list_cms' => 'Список CMS пуст',	
	'autoins_list_cmsnot_install' => 'Список CMS',
	'autoins_list_not_arr' => 'Массив CMS пуст',
	'autoins_list_not_id_arr' => 'Нет такого id для удаления CMS',
	'autoins_suspended_dell' => 'CMS Успешно удалена',	
	'autoins_error_dell' => 'Ошибка удаления CMS',
	'autoins_not_root' => 'У вас недостаточно прав. Уберите user_edit.',
	'autoins_error_mysql' => 'error mysql query',
    'autoins_user_cms' => 'Установить CMS пользователю',
    'autoins_user_config_acc' => 'Доступ',
    'autoins_name_admin' => 'Автоустановщик CMS',
    'autoins_please_wait' => 'Пожалуйста, подождите',
    'autoins_notexist_conf_cmsinputdata' => 'Отсутствует файл конфигурации CMS inputdata',
    'install_app_adminarea_realname_latin' => 'Ваше имя должно быть латинскими символами',
    'autoins_path_admin' => 'Путь к админ панели',
    'autoins_path_admin_error' => 'Ошибка ввода пути к админпанели минимальная длина 4 символа',
    'autoins_incorrect_ip' => 'Не корректный ip адрес',
    'autoins_incorrect_forum' => 'Не корректное название форума',
    'autoins_findcapt' => 'Поиск',
    'autoins_findcapt_wait' => 'Выполнятеся поиск...',
    'autoins_findcapt_nothingfound' => 'Ничего не найдено',
    'autoins_import_sample' => 'Импортировать примеры, товары',
    'autoins_domain_not_select' => 'Домен не выбран или не добавлен пользователю',
    'autoins_userhavenotdomain' => 'Домен не добавлен',
    'autoins_data_admin_panel' => 'Данные для входа в в админ панель',
    'autoins_brainy' => 'Brainy',	
    'autoins_login_admin' => 'Вход в админ панель',		
    'autoins_redirect_login_admin' => 'Перейти в админ панель',
    'autoins_failed_copy' => 'Ошибка копирования исходных файлов CMS. Файл ',
    'autoins_failed_user_config' => 'К сожаленью не доступны файлы конфигурации удаленной CMS',
    'autoins_user_config' => 'Пользовательские CMS',
    'autoins_incl_user_config' => 'Подключить пользовательскую CMS',
    'autoins_url_user_incl' => 'http://Путь к list.txt',
    'autoins_url_user_add' => 'Добавить',
    'autoins_url' => 'url',
    'autoins_not_include_cms' => 'Нет подключенных cms',
    'autoins_error_remote_url' => 'Ошибка url',
    'autoins_error_import_cms' => 'Ошибка импорта сторонних CMS. Проверте существование удаленного list.txt',
    'autoins_error_paranetrs' => 'Ошибка параметров.',
    'autoins_cms_error' => 'CMS',
    'autoins_version_error' => 'Версия',
    'autoins_not_null_cms' => 'Подключаемый список cms существует',
    'autoins_confirm_remove_cms' => 'Подтвердите удаление подключенного списка cms',
    'autoins_yes' => 'Да',
    'autoins_not' => 'Нет',
    'autoins_error_remove_list_txt' => 'Ошибка удаления списка cms',
    'autoins_succp' => 'Успешно выполнено.',
    'autoins_install_cms' => 'Установить CMS через автоустановщик',
    'autoins_availcms' => 'Доступные CMS',
    'autoins_addowncms' => 'Добавить свою CMS',

);
?>