<?php

$lang = array(
    'certs_control'           => 'Управление SSL / TLS',
    'service_serv'           => 'Сервисы',
    'service_domain'           => 'Домены',
    'service_expire'           => 'Срок',
    'service_expire_up'           => 'Срок действия до',
    'service_keysize'           => 'Размер ключа',
    'service_issuer'           => 'Издатель',
    'service_action'           => 'Действия',
    'service_action_loadnewcert'           => 'Загрузить новый',
    'service_apply_exist'           => 'Применить существующий сертификат',
    'service_install_newcert'           => 'Установить новый сертификат',
    'service_install_newcert_title'           => 'Выберите один или несколько сервисов для установки сертификата',
    'service_certificate'           => 'Сертификат',
    'service_privatekey'           => 'Приватный ключ',
    'service_cabunlde'           => 'Certificate Authority Bundle',
    'service_install_newcert'           => 'Установить',
    'service_reinstall_cert'           => 'Установить новый сертификат',
    'service_install_error_nosel'           => 'Выберите сервис для которого нужно установить сертификат',
    'service_applyexist'           => 'Применить существующий сертификат',
    'service_applyexist_ok'           => 'Применено успешно',
    'service_install_new_ok'           => 'Новый сертификат установлен успешно',
    'service_save'           => 'Сохранить',
    'service_cancel'           => 'Отменить',
    'service_cert_del'           => 'Удалить сертификат',
    'service_overwrite_cert_q'           => 'Перезаписать сертификат?',
    'service_overwrite_cert_yes'           => 'Да',
    'service_overwrite_cert_no'           => 'Нет',
    'service_cert_not_ins'           => 'Сертификат не установлен',
    'service_cert_del_confirm'           => 'Подвердите удаление сертификата',
    'service_cert_del_confirm_yes'           => 'Да',
    'service_cert_del_confirm_no'           => 'Нет',
    'service_cert_del_complete'           => 'Сертификат удален',
    'service_cert_view'           => 'Просмотреть сертификат',

    'service_cert_install_wrong_cert'           => 'Сертификат не установлен, проверьте корректность введеного сертификата, ключа и Authority Bundle',


    'tpl_certs_cert'		=> 'Сертификат',
    'tpl_certs_del'			=> 'Удалить',
    'tpl_certs_certdel'		=> 'Удалить сертификат',
    'tpl_certs_cerdeactiv'		=> 'Деактивировать сертификат',
    'tpl_certs_key'			=> 'Ключ',
    'tpl_certs_certkey'		=> 'Удалить ключ',
    'tpl_certs_gen_csr'		=> 'Сгенерировать CSR',
    'tpl_certs_select_key'		=> 'Выберите ключ',
    'tpl_certs_key_new'		=> 'Новый ключ',
    'tpl_certs_domain_name'		=> 'Имя домена',
    'tpl_certs_key_size'		=> 'Выберите размер',

    'tpl_certs_country'		=> 'Страна',
    'tpl_certs_state'		=> 'Штат',
    'tpl_certs_city'		=> 'Город',
    'tpl_certs_company'		=> 'Компания',
    'tpl_certs_division'		=> 'Отдел',
    'tpl_certs_create_csr'		=> 'Создать CSR',
    'tpl_certs_load_crt'		=> 'Загрузить сертификат',
    'tpl_certs_name'		=> 'Имя',
    'tpl_certs_copy_file_crt'	=> 'Скопируйте файл сертификата',
    'tpl_certs_insert_file_crt'	=> 'Вставьте файл сертификата',
    'tpl_certs_download_crt'	=> 'Загрузить CRT',
    'tpl_certs_your_crt'		=> 'Ваши CRT',

    'tpl_certs_domain'		=> 'Домен',
    'tpl_certs_certs'		=> 'Сертификат',
    'tpl_certs_lenkey'		=> 'Длина ключа',
    'tpl_certs_status'		=> 'Статус',
    'tpl_certs_func'		=> 'Функции',
    'tpl_certs_edit'		=> 'Редактировать',
    'tpl_certs_save'		=> 'Сохранить',
    'tpl_certs_del_key'		=> 'Удалить ключ',

    'tpl_certs_c_keys'		=> 'Ключи',
    'tpl_certs_c_crts'		=> 'Сертификаты',
    'tpl_certs_c_setting_crts'	=> 'Установка сертификата',
    'tpl_certs_c_list_keycerts'	=> 'Список доменов и сертификатов',
    'tpl_certs_c_create_priv_key'	=> 'Создать приватный ключ',
    'tpl_certs_c_name'		=> 'Имя',
    'tpl_certs_c_key_size'		=> 'Выберите размер',
    'tpl_certs_c_create_key'	=> 'Создать ключ',
    'tpl_certs_c_download_priv_key'	=> 'Загрузить приватный ключ',
    'tpl_certs_c_copy_key'		=> 'Скопируйте ключ',
    'tpl_certs_c_insert_file_key'	=> 'Вставьте файл с ключом',
    'tpl_certs_c_load_key'		=> 'Загрузить ключ',
    'tpl_certs_c_your_private_keys'	=> 'Ваши закрытые ключи',

    'tpl_certs_c_generate_csr'	=> 'Сгенерировать CSR',
    'tpl_certs_c_select_key'	=> 'Выберите ключ',
    'tpl_certs_c_new'		=> 'Новый',
    'tpl_certs_c_name_domain'	=> 'Имя домена',
    'tpl_certs_c_select_size'	=> 'Выберите размер',

    'tpl_certs_c_install_cert'	=> 'Установить сертификат',
    'tpl_certs_c_select_domain'	=> 'Выберите домен',
    'tpl_certs_c_select_crt'	=> 'Выберите сертификат',
    'tpl_certs_c_or_load_new'	=> 'Или загрузите ниже',
    'tpl_certs_c_cert1'	=> 'Сертификат (CRT)',
    'tpl_certs_key1'	=> 'Закрытый ключ (KEY)',
    'tpl_certs_c_list_domain_crts'	=> 'Список доменов и сертификатов',

    'tpl_certs_s_domain_name'	=> 'Доменное имя',
    'tpl_certs_s_ip_addr'		=> 'IP адрес',
    'tpl_certs_s_root_dir'		=> 'Корневая директория',
    'tpl_certs_s_owner'		=> 'Владелец',
    'tpl_certs_s_key_size'		=> 'Размер ключа',
    'tpl_certs_s_domain_def'	=> 'Домен по умолчанию',
    'tpl_certs_s_action'		=> 'Действие',
    'tpl_certs_s_domain_def_ip'	=> 'Установить домен по умолчанию на IP',

    'tpl_certs_s_service_cert'	=> 'Сертификаты сервисов',
    'tpl_certs_s_list_certs'	=> 'Список сертификатов',


    'msg_cert_err_nodomain'		=> 'Ошибка.Отсутствует имя домена',
    'msg_cert_err_nocode'		=> 'Ошибка. Код страны должен содержать 2 символа. Например RU,UK',
    'msg_cert_err_State'		=> 'Ошибка. Штат должен быть заполнен в формате a-z.',
    'msg_cert_errCity'		=> 'Ошибка. Город должен быть заполнен в формате a-z.',
    'msg_cert_errCompany'		=> 'Ошибка. Компания должен быть заполнен в формате a-z.',
    'msg_cert_errOtdel'		=> 'Ошибка. Отдел должен быть заполнен в формате a-z.',

    'msg_cert_create_info0'		=> 'Сертификат для ',
    'msg_cert_create_info1'		=> ' был успешно создан',
    'msg_cert_err_create_domain'		=> 'Ошибка. Возникла проблема при загрузке ключа для этого домена.',
    'msg_cert_err_del_cert'		=> 'Ошибка. Ваш ключ нельзя удалить, так как он используется в хосте ',
    'msg_cert_err_del_cert_cert'		=> 'Ошибка. Ваш сертификат нельзя удалить, так как он используется в хосте ',
    'msg_cert_ok_del_cert'		=> 'Ключ и его сертификат были успешно удалены.',
    'msg_cert_ok_del_cert1'		=> 'Сертификат был удален',
    'msg_cert_err_load_certs'		=> 'Ошибка. Сертификат не загружен',
    'msg_cert_let_info0'		=> 'Сертификат для',
    'msg_cert_let_info1'		=> 'был конфигурирован и применен',

    'msg_cert_ok_unset_dom'		=> 'Сертификат был убран с домена',
    'msg_cert_apply_lets_cert'		=> 'Пожалуйста, подождите. Идет процесс создания сертификата',

    'msg_cert_installed_ok'		=> 'Сертификат установлен',

    'msg_cert_not_installed_yet'		=> 'Сертификат не установлен',
    'msg_key_not_installed_yet'		=> 'Ключ не установлен',
    'msg_cert_install_foremail'		=> 'Установить сертификат для почты',
    'msg_cert_used_foremail'		=> 'Используется для почты',

    'msg_cert_generate_cert'		=> 'Сгенерировать сертификат',

    'msg_cert_nocertkey'		=> 'Нет такого ключа и сертификата, нечего удалять.',
	
	'certs_control_gen_process' => 'Генерируется...',
	'certs_control_apply_cert_process' => 'Применяется...',
	'certs_control_remove_cert_process' => 'Удаляется...',
	'certs_control_install_newcert_process' => 'Устанавливается...',


    'certs_control_error_validcert' => 'Ошибка. Ключ не соответствует данному сертификату',
    'certs_control_error_validcert_chain' => 'Ошибка. Certificate Authority Bundle не соответствует данному сертификату',

    'certs_control_failed_gen_letsen' => 'Ошибка генерации сертификата. Домен должен быть привязан!',
    'certs_control_failed_gen_letsen_dns_record' => 'Ошибка генерации сертификата. Проверьте наличие днс записи на домен ',
    'certs_control_failed_gen_letsen_dns_record_error_arg' => 'Ошибка генерации сертификата. Установлен неизвестный аргумент ',
    'certs_control_failed_gen_letsen_dns_record_AAAA' => 'Ошибка генерации сертификата. В панели нет виртуального хоста с ipv6 , Удалите днс запись АААА ',
    'certs_control_failed_gen_letsen_serv' => 'Ошибка генерации сертификата. Серверный хостнейм должен быть привязан к айпи сервера!',
    'certs_control_failed_gen_letsen_domain' => 'Ошибка генерации сертификата. Домен должен быть привязан к ip сервера. Проверьте днс записи на домен ',
    'certs_control_failed_gen_letsen_error_domain' => 'Ошибка генерации сертификата. На данный домен запрещена выдача сертификата ',


    'certs_control_certload_ok' => 'Сертификат успешно загружен',
    'certs_control_keyload_ok' => 'Ключ успешно загружен',

    'certs_control_certload_failedname' => 'Сертификат не загружен. Ошибка в имени сертификата.',
    'certs_control_keyload_failedname' => 'Ключ не загружен. Ошибка в имени ключа.',

    'certs_control_certload_wrongformat' => 'Неверный формат сертификата.',
    'certs_control_keyload_wrongformat' => 'Неверный формат ключа.',
    'msg_certs_control_certs_info0' => 'Сертификат ',
    'msg_certs_control_certs_info1' => ' успешно применен',
    'cert_control_seluser' => 'Имя пользователя',
    'cert_control_load_wait' => 'Пожалуйста, подождите',
    'cert_control_gen_lets' => 'Сгенерировать Lets Encrypt',
    'cert_control_gen_lets_renew' => 'Сгенерировать новый Lets Encrypt сертификат',
    'cert_control_letsen_autorenew' => 'Автопродление сертификата',
    'cert_control_letsen_autorenew_stat_save' => 'Сохранено',
    'certs_control_domain_setdef'	=> 'Домен установлен на IP по умолчанию',
    'certs_control_ipdomain'	=> 'IP адрес',
    'certs_control_gen_letsen_hostname_ok'	=> 'Сертификат Lets Encrypt успешно сгенерирован',
    'certs_control_active_autorenew_lets_hostname'	=> 'Автопродление сертификата',
	'certs_control_no_keys'	=> 'Нет ключей',
	'certs_control_no_certs'	=> 'Нет сертификатов',
	'certs_control_no_domains'	=> 'Нет добавленных доменов',
    'certs_control_no_cert'	=> 'Убрать сертификат',
    'certs_control_gennew_letsen'	=> 'Сгенерировать новый Lets Encrypt',

    'certs_control_nottimeyet'		=> 'Сертификат для',
    'certs_control_nottimeyet2'		=> 'еще актуален',
    'certs_control_pleasereloadpage' => 'Сертификат для сервиса brainy будет применен через 20 секунд. Пожалуйста, перезагрузите страницу для возобновления работы.',
    'certs_control_pleasereloadpage_del' => 'Сертификат для сервиса brainy будет удален через 20 секунд. Пожалуйста, перезагрузите страницу для возобновления работы.',

    'certs_control_pleasewaitloadinfocert' => 'Пожалуйста, подождите. Идет загрузка информации о сертификате.',
    'certs_control_letsfailedexistgen' => 'Сертификат еще не истек, поэтому невозможно сгенерировать новый сертификат для домена ',

    'certs_warn_notinstall_certbot' => 'CertBOT не установлен. Пожалуйста, установите CertBOT.',
    'certs_warn_notinstall_certbot_btn' => 'Установить CertBOT',
    'certs_warn_nothing_sel' => 'Пожалуйста, выберите сертификат.',

    'certslets_tip_help' => 'Для генерации Lets Encrypt сертификата будет использован хостнейм сервера. Вы можете сменить хостнейм в разделе <a target=_blank href=/index.php?do=properties>Настройка сервера</a>. <br/>Пожалуйста, убедитесь в привязке к вашему серверу хостнейма ',

    'certs_error_nxdomaingencertlets' => 'Необходимо добавить А запись с айпи сервера для домена ',
    'certs_error_genletssuffauth' => 'Недостаточно прав для авторизации домена ',
    'certs_error_genletssuffauth_check' => 'Проверьте, что домен привязан именно к этому серверу.',
    'certs_check_gencertforpanel_host' => 'Генерировать сертификат для panel.hostname',
    'certs_check_gencertforpanel_host_hint' => 'Для генерации сертификата убедитесь, что к вашему серверу привязан домен panel.',
    'certs_select_cert' => 'Выбрать сертификат',
    'certs_data_cert' => 'Данные сертификата',
    'certs_too_many_cert' => 'Сгенерируйте сертификат немного позже. Исчерпан лимит генерации сертификатов.',
    'certs_too_many_cert_services' => 'Сгенерируйте сертификат сервиса немного позже. Исчерпан лимит генерации сертификатов.',
    'certs_too_many_error' => 'Ошибка генерации сертификата. Слишком много неудачных созданий сертификата. Проверьте конфигурации сайта на редиректы и повторите попытку через несколько часов.',
    'certsfailedGenUnauth' => 'Ошибка авторизации. Пожалуйста, проверьте не установлена ли переадресация в настройках сайта, пароль на авторизацию в корневую директорию домена ',
    'certs_error_user' => 'Ошибка пользователя.',	
    'certs_error_domain' => 'Ошибка Домена.',	
    'certs_remove_domain_default_ip' => 'Удалить домен по умолчанию на IP',	
    'certs_wildcard' => 'Wildcard',
    'certs_wildcard_text' => 'Wildcard - возможность генерирования сертификата вида: ',
    'certs_error_api_cloudflare' => 'Сайт подключен к cloudflare, обнаружена ошибка проверки данных от сервиса cloudflare. Проверьте ваши данные от cloudflare, а также ns сервера на домен.',
    'certs_gencerttitle' => 'Генерация сертификата',
    'certs_certdomaccpanel' => 'Сертификат для домена, по которому доступна панель:',
    'certs_thiscertnotallow' => 'Это сертификат не может быть сгенерирован вместе с остальными. Поэтому сертификаты выше недоступны при его генерации.',
    'certs_limitslets' => 'Ограничения Lets Encrypt',
	'certs_control_cloudflare' =>' Если домен подключен с сервису cloudfare, отключите проксирование, или добавьте ваш домен через меню cloudflare, в панели.',
	'certs_control_remove_cert_service' =>'Подтвердите удаление сертификата сервиса.<br><br> ПРЕДУПРЕЖДЕНИЕ, удаление сертификата сервиса приведут к дальнейшей остановке сервиса, рекомендуется переустановить сертификат, или применить существующий.',
    'certs_control_api_empty_user' => 'Такой пользователь отсутствует в ISP-панели:',
    'certs_control_api_get_user_certs' => 'Список сертификатов был успешно получен для пользователя',	
    'certs_control_api_error_parametrs' => 'Ошибка в блоке параметров',	
    'certs_control_api_error_rm_cert' => 'Требуемый сертификат не может быть удален так как он используется',
    'certs_control_api_success_rm_cert' => 'Ключ и сертификат были успешно удалены для пользователя',		
    'certs_control_api_empty_domain' => 'Не найден домен',		
    'certs_control_get_log_letcen' => 'Смотреть лог Lets Encrypt',		
    'certs_control_filed_crt' => 'Ошибка генерации сертификата',		
    'certs_control_empty_log_letcen' => 'Не найден файл лога.',		

);

?>