<?php

$lang = array(
    'access_denied'                 => '您没有足够的权限访问此部分',
    'access_deniedtitle'                 => '访问被拒绝',
    'index'                 => '主页',       
    'input'                 => '入口', 
    'login'                 => '登录',
    'logout'                => '退出',
    'password'              => '密码',
    'ip_manager'            => 'IP管理器',
    'ipmanager'             => 'IP管理器',
    'memmanager'             => '资源管理器',
    'login_form'            => '登录表格',
    'navigation'            => '导航',
    'ip_list'               => 'IP列表',
    'send'                  => '发送',
	'add'                   => '添加',
    'delete'                => '删除',
    'add_time'              => '临时添加',
    'mysql'                 => 'MySQL',
    'plans'                 => '计划',
    'plan'                  => '计划',
    'new_plan'              => '新计划',
    'planname'              => '计划名称',
    'plan_properties'       => '计划属性',
    'host_accounts'         => '主机账户',
    'host_account'          => '主机账户',
    'quota'                 => '配额',
    'yes'                   => '是',
    'no'                    => '否',
    'change'                => '更改',
    'install'               => '安装',
	'reinstall'             => '重新安装',
    'restart'               => '重新启动',
	'force_restart'         => '强制重启',
    'start'                 => '开启',
    'stop'                  => '停止',
    'controls'              => '管理',
    'edit'                  => '编辑',
    'edit_plain'            => '编辑为文本',
    'set'                   => '设置',
    'update'                => '更新',
    'version'               => '版本',
    'current_version'       => '当前版本',
    'add_user'              => '添加用户',
    'add_db'                => '添加数据库',
    'name'                  => '名称',
    'add_user_to_db'        => '将用户添加到数据库',
    'user'                  => '用户',
    'db'                    => '数据库',
    'exist_users'           => '现有用户',
    'exist_dbs'             => '现有数据库',
    'privileges'            => '权限',
    'data'                  => '数据',
    'structure'             => '结构',
    'default_mycnf'         => '恢复默认 my.cnf',
    'change_root_pass'      => '更改root密码',
    'server_control'        => '服务器管理',
    'complectation'         => '完成',
    'php_install'           => '安装 php',
    'apache_install'        => '安装 apache',
    'apache_control'        => '管理 apache',
    'change_passwords'      => '更改密码',
    'nginx_install'         => '安装 nginx',
    'autostatic'            => '静态代理',
    'nginx_control'         => '管理 nginx',
    'server_install'        => '服务器安装',
    'server_complectation'  => '服务器配置',
    'edit_apacheconf'       => '编辑 apache 配置',
    'edit_nginxconf'        => '编辑nginx配置',
    'add_site'              => '添加站点',
    'site'             		=> '站点',
	'site_name'             => '站点名称',
    'site_alias'            => '站点别名',
    'site_admin'            => '站点管理员',
    'site_root'             => '站点根文件夹',
    'default_conf'          => '恢复默认配置',
	'email'             	=> 'Email',
    'ip'                    => 'IP',
    'domain'                => '域',
    'aliases'               => '别名',
    'dir'                   => '目录',
    'reload_hosts'          => '重建虚拟主机',
    'remove_host'           => '删除虚拟主机',
    'current_complectation' => '当前设备',
    'basedir'               => '基本目录',
	'enter'                 => '进入',
    'options'               => '选项',
	'please_wait'			=> '请稍等',
	'processing'			=> '该过程正在进行中。请等一下',
    'deleting'			=> '已移除...',
    'access_error'          => '访问错误',

    'topinfo_count_sites'               => '网站',
	'topinfo_ftp'               => 'FTP 帐户',
    'topinfo_bandwidth' => '带宽',
    'topinfo_databases' => '数据库',
    'topinfo_emailboxes' => '邮箱',
    'topinfo_mailperhour' => '每小时电子邮件数',
    'topinfo_plan' => '计划',
    'topinfo_disk' => '磁盘',
    'topinfo_ip' => 'IP',
    'topinfo_shell_access' => 'Shell',
    'topinfo_language' => '语言',
    'topinfo_username' => '登录',
    'topinfo_rootdir' => '主文件夹',
    'topinfo_group' => '组',
    'topinfo_clamav' => 'Clamav',
    'topinfo_exim' => 'Exim',
    'topinfo_dovecot' => 'Dovecot',
    'topinfo_postfix' => 'postfix',
    'topinfo_webserver' => '网络服务器',
    'topinfo_cron' => 'Cron',
    'topinfo_db' => '数据库',
    'topinfo_named' => '命名',
    'topinfo_loadavg' => '负载均衡',
    'topinfo_diskspace' => '磁盘',
    'topinfo_proftpd' => 'FTP',
    'topinfo_pureftpd' => 'FTP',
    'topinfo_brainy' => 'Brainy',
    'topinfo_opendkim' => 'OpenDKIM',
    'topinfo_brainysqld' => 'BrainySQL',
    'topinfo_postgresql' => 'PostgreSQL',
    'topinfo_fail2ban' => 'fail2ban',

    'topinfo_g_nginx' => 'Nginx',

    'topinfo_csf' => 'CSF',
    'topinfo_spamassassin' => 'SpamAssassin',

    'topinfo_saveok' => '保存成功',
    'common_seluserplease' => '选择用户',
    'common_user_notselect' => '未选择用户',
	'nothing_found' => '找不到',
	'search_is_runnig' => '正在搜索',
	'common_notselect' => '没有选择',
	'common_putname_label' => '输入名称',
	'common_user_current' => '当前用户',
    'common_value_unlim' => '无限',
    'main_title'  => 'BrainyCP — 服务器控制面板',
    'post_title'  => ' — BrainyCP',
	
	'min' => '分钟.',
	
	'topinfo_tip' => '数据在后台更新',
	'topinfo_tip_one' => '每一个',
	'topinfo_tip_not_one' => '每一个',

    'common_killall_ok' => '进程被强行停止',
	
	'upload_caption' => '未选择文件',
	'upload_btn_text' => '选择一个文件',

    'common_pagegencountonpage' => '每页数量: ',
	
	'navigate_header_list'=>'按类别分类',
	'navigate_header_tile'=>'所有部分',

    'context_menu_password' => '设置目录密码',
    'context_menu_optimization' => '加速网站',
    'context_menu_www' => '启用重定向',
    'context_menu_certs_control' => '安装 SSL 证书',
    'context_menu_certs_control_lets' => '安装 Lets Encrypt 证书',
    'context_menu_http' => '配置 HTTPS 重定向',
    'context_menu_server_control_1' => '更改 PHP 指令',
    'context_menu_openfolder' => '在文件管理器中管理文件',
    'context_menu_antivirus' => '使用防病毒软件检查站点',
    'context_menu_logging' => '日志',
    'context_menu_web_statistics' => '统计',
    'context_menu_webserver_config' => '配置虚拟主机',
    'context_menu_mailforward' => '配置邮件转发',
    'context_menu_spf' => '管理 SPF',
    'context_menu_opendkim' => '管理 DKIM',
    'context_menu_mail_antivirus' => '用杀毒软件检查邮件文件夹',
    'context_menu_mail_statistic' => '邮件统计',
    'context_menu_mail_filter' => '添加过滤器',
        'auth_title' => 'BrainyCP - 授权页面',

    'common_config_monitor' => '配置',
     'common_config_updatecaption' => '更新：',
     "common_inhour" => "in",
     "common_every1hour" => "每小时",
     "common_every2to24" => "每小时",
     "common_hour1hour" => "小时",
     "common_hour2to4" => "小时",
     "common_hour5to24" => "小时",

     "common_every1minute" => "所有",
     "common_every2to60" => "所有",
     "common_minute1hour" => "分钟",
     "common_minute2to4" => "分钟",
     "common_minute5to60and0" => "分钟",
     "common_everyhoursend" => "每小时",

	"gen_pass" => "生成密码",
	"difficult_pass" => "复杂度",

    "common_demo_version" => "面板在演示模式下工作。文件管理器以只读模式工作.",
    'common_demo_message' => '抱歉，此操作在演示版中被禁用.',

	"choose_file" => "选择文件",
	"no_file" => "未选择文件",

    "child_human_log_mysqldb" => "创建数据库备份",
    "child_human_log_preparelog1" => "正在准备用户文件",
    "child_human_log_preparelog2" => "正在复制文件",
    "child_human_log_preparelog3" => "创建所需目录",
    "child_human_log_process" => "",
    "child_human_log_data_backup" => "记录备份信息",
    "child_human_log_remove_temp" => "正在删除临时文件",
    "child_human_log_finish_oper" => "完成操作",
    "child_human_log_finish_emailsendcomplete" => "如果设置就发送邮件",
    "child_human_log_finish_calcbackupsfordelete" => "计算备份数量",
    "child_human_log_finish_completecreatebackup" => "备份过程成功完成",
    "child_human_log_startcreate_backup" => "开始创建备份用户",
    "child_human_log_uptodrop" => "正在将备份上传到 Dropbox",
    "child_human_log_uptogdrive" => "正在上传备份到 GoogleDrive",
    "child_human_log_yadisk_putfile" => "将备份上传到 YandexDisk",
    "child_human_log_ftp" => "上传备份到 FTP",

    "child_human_log_uptodrop_rest" => "正在从 Dropbox 上传备份",
     "child_human_log_uptogdrive_rest" => "正在从 GoogleDrive 上传备份",
     "child_human_log_yadisk_putfile_rest" => "正在从 YandexDisk 下载备份",
     "child_human_log_ftp_rest" => "FTP 备份下载",


    "child_human_logtrans_start" => "账户转移开始",
    "child_human_logtrans_transuser" => "用户转移",
    "child_human_logtrans_transuserend" => "用户迁移完成",
    "child_human_logtrans_restoreuser" => "正在恢复用户",
    "child_human_logtrans_restoredbuser" => "恢复用户数据库用户",
    "child_human_logtrans_restoredbuserdbs" => "正在恢复用户数据库",
    "child_human_logtrans_autoins_backup" => "恢复已安装的用户 CMS 列表",
    "child_human_logtrans_restore_backups_jobs" => "正在恢复用户的备份作业列表",

    "child_human_logtrans_restore_restoreftpacc" => "用户帐户的 FTP 恢复",
    "child_human_logtrans_restore_restorevhosts" => "正在恢复用户虚拟主机",
    "child_human_logtrans_restore_change_ips_domains" => "更改用户虚拟主机的ip",
    "child_human_logtrans_restore_vhostsrebuild" => "重建用户虚拟主机",
    "child_human_logtrans_restore_addzones" => "添加 DNS 用户区域",
    "child_human_logtrans_restore_restore_emails_user" => "正在恢复电子邮件帐户",
    "child_human_logtrans_restore_restore_emails_routes" => "正在恢复邮件路由",
    "child_human_logtrans_restore_email_forward" => "恢复邮件重定向",
    "child_human_logtrans_restorequalifyDomainJail" => "为监狱用户恢复qualifydomain",
    "child_human_logtrans_restore_dns_user" => "正在恢复所需文件",
    "child_human_logtrans_restore_dkimkeys_user" => "正在恢复 DKIM 密钥",
    "child_human_logtrans_restore_webserver_includes_user" => "正在恢复虚拟主机设置",
    "child_human_logtrans_restore_passdir_user" => "恢复用户偏好",
    "child_human_logtrans_restore_httpredir_user" => "正在恢复 HTTP 重定向",
    "child_human_logtrans_restore_siteredir_user" => "正在恢复站点重定向",
    "child_human_logtrans_restore_opti_user" => "恢复网站优化设置",
    "child_human_logtrans_crontab" => "为用户恢复 CRON 作业",

    "child_human_logtrans_restorebackuphint" => "用户恢复开始",
    "child_human_logtrans_restorebackuphintend" => "已完成用户恢复",
    "child_human_logtrans_clearuserdata" => "恢复前删除当前用户",
    "child_human_logtrans_restore_passdir_user" => "恢复用户偏好。",

    "child_human_logtrans_userexist" => "已存在同名用户",

    "child_human_dns_type_cluster" => "同步类型：集群",
    "child_human_dns_type_server" => "同步类型：服务器",
    "child_human_dns_ipaddress" => "同步 IP:",
    "child_human_dns_typeserver" => "服务器类型：",
    "child_human_backup_prepare" => "正在执行请求...",

    "common_wrongname_pass" => "用户名或密码错误",

    "child_human_backup_control_sum" => "计算备份校验和",
    "child_human_backup_logtrans" => "日志：",
    "child_human_backup_logtrans_ok" => "备份已成功保存",

    "common_autoloadservice_after_reset_server" => "服务器重启后自动加载服务",
    "common_autoloadservice_title" => "启动",

    "child_human_hostaccsetjailhost" => "恢复用户环境监狱设置",
    "child_human_hostaccsetjailphp" => "恢复用户监狱 php 设置",
    "child_human_backup_opensslcrypt" => "加密/解密备份",
    "child_human_backup_openssldecryptFailed" => "解密失败并出现错误。还原中止。未进行任何更改",

    "child_human_hostaccJaillOffBeforeRestore" => "用户恢复",
    "child_human_hostaccRestoreContinue" => "正在复制文件",

    "current_lang" => "俄语",

    "child_human_listDBrestoredb" => "数据库恢复列表：",
    "child_human_listDBuserrestore" => "数据库用户恢复列表：",
    'common_showAllData' => '显示全部',
   'common_server_resource_limit' => '限制服务器资源',
   'common_access_is_denied' => '拒绝访问',

    "child_human_logtransStart" => "正在转移用户，请稍候",

    "child_human_logtransStartFromRemote" => "正在从远程服务器转移用户，请稍候",

    'child_human__yandexGetBackup' => '从 YandexDisk 获取备份',
    'common_control_packet_menager' => '通过包管理器控制',
    'common_install_version' => '安装版本',
    'commonGmailWarning' => '可用空间少于 xxxMB，无法备份。请腾出空间。',
    'commonFewSpace' => '空间不足。另外需要',
    'commonFewSpaceMsg' => '另外需要',
    'commonSizeMb' => 'mb',
    'commonEnoughSpace' => '有足够的空间。正在加载。',
    'human_backupNoAvailUserForBackup' => '备份作业中指定的用户不可用于备份',

    'human_dropbox_message_createbackup_failed' => '创建 Dropbox 备份时出现连接错误。无法连接到 Dropbox，请检查您的令牌是否是最新的。',
    'human_gdrive_message_createbackup_failed' => '创建 Gdrive 备份时连接错误。无法连接到 Gdrive，请检查您的令牌是否是最新的。',
    'human_yandex_message_createbackup_failed' => '在 Yandex 上创建备份时出现连接错误。无法连接到 Yandex，请检查令牌的相关性。',
    'human_ftp_message_createbackup_failed' => '创建 FTP 备份时出现连接错误。 FTP 连接不可用，请检查您的登录名和密码是否正确。',
    'human_FailedConnWhileCreateBackupRemote' => '创建到远程服务器的备份时出现连接错误。请检查您的连接设置。',

    "humanUserListLockBackup" => "无法备份指定的用户，因为另一个备份进程已经在运行：",
    "humanUserListLockRestore" => "无法备份指定的用户，因为另一个备份还原进程已在运行：",

    "humanUserListLockBackupRestAct" => "无法备份指定的用户，因为另一个备份进程已经在运行：",
    "humanUserListLockRestoreRestAct" => "无法从备份中恢复指定的用户，因为另一个备份恢复进程已经在运行：",
    "humanDownBackuoFromFTP" => "从 FTP 下载备份",
    "humanDownBackuoFromFTPFewSpace" => "FTP 空间不足",

    "childHumanBackupGdriveFailedConn" => "连接到 gDrive 时出错。恢复中止。未进行任何更改。",
    "childHumanBackupGdriveFailedConnUpload" => "连接到 gDrive 时出错。备份到 gDrive 尚未上传。",
    "childHumanBackupGdriveConnOk" => "已成功连接到 gDrive。",

    "childHumanRestoreEmail" => "邮件帐户恢复列表：",
    "childHumanRestoreAll" => "全部",
    "commonAllItems" => "全部",
    "childHumanmakeDataBackupInfo" => "写入备份信息",
    'child_humanGetdropboxBackup' => '从 Dropbox 获取备份',
    "childHumanmakeUnlock" => "解锁用户",
    'commonCustomRestFromfileUserNotExistStop' => '恢复已中止，因为备份是选择性的并且不包含用户信息。指定的用户未登录: ',
    "childHumanrestorefromfileStream" => "正在从所选档案中恢复备份",
    "childHumanrestoreLoggingRotate" => "恢复日志轮换设置",
    "childHumanrestoreHashmon" => "恢复哈希控制设置",
    "childHumanrestoreGroups" => "正在恢复用户组",
    "childHumanrestorePlans" => "恢复用户计划",
    "childHumanrestoreCrons" => "恢复用户工作冠",
    'child_letsRegen' => '为新 IP 地址生成 letencrypt 证书',
    "common_userNotInJailphp" => "编辑 php.ini 不可用 - 用户未添加到 Jail PHP",
    "common_restphpiniuserjailok" => "成功恢复php.ini",
    "childHumanrestorephpini" => "恢复 phpini 设置",
    "child_human_checkauthRemoteServer" => "检查远程服务器的授权",
    'common_file' => '文件',
    'common_erroroccu' => '发生错误：',
    'common_users' => '用户',
    'common_applybtn' => '提交',
    'common_domains' => '域',
    'common_cancelbtn' => '取消',
    'common_selectAll' => '全选',
    'common_processfinish' => '进程完成',
'common_paramwitherror' => '参数包含错误',
'common_status' => '状态',
'common_configtitle' => '配置',
    'common_denyaccess' => '无访问权限',
    'common_see' => '查看',
'common_param' => '参数',
'common_diskpart' => '磁盘分区',
'common_countconnport' => '每个端口的连接数',
'common_dnscount' => 'DNS 区域',
    "common_fastsearche" => "搜索会找到网站、包裹、电子邮件",
'common_failedparam_pass' =>' 字符 \\\ / & apos; &quot; ',
    "license_empty" => "您没有许可证",
    "license_check_data" => "检查日期：",
    "license_panel" => "控制面板",
    "license_correct_date" => "如果不同，请使用以下方法更正日期：",
    "license_support" => "如果日期正确，请联系本站技术支持",
    'access_denied_cluster' => '服务器连接到一个集群，这个模块只在主服务器上管理',
	
);
?>
