<?php

$lang = array(
    'crontab' => 'CRON 设置',
    'clear_script' => '清除脚本',
    'cron_ownvalue' => '...',
    'cron_mon' => '星期一',
    'cron_tue' => '星期二',
    'cron_wed' => '星期三',
    'cron_thu' => '星期四',
    'cron_fri' => '星期五',
    'cron_sat' => '星期六',
    'cron_sun' => '星期日',
    'cron_*_short' => '*',
    'cron_mon_short' => '星期一',
    'cron_tue_short' => '星期二',
    'cron_wed_short' => '星期三',
    'cron_thu_short' => '星期四',
    'cron_fri_short' => '星期五',
    'cron_sat_short' => '星期六',
    'cron_sun_short' => '星期日',
    'cron_min_fail_format' => '无效的格式开始周期分钟',
    'cron_hours_fail_format' => '格式开始周期时钟无效',
    'cron_days_fail_format' => '格式开始周期天数无效',
    "Cron_suspended_acc" => "添加、编辑、删除 Cron 作业已禁用。请联系您的管理员。",

    'cron_install' => '已安装',
    'cron_noinstall' => '未安装',
    'cron_add_comand' => '添加命令',
    'cron_delete' => '删除',
    'cron_delete_process' => '正在删除...',
    'cron_edit' => '编辑',
    'cron_save' => '保存',
    'cron_cansel' => '取消',
    'cron_service' => 'CROND 服务',
    'cron_status' => 'CROND 服务状态',
    'cron_install_cr' => '安装 CROND',
    'cron_delete_cr' => '删除 CROND',
    'cron_reinstall_cr' => '重新安装 CROND',
    'cron_detail' => '详细信息',
    'cron_hide' => '隐藏',
    'cron_control' => 'CROND 控制',
    'cron_start' => '开始',
    'cron_stop' => '停止',
    'cron_reboot' => '重启',
    'cron_task' => 'CROND 任务',
    'cron_select_user' => '选择用户',
    'cron_nocheck' => '未选中',
    'cron_add' => '保存电子邮件',
    'cron_changes' => '更改已成功保存。',
    'cron_null' => '无效的电子邮件格式',
    'cron_minute' => '分钟',
    'cron_hour' => '小时',
    'cron_day' => '天',
    'cron_month' => '月',
    'cron_week' => '周',
    'cron_comand' => '命令',
    'cron_user_email' => '电子邮件（用于发送通知）：',
    'cron_save_ok' => '数据更改成功',

    'cron_command_err' => '命令字段错误',
    'cron_day_err' => '错误地指定了星期几',
    'cron_month_err' => '指定的月份无效',
    'cron_username_err' => '无效用户名',
    'cron_params_err' => '参数错误',
    'cron_start_ok' => '开始',
    'cron_stop_ok' => '停止',
    'cron_start_failed' => '启动失败，出现错误',
    'cron_inprogress_oper' => '请稍候',
    'cron_inprogress_oper_finish' => '操作完成',
    'cron_notins_ok' => '未安装',
    'cron_ins_ok' => '已安装',
    'cron_no_tasks' => '无任务',
    'cron_job_add_ok' => '作业添加成功',
    'Cron_demo_mess' => '在演示模式下，所有更改本质上只是视觉上的，实际上 CZK 作业不会被编辑，不会被创建或删除。',

    'cron_testrunjob' => '运行',
    'cron_hintAddJob' => '要添加的示例命令：<br/> 1. /usr/bin/phpXX/bin/php/home/user/script.php，其中XX - php版本<br/> <br/> 2.隐藏脚本消息输出 <br/> /usr/bin/phpXX/bin/php -q /home/user/script.php> /dev/null 2> /dev/null <br/> <br/> 3./usr/ bin / wget -t 1 -O - `http://site.com/script.php?p1 = a & p2 = b` ',
    'cron_hintAddJobPHPAllow' => '可用的 php 版本：',
    'cron_comand_sucessf' => '命令完成。<br>',

    'cronChangeJobStatusOk' => '作业状态更改成功',
    'cronChangeJobStatusHint' => '激活/停用作业',

	
);

?>

