<?php

$lang = array(
    'hostacc'           			=> '主机帐户',
    'hostacc_suspended_sites_ok'           => '主机帐户上的站点被阻止.',
    'hostacc_unsuspended_sites_ok'           => '主机帐户上的站点已解锁.',
    'hostacc_suspended_ftp_ok'           => '主机帐户上的 FTP 被阻止.',
    'hostacc_unsuspended_ftp_ok'           => '主机帐户上的 FTP 已解锁.',
    'hostacc_suspended_email_ok'           => '主机账户上的邮件被阻止.',
    'hostacc_unsuspended_email_ok'           => '主机帐户邮件已解锁.',
    'hostacc_suspended_cron_ok'           => '主机帐户上的cron被阻止.',
    'hostacc_unsuspended_cron_ok'           => '主机帐户上的 Cron 已解锁.',
    'hostacc_suspended_panel_ok'           => '用户面板访问被阻止.',
    'hostacc_unsuspended_panel_ok'           => '面板访问已解锁.',
    'hostacc_suspended_shell_ok'           => '外壳用户访问被阻止.',
    'hostacc_unsuspended_shell_ok'           => '外壳访问已解锁.',
    'hostacc_suspended_full_ok'           => '用户访问被完全阻止.',
    'hostacc_unsuspended_full_ok'           => '用户访问完全解锁.',
    'hostacc_unsuspended_user_del'           => '您没有足够的权限删除此用户.',
    'hostacc_unsuspended_user_del_ok'           => '用户已成功删除.',


    'hostacc_stat_susp_sites_title'		=> 'Блокировка сайтов',
    'hostacc_stat_susp_ftp_title'		=> 'Блокировка ФТП',
    'hostacc_stat_susp_email_title'		=> 'Блокировка почты',
    'hostacc_stat_susp_cron_title'		=> 'Блокировка Cron',
    'hostacc_stat_susp_shell_title'		=> 'Блокировка Шелл',
    'hostacc_stat_susp_panel_title'		=> 'Блокировка панели',
    'hostacc_stat_susp'           		=> 'Да',
    'hostacc_stat_unsusp'           		=> 'Нет',
    'hostacc_stat_susp_reason'           	=> 'Причина блокировки',
    'hostacc_stat_unsusp_ftpuser_failed'	=> 'ФТП пользователи разблокированы с ошибкой',

    'hostacc_stat_confirm_susp'           => 'Подтвердить блокировку',
    'hostacc_btn_susp'           => 'Заблокировать',
    'hostacc_btn_unsusp'           => 'Разблокировать',

    'hostacc_btn_susp_full'           => 'Заблокировать полностью',
    'hostacc_btn_unsusp_full'           => 'Разблокировать полностью',
    'hostacc_date_susp'           => 'Дата последней блокировки',
    'hostacc_date_unsusp'           => 'Дата последней разблокировки',

    'hostacc_delete_ip_from_acc_failed'           => 'Указанные ip: <br/>{ips}<br/> используются в: <br/>{domains}<br/> Для смены IP в конфигурации указанных доменов выше выберите один из доступных IP:<br/>',
    'hostacc_data_unset_plan'           => 'Не указан',
    'hostacc_data_unset_group'           => 'Не указана',

    'lang_rootaccess'			=> 'Доступ ROOT',
    'lang_ftp_access_restart'		=> 'Перезагрузка FTP',
    'lang_ftp_access_install'		=> 'Переустановка FTP',
    'lang_is_reseller'			=> 'Посредник',
    'lang_is_reseller_planview'		=> 'Просматривать план посреднику',
    'lang_is_reseller_groupview'	=> 'Просматривать группу посреднику',
    'lang_is_reseller_groupcreate'	=> 'Создавать группу посреднику',
    'lang_is_reseller_plancreate'	=> 'Создовать план посреднику',

    'msg_unlimited0'				=> 'неограниченно',
    'msg_unlimited'				=> '&#8734',
    'msg_no_permission_suspend_sites'		=> 'Нет разрешения чтобы остановить сайты!',
    'msg_no_permission_unsuspend_sites'		=> 'Нет разрешения чтобы запустить сайты!',
    'msg_no_permission_suspend_ftp'		=> 'Нет разрешения чтобы остановить FTP!',
    'msg_no_permission_unsuspend_ftp'		=> 'Нет разрешения чтобы запустить FTP!',
    'msg_no_permission_suspend_shell'		=> 'Нет разрешения чтобы остановить работу оболочки!',
    'msg_no_permission_unsuspend_shell'		=> 'Нет разрешения чтобы запустить оболочку!',
    'msg_no_permission_suspend_cron'		=> 'Нет разрешения чтобы остановить работу CRON!',
    'msg_no_permission_unsuspend_cron'		=> 'Нет разрешения чтобы запустить CRON!',
    'msg_no_permission_suspend_panel'		=> 'Нет разрешения чтобы остановить работу панели!',
    'msg_no_permission_unsuspend_panel'		=> 'Нет разрешения чтобы запустить панель!',
    'msg_no_permission_suspend_full'		=> 'Нет разрешения чтобы остановить работу полностью!',
    'msg_no_permission_unsuspend_full'		=> 'Нет разрешения чтобы сделать полный перезапуск!',

    'msg_no_permission_edit'		=> 'У вас нет прав чтобы редактировать это.',
    'msg_no_group_name'			=> 'Нет имени группы',
    'msg_no_group_add_ok'		=> 'Группа успешно добавлена',
    'msg_no_group_edit_ok'		=> 'Группа успешно отредактирована',
    'msg_seccess_del'			=> 'Успешно удалено',
    'msg_add_host_acct'			=> 'Добавить хост-аккаунт',
    'msg_edit_host_acct'		=> 'Редактировать хост-аккаунт',
    'msg_save_host_acct'		=> 'Сохранить хост-аккаунт',
    'msg_add_plan'			=> 'Добавить тариф',
    'msg_edit_plan'			=> 'Редактировать тариф',
    'msg_edit_user'			=> 'Редактировать пользователя',
    'msg_username'			=> 'Имя пользователя:',
    'msg_passwd'			=> 'Пароль:',
    'msg_ip'				=> 'Айпи адрес:',
    'msg_group'				=> 'Группа:',
    'msg_plan'				=> 'Тариф:',
    'msg_language'			=> 'Язык:',
    'msg_count_mailbox'			=> 'Количество почтовых ящиков:',
    'msg_bandwidth'			=> 'Трафик:',
    'msg_count_sites'			=> 'Количество сайтов:',
    'msg_count_db'			=> 'MySQL баз:',
    'msg_count_subdomains'		=> 'Количество DNS зон:',
    'msg_count_dns_zones'		=> 'Количество DNS зон:',
    'msg_count_mailperhour'		=> 'Количество писем в час:',
    'msg_count_disk'			=> 'Место на диске:',
    'msg_count_ftp_acct'		=> 'ФТП аккаунты:',
    'msg_shell_access'			=> 'Шелл доступ:',
    'msg_nginx_access'			=> 'Разрешить изменять размеры кешей для nginx:',
    'msg_owner'				=> 'Владелец:',

    'msg_seccess_added'			=> 'Успешно добавлено',
    'msg_seccess_edit'			=> 'Успешно отредактировано',

    'msg_only_number'			=> 'Указывайте только число в поле ',
    'msg_both_num_leter'		=> 'Указывайте только число или латинские буквы в поле ',

    'msg_only_number_bandwith'		=> 'Используя цифры укажите пропускную способности',
    'msg_only_number_sites'		=> 'Используя цифры укажите количество сайтов',
    'msg_only_number_subdomains'	=> 'Используя цифры укажите количество поддоменов',
    'msg_only_number_databases'		=> 'Используя цифры укажите количество БД',
    'msg_only_number_mailbox'		=> 'Используя цифры укажите количество почтовых ящиков',
    'msg_only_number_mailperhour'	=> 'Используя цифры укажите количество писем в час',
    'msg_only_number_ftp_acct'		=> 'Используя цифры укажите количество аккаунтов ftp',
    'msg_only_number_disk'		=> 'Используя цифры укажите диск',
    'msg_both_lang'		=> 'Укажите язык',
    'msg_both_shell'		=> 'Укажите оболочку для использования',
    'msg_both_plan'		=> 'Укажите название тарифа',
    'msg_both_template'		=> 'Укажите шаблон',


    'msg_everything_good'	=> 'Все выполнено без ошибок.',
    'msg_ip_wrong'		=> 'IP адрес указан неверно',
    'msg_exists_plan'		=> 'Такой тариф уже существует',
    'msg_done'			=> 'Выполнено',
    
    'msg_done_pass'		=> 'Пароль должен содержать минимум 7 символов',
    'msg_done_username'		=> 'Имя пользователя должно содержать максимум 8 символов',

    'msg_both_username'		=> 'Используя цифры и латинские буквы укажите имя пользователя. Минимум 3 символа.',
    'msg_both_group'		=> 'Используя цифры и латинские буквы укажите имя группы',
    
    'msg_no_user_sel'		=> 'Это не принадлежит пользователю',
    'msg_everything'		=> 'Все хорошо',

    'msg_edit_or_add_group'		=> 'Добавить новую группу или редактировать текущие →',
    'msg_edit_or_add_plan'		=> 'Добавить новый тариф или редактировать текущие →',

    'js_lang_select_ok'		=> 'Язык успешно изменен',

    'tpl_host_add_plan'		=> 'Добавить тарифный план',
    'tpl_host_edit_plan'	=> 'Редактировать тарифный план',
    'tpl_host_save_plan'	=> 'Сохранить тарифный план',
    'tpl_host_add_new_plan'	=> 'Добавить новый тариф',
    'tpl_host_plan_name'	=> 'Название тарифа:',
    'tpl_host_bandwidth'	=> 'Трафик:',
    'tpl_host_disk'		=> 'Диск:',
    'tpl_host_sites'		=> 'Сайты:',
    'tpl_host_subdomains'	=> 'DNS зоны:',
    'tpl_host_databases'	=> 'Базы данных:',
    'tpl_host_mailbox'		=> 'Почтовые ящики:',
    'tpl_host_mailperhour'	=> 'Писем в час:',
    'tpl_host_ftp_acct'		=> 'ФТП аккаунты:',
    'tpl_host_shell_access'	=> 'Shell доступ:',
    'tpl_host_lang'		=> 'Язык:',
    'tpl_host_lang_noselect'	=> 'Не выбран',

    'tpl_host_groups_acct'	=> 'Группы хост-аккаунтов',
    'tpl_host_current_group'	=> 'Текущая группа:',
    'tpl_host_groupEditortitle'	=> 'Редактор групп',
    'tpl_host_create_new_group'	=> 'Создать новую',
    'tpl_host_name_new_group'	=> 'Имя новой группы:',
    'tpl_host_select_not_defined'	=> 'не определено',
    'tpl_host_select_yes'	=> 'вкл',
    'tpl_host_select_no'	=> 'выкл',
    'tpl_host_select_form_save'	=> 'Сохранить',
    'tpl_host_select_form_del'	=> 'Удалить',

    'tpl_host_list_title'	=> 'Все хост-аккаунты',
    'tpl_host_list_login'	=> 'Логин',
    'tpl_host_list_plan'	=> 'Тариф',
    'tpl_host_list_homefolder'	=> 'Домашняя папка',
    'tpl_host_list_ip'	=> 'IP',
    'tpl_host_list_disk'	=> 'Диск',
    'tpl_host_list_group'	=> 'Группа',
    'tpl_host_list_control'	=> 'Управление',
    'tpl_host_list_edit'	=> 'Редактировать',
    'tpl_host_list_delete'	=> 'Удалить',
    'tpl_host_list_t_plan'	=> 'Тарифный план',
    'tpl_host_list_t_plans'	=> 'Тарифные планы',

    'tpl_host_single_title'		=> 'Информация о хост-аккаунте',
    'tpl_host_single_action'		=> 'Действия:',
    'tpl_host_single_abort'		=> 'Отмена',
    'tpl_host_single_create_date'	=> 'Дата создания:',
    'tpl_host_single_edit_date'		=> 'Дата последнего изменения:',
    'tpl_host_single_domain'		=> 'Домен',
    'tpl_host_single_ip'		=> 'IP',
    'tpl_host_single_home'		=> 'Домашний каталог',
    'tpl_host_single_aliases'		=> 'Алиасы',
    'tpl_host_single_triger_on'		=> 'Разблокировать',
    'tpl_host_single_triger_off'	=> 'Заблокировать',
    'tpl_host_single_change_lang'	=> 'Сменить язык',

    'lang_host_api'	=> 'Доступ по API',
    'lang_host_apifull'	=> 'Полный доступ по API(администратор)',
    'apifull_off'	=> 'Недостаточно прав для выполнения данного API запроса',

    'hostacc_suspended_sites'	=> 'Добавление, редактирование, удаление сайтов заблокировано. Пожалуйста, обратитесь к администратору.',
	'hostacc_del_process'	=> 'Удаляется...',
	'hostacc_successf_add'	=> 'Хост аккаунт успешно добавлен',

    'hostacc_change_pass_label'	=> 'Пароль',
    'hostacc_change_pass_label1'	=> 'Введите новый пароль',
    'hostacc_change_pass_label2'	=> 'Повторите новый пароль',
    'hostacc_change_pass_pass_diff'	=> 'Введенные пароли не совпадают.',
    'hostacc_change_pass_exec'	=> 'Сменить пароль',
    'hostacc_change_pass_exec_ok'	=> 'Пароль успешно изменен.',

    'hostacc_refresh_user_cache'	=> 'Обновить статистику пользователя',
    'hostacc_refresh_user_cache_btn'	=> 'Обновить',
    'hostacc_refresh_user_cache_ok'	=> 'Статистика пользователя успешно обновлена',

    'hostacc_user_search'	=> 'Поиск',
	'hostacc_return_main'	=> '← Вернуться к списку хост-аккаунтов',
    'hostacc_user_search_res_empty'	=> 'Ничего не найдено',

    'hostacc_user_search_pleasewait'	=> 'Выполняется поиск...',

    'msg_only_number_dnz_zones'	=> 'Используя цифры укажите количество DNS зон',
    'hostacc_sel_addgroup'	=> 'Добавьте группу',
    'hostacc_sel_addpackage'	=> 'Добавьте тариф',
    'hostacc_noaddhostacc_yet'	=> 'Хост-аккаунты еще не добавлены',
	'hostacc_no_plans'	=> 'Тарифные планы еще не добавлены',

    'hostacc_updatecache_detail'	=> 'Выполнить пересчет статистики: количество сайтов, почтовые ящики, использованное место, количество ФТП-аккаунтов, количество баз данных.',

    'hostacc_user_alreadyexist'	=> 'Пользователь с таким именем уже существует',
    'hostacc_user_userhaventdomain'	=> 'Еще нет добавленных доменов',
    'hostacc_user_signin'	=> 'Войти',
    'hostacc_user_signin_warning'	=> 'При входе под выбранным пользователем вы будете разавторизованы из-под текущего. <br/>Подтвердить авторизацию ',
    'hostacc_user_signin_warning_yes'	=> 'Да',
    'hostacc_user_signin_warning_no'	=> 'Нет',
    'hostacc_user_signin_failed'	=> 'Ошибка авторизации. Необходимо сбросить пароль пользователю.',
    'hostacc_user_signin_process'	=> 'Авторизация...',
    'hostacc_user_plan_not_set'	=> 'Не указан',

    'hostacc_header_admin_param' => 'Все, что не определено, запрещено.',
    'hostacc_header_user_param' => 'Все, что не определено, разрешено.',
    'hostacc_chache_name' => 'Сменить имя',	
    'hostacc_input_name' => 'Введите новое имя',	
    'hostacc_suc_change' => 'Успешно выполнено',	
    'hostacc_suc_change_empty' => 'Пустое значение в названии группы',
    'hostacc_error_name_group' => 'Ошибка в названии',
    'hostacc_error_no_user' => 'Такого пользователя не существует',
    'hostacc_confirm_userdel' => 'Подтвердите удаление пользователя ',
    'hostacc_confirm_userdel_yes' => 'Да',
    'hostacc_confirm_userdel_no' => 'Нет',

    'hostacc_confirm_universal_yes' => 'Да',
    'hostacc_confirm_universal_no' => 'Нет',

    'hostacc_usernotexist' => 'Указанного пользователя не существует',

    'hostacc_stat_susp_sites_hint'		=> 'Сайты заблокированы',
    'hostacc_stat_susp_ftp_hint'		=> 'ФТП заблокирован',
    'hostacc_stat_susp_email_hint'		=> 'Почта заблокирована',
    'hostacc_stat_susp_cron_hint'		=> 'Cron заблокирован',
    'hostacc_stat_susp_panel_hint'		=> 'Панель заблокирована',
    'hostacc_stat_susp_full_hint'		=> 'Доступ полностью заблокирован',
    'hostacc_stat_susp_reason_hint'           	=> 'Причина блокировки: ',
    'hostacc_stat_susp_reason_hint_notset'           	=> 'не указана',
    'hostacc_incorecly_simbol'           	=> 'Запрещенный символ в названии тарифа',

    'hostacc_createjailuser'           	=> 'Jail окружение',
    'hostacc_createjailuserhint'           	=> 'Пользователь будет помещен в jail окружение для ограничения доступа',

    'hostacc_jailTitle'           	=> 'Настройка Jail',
    'hostacc_jailStatusTitle'           	=> 'Jail Shell',
    'hostacc_jailStatusTitlePHP'           	=> 'Jail PHP',
    'hostacc_jailStatusSave'           	=> 'Сохранить',
    'hostacc_jailStatusDesel'           	=> 'Отключить всем Jail Shell',
    'hostacc_jailStatusSel'           	=> 'Включить всем Jail Shell',
    'hostacc_jailStatusDeselPHP'           	=> 'Отключить всем Jail PHP',
    'hostacc_jailStatusSelPHP'           	=> 'Включить всем Jail PHP',
    'hostacc_jailStatusRebuild'           	=> 'Применить',
    'hostacc_jailStatusSetResOk'           	=> 'Jail окружение изменено успешно',
    'hostacc_jailStatusSetResFail'           	=> 'Jail окружение не изменено',
    'hostacc_jailPHPHint'           	=> 'PHP будет выполняться в jail окружение. Доступно только для моста fastcgi(php-fpm)',
    'hostacc_jailnewaccShell'           	=> 'Новые хост-аккаунты помещать в Jail Shell',
    'hostacc_jailnewaccPhp'           	=> 'Новые хост-аккаунты помещать в Jail PHP',
    'hostacc_jailStatusAutoNewAcc'           	=> 'Сохранить',
    'hostacc_jailStatusAutoNewAccSaveok'           	=> 'Сохранено успешно. <br/>Если был изменен Список пакетов доступных в Jail, необходимо выполнить перестроение Jail с помощью таблицы внизу',

    'hostacc_jailerrorMountMysql'           	=> 'Ошибка монтирования сокета mysql',

    'hostacc_confirmDelPlan'           	=> 'Подтвердите удаление тарифа ',
    'hostacc_limit_mysql_user'           	=> 'Лимит mysql соединений для user',
    'hostacc_max_questions'           	=> 'MYSQL лимит на количество запросов за час',
    'hostacc_max_updates'           	=> 'MYSQL лимит на редактирования данных в час',
    'hostacc_max_connections'           	=> 'MYSQL лимит на одновременных подключений',
    'hostacc_max_user_connections'           	=> 'MYSQL лимит на подключений пользователя в час',
    'hostacc_error_msg_questions'           	=> 'Используя цифры укажите значение max_questions',
    'hostacc_error_msg_updates'           	=> 'Используя цифры укажите значение max_updates',
    'hostacc_error_msg_user_connections'           	=> 'Используя цифры укажите значение max_user_connections',
    'hostacc_error_msg_connections'           	=> 'Используя цифры укажите значение max_connections',
    'hostacc_jailreinit'           	=> 'Выполняется переинициализация jail окружения пользователей. Пожалуйста, подождите.',
    'hostacc_jailreinitParams'           	=> 'Указанные параметры: ',
    'hostacc_jailreinitParamsHost'           	=> 'Установить статус джейл окружения: ',
    'hostacc_jailreinitParamsPHP'           	=> 'Установить статус джейл окружения php: ',
    'hostacc_jailreinitParamsPHPForce'           	=> 'Выполнить перестройку виртуальных хостов пользователей: ',
    'hostacc_jailreinitParamsHostOn'           	=> 'Включить',
    'hostacc_jailreinitParamsHostOff'           	=> 'Выключить',
    'hostacc_jailreinitParamsHostRebuildYes'           	=> 'Да',
    'hostacc_jailreinitParamsHostRebuildNo'           	=> 'Нет',
    'hostacc_jailreinitBaseOnHostConf'           	=> 'Выполняется переинициализация джейл окружения на основе текущих настроек пользователя.',
    'hostacc_jailConfTitle'           	=> 'Настройки',
    'hostacc_jailListAppAvailInJail'           	=> 'Список пакетов доступных в Jail',
    'hostacc_jailListAppAvailInJailHint'           	=> 'Указать через ; , пробел или каждый пакет с новой строки. Для применения изменений после сохранения необходимо выполнить перестроение jail для пользователей',
    'hostaccPleaseWaitAuth'           	=> 'Выполняется авторизация. Пожалуйста, подождите.',

    'hostaccRebuldJailAll'           	=> 'Перестроить Jail окружение',
    'hostaccRebuldJailAllConfirm'     	=> 'Подтвердите перестроение Jail окружения для выбранных пользователей. <br/>Ориентировочное время выполнения от 1 до 20 минут в зависимости от количества выбранных пользователей.',
    'hostaccRebuldViewLog'           	=> 'Смотреть лог',
    'hostaccRebuildAlreadyrun'          => 'Перестроение Jail уже запущено. Посмотрите, пожалуйста, логи',
    'hostaccRebuildStartOk'           	=> 'Перестроение Jail успешно запущено. Просмотр лога по кнопке Смотреть лог. <br/>В процессе перестройки Jail запрещены любые операции с Jail. <br/>Пожалуйста, дождитесь завершения операции.',
    'hostaccRebuildStartFailed'         => 'Ошибка входящего списка пользователей',
    'hostaccRebuildViewLogBtn'          => 'Смотреть лог перестройки Jail',
    'hostaccRebuildListUser'           	=> 'Список пользователей для перестроения: ',
    'hostaccRebuildStartJailShell'     	=> 'Перестроение Jail Shell',
    'hostaccRebuildStartJailPHP'       	=> 'Перестроение Jail PHP',
    'hostaccRebuildFinish'           	=> 'Jail перестроение завершено',
    'hostaccerror_e'           		=> 'Ошибка. Зарезервировано значение в mysql (1E или 2e и тд.)',

    'hostacc_max_user_task'  	=> 'Максимальное количество задач (пусто - неограничено)',
    'hostacc_max_user_memory'  	=> 'Максимальное количество памяти в MB (пусто - неограничено)',
    'hostacc_max_user_cpu'  	=> 'Максимальная нагрузка CPU в % (100% - 1 ядро,[200%...], пусто - неограничено)',
    'hostacc_max_user_ior'  	=> 'Максимальное IO чтения (пусто - неограничено)',
    'hostacc_max_user_iow'  	=> 'Максимальное IO записи (пусто - неограничено)',
    'hostacc_empty_log_jail'  	=> 'Логи по перестройке jail, не найдены.',
    'hostacc_user_reserv_system'  	=> 'Пользователь зарезервирован системой.',
    'hostacc_error_name_numper_all'  	=> 'Хостаккаунт не должен состоять из одних цифр.',
    'hostacc_error_connect_mysql'  	=> 'Пользователь не может быть удален. Ошибка подключения к базе данных',
    'hostacc_error_umount_user'  	=> 'Ошибка размонтирования директорий пользователя.',
    'hostacc_error_clear_rc_local'  	=> 'Ошибка очистки rc.local',
    'hostacc_error_add_user_linux'  	=> 'Ошибка добавления пользователя linux',
    'hostacc_error_add_user_err'  	=> 'Хостаккаунт добавлен.',
    'hostacc_error_error_mount'  	=> 'Ошибка монтирования ',
    'hostaccChangePassForFTP'	=> 'Сменить пароль для FTP',
    'hostacc_disable_brainy_connect'	=> 'Сервис brainy-socket.service отключен.',
    'hostacc_error_brainy_connect_not_found'	=> 'Сервис brainy-socket.service не найден.',

    'hostacc_RebuildJailSkeleton'	=> 'Перестроить Jail Skeleton',
    'hostacc_RebuildJailSkeletonOK'	=> 'Jail Skeleton перестроен успешно. Для применения изменений необходимо выполнить перестроение jail для пользователей',
    'hostacc_RebuildJailSkeletonHint'	=> 'Создает/обновляет копию системных файлов для работы Jail',
    'hostacc_error_set_limit_mysql'	=> 'При установенной mariadb 10.4 отключено ограниение на количество запросов за час',
    'hostacc_error_set_limit_mysql_time'	=> 'При установенной mariadb 10.4 отключено ограниение на редактирования данных в час',
    'hostacc_error_set_limit_mysql_connection'	=> 'При установенной mariadb 10.4 отключено ограниение на одновременных подключений',
    'hostacc_error_set_limit_mysql_connection_time'	=> 'При установенной mariadb 10.4 отключено ограниение на подключений пользователя в час',
    'tpl_host_nginx_access'	=> 'Разрешить изменять размеры кешей для nginx:',
    'tpl_host_sharedata_title'	=> 'Общие данные',
    'hostacc_listhostacc'	=> 'Список хост-аккаунтов',
    'hostacc_server_resource_systemd'=>'Ограничение ресурсов пользователю',
    'hostacc_grouprightAdmin'=>'Администраторские',
    'hostacc_grouprightUser'=>'Пользовательские',
    'hostacc_blockextended'=>'Расширенная блокировка',
	'hostacc_error_remove_user'  	=> 'Ошибка удаления пользователя. Доступ для root в панели закрыт, и данный пользователь находится в группе root, для управления панелью.',
    'hostacc_error_remove_group_root'	=> 'Ошибка удаления или редактирования группы. Доступ для root в панели закрыт, и данное действие заблокирует вход в панель пользователю.',
    'hostacc_block_all_sites'	=> 'Заблокировать все сайты',
    'hostacc_block_all_sites_list'	=> 'Список заблокированных сайтов', 
    'hostacc_stat_susp_email_hint'		=> 'Email заблокированы',
    'hostacc_stat_susp_shell_hint'		=> 'Shell заблокирован',	
    'hostacc_error_add_system_jail'		=> 'Ошибка добавления системных пакетов, или директорий',	

);

?>
