<?php

$lang = array(
    'index_logout' => '退出',
     'index_home' => '首页',
     'index_search' => '搜索',
'index_quick_search' => '快速搜索',
'index_section_search' => '分类搜索',

    'index_control' => '控制',
     'index_conf_server' => '服务器配置',
     'index_host_acct' => '主机账户',
     'index_groups_acct' => '主机帐户组',
     'index_plans_acct' => '主机账户费率',
     'index_manage_ip' => 'IP 地址管理器',
     'index_manage_mem' => '资源管理器',
     'index_update' => '更新',
     'index_reboot' => '服务器重启',

    'index_www' => '网络服务器',
     'index_www_install' => '安装网络服务器',
     'index_php_install' => '安装和配置 PHP',
     'index_php_delete' => '删除网络服务器和 PHP',

     'index_pass_folder' => '目录密码',
     'index_jmp_http' => 'HTTP 重定向',
     'index_jmp_sites' => '网站重定向',
     'index_apacserver_optimization' => '网站优化',
'index_apacserver_error_pages' => '错误页面',
'index_webserver_config' => '虚拟主机的单独配置',

    'index_databases' => '数据库',
    'index_mysql_db' => 'MySQL / MariaDB 管理',
    'index_phpmyadmin' => '管理 PHPMyAdmin',

    'index_email' => '邮件',
    'index_email_down' => '发件服务',
    'index_email_up' => '收件服务',
    'index_more_install' => '批量安装服务',
    'index_init_mail' => '配置邮件服务',
    'index_control_queue' => '队列控制',
    'index_control_spf' => 'SPF 控制',
    'index_control_dmarc' => '控制 DMARC',
    'index_mail_acct' => '邮件账户',
    'index_jmp_mail' => '邮件转发',
    'index_control_opendkim' => 'Opendkim 控制',
    'index_control_clamv' => 'Clamav 控制',
    'index_control_spam' => '控制 Spamassassin',
    'index_auto_answer' => '自动回复',
    'index_mail_filtet' => '邮件过滤',
    'index_mail_statistic' => '邮件统计',
    'index_mail_default' => '默认邮箱',

    'index_dns' => '名称服务器',
     'index_dns_control_zone' => 'DNS 区域管理',
     'index_dns_ns' => '域名服务器',
     'index_dns_init_claster' => 'DNS集群',

     'index_application' => '应用程序',
     'index_application_manager' => '应用管理器',
     'index_autoinit_cms' => 'CMS 自动安装程序',
     'index_user_cms' => '为用户安装 CMS',
     'index__file_manager' => '文件管理器',
     'index_ssh' => 'SSH 服务器',
     'index_cron' => 'CRON',
     'index_ftp' => 'FTP 服务器',

    'index_static' => '统计',
     'index_manage_proc' => '进程管理器',
     'index_top' => 'TOP',
     'index_trafic_use' => '流量使用',
     'index_average_load' => '负载均衡',
     'index_static_processing' => '统计处理工具',
     'index_logging' => '记录',
     'index_monitoring' => '服务监控',
     'index_mysql_process' => 'MySQL 进程列表',
     'index_status_web' => '网络服务器状态',
     'index_hardware_info' => '服务器信息',
     'index_smart_mon' => 'S.M.A.R.T 监控',

    'index_cert_ssl' => 'SSL 证书',
     'index_cert_service' => '服务证书',
     'index_cert_user' => '用户证书',

     'index_backup' => '备份',
     'index_config_backup' => '配置备份',
     'index_jmp_server' => '服务器间传输',

     'index_network' => '网络',
     'index_network_tools' => '管理 IPTables',
     'index_stat_connect' => '监控连接',
'index_csf' => 'CSF 防火墙',
'index_speedtest' => '服务器测试',

     'index_security' => '安全',
     'index_antivirus' => '防病毒',
     'index_mod_security' => '管理 ModSecurity',

   'index_general' => '一般',
    'index_general_info' => '一般信息',

    'index_webwww' => 'WWW',
    'index_web_sites' => '网站',
    'index_web_virthost' => '其他站点设置',
    'index_cloudflare' => 'Cloudflare',
    'index_black_domain' => '禁止域名',
    'index_dns_editing' => 'DNS 编辑器',

    'index_ftp_section' => 'FTP',
    'index_ftp_section_acct' => 'FTP 账户',

    'index_webserver_control' => 'Web 服务器控件',

    'index_section_mail' => '邮件',
    'index_section_mailbox' => '邮箱',
    'index_section_jmp_mail' => '邮件重定向',
    'index_section_spf' => 'SPF',
    'index_section_dkim' => 'DKIM',
    'index_section_dmarc' => 'DMARC',

    'index_section_cert' => '证书',
    'index_control_ssl' => 'SSL 控制',

    'index_sect_bd' => 'DB',
    'index_sect_bd_mysql' => 'MySQL 数据库',
    'index_sect_bd_myadmin' => 'PHPMyAdmin',

    'index_sect_tools' => '实用程序',
     'index_sect_tools_cron' => 'CRON 作业',
     'index_sect_tools_backup' => '备份',
     'index_sect_tools_fmanager' => '文件管理器',
     'index_sect_tools_cms' => 'CMS 自动安装程序',

     'index_sect_info' => '信息',
     'index_sect_info_monitor' => '服务监控',
     'index_sect_info_log' => '日志',
     'index_sect_info_ns' => '默认托管服务器',
     'index_sect_info_php' => 'PHP 设置',
     'index_sect_info_usage' => '流量使用',
     'index_sect_info_average' => '负载均衡',
     'index_sect_info_stat' => '统计工具',

    'index_brainy_tel'		=> '',
    'index_brainy_msg'		=> '',

   'index_topinfo_ip' => '所有用户IP',
    'index_topinfo_unlim' => '无限制',
    'index_topinfo_unlimited' => '&#8734',
    'webhost_configurator' => '虚拟主机单独配置',
    'index_blacklist' => '检查黑名单中的服务器',
    'index_mail_mailing' => '邮件列表',

    'index_databases_postgresql' => 'PostgreSQL 数据库',

    'index_LogStatDom' => '管理站点日志',

    'index_cluster' => '集群',
    'index_cluster_server' => '服务器集群',
    'index_cluster_ip' => 'IP 集群',
    'indexRouteMail' => '邮件路由',
    'index_cluster_mysql' => '数据库集群',

    'index_controlpanel' => '服务器控制面板',
    'index_close' => '关闭',
'index_stopautorefresh' => '停止自动刷新',
    'index_continueautorefresh' => '继续自动刷新',
    'index_method_withname' => '命名方法',
    'index_notexistforjquery' => 'jquery.tooltip不存在',
    'index_date_fullJan' => '一月',
    'index_date_fullFeb' => '二月',
    'index_date_fullMar' => '三月',
    'index_date_fullApr' => '四月',
    'index_date_fullMay' => '五月',
    'index_date_fullJun' => '六月',
    'index_date_fullJul' => '七月',
    'index_date_fullAug' => '八月',
    'index_date_fullSep' => '九月',
    'index_date_fullOct' => '十月',
    'index_date_fullNov' => '十一月',
    'index_date_fullDec' => '十二月',
    'index_date_fullJan_short' => '一月',
    'index_date_fullFeb_short' => '二月',
    'index_date_fullMar_short' => '三月',
    'index_date_fullApr_short' => '四月',
    'index_date_fullMay_short' => '五月',
    'index_date_fullJun_short' => '六月',
    'index_date_fullJul_short' => '七月',
    'index_date_fullAug_short' => '八月',
    'index_date_fullSep_short' => '九月',
    'index_date_fullOct_short' => '十月',
    'index_date_fullNov_short' => '十一月',
    'index_date_fullDec_short' => '十二月',
    'index_date_mon' => '星期一',
    'index_date_tue' => '星期二',
    'index_date_wed' => '星期三',
    'index_date_thu' => '星期四',
    'index_date_fri' => '星期五',
    'index_date_sat' => '星期六',
    'index_date_sun' => '星期日',
    'index_date_mon_short' => '星期一',
    'index_date_tue_short' => '星期二',
    'index_date_wed_short' => '星期三',
    'index_date_thu_short' => '星期四',
    'index_date_fri_short' => '星期五',
    'index_date_sat_short' => '星期六',
    'index_date_sun_short' => '星期日',
    'index_date_mon_min' => '星期一',
    'index_date_tue_min' => '星期二',
    'index_date_wed_min' => '星期三',
    'index_date_thu_min' => '星期四',
    'index_date_fri_min' => '星期五',
    'index_date_sat_min' => '星期六',
    'index_date_sun_min' => '星期日',
    'index_date_ready' => '完成',
    'index_date_prev' => '上一个',
    'index_date_next' => '下一个',
    'index_date_today' => '今天',
    'index_sect_graphs' => '监控图表',

);
?>
