<?
$lang = array(
    'logging' => '日志',
    'logging_log' => '日志',
    'logging_select_user' => '选择用户：',
    'logging_not_selected' => '未选中',
    'logging_setting_rotation' => '设置服务日志轮换→',
    'logging_users_log' => '用户归档日志',
    'logging_download' => '下载',
    'logging_download_log' => '下载这段日志',
    'logging_download_all_log' => '下载整个当前日志',
    'logging_path_log' => '日志文件的路径：',
    'logging_searche_log' => '在日志中搜索一个短语：',
    'logging_show' => '显示',
    'logging_prev_record' => '以前的记录',
    'logging_next_record' => '下一条记录',
    'logging_line_latest' => '行（最后一行）来自',
    'logging_line_display' => '显示多少行：',
    'logging_add_log_rotation' => '将日志添加到轮换',
    'logging_back_log' => '← 返回日志',
    'logging_not_install' => '未安装',
    'logging_install' => '安装',
    'logging_successfully' => '安装成功。刷新页面 ',
    'logging_stat_ins' => '活动',
    'logging_nologs' => '没有可用的日志',
    'logging_titlemanrot' => '旋转控制',
    'logging_namelog' => '日志名称',
    'logging_titlelog1' => '日志',

    'logging_rotUserLogsTitle' => '轮换用户日志',
    'logging_rotUserLogsHint' => '全局启用/禁用所有用户的日志轮换',

    'logging_ConfPeriod' => '开始时间',
    'logging_ConfPeriodHourly' => '每小时',
    'logging_ConfPeriodDaily' => '每一天',
    'logging_ConfPeriodWeekly' => '每周',
    'logging_ConfPeriodMonthly' => '每个月',
    'logging_ConfSave' => '保存',
    'logging_ConfSaveAllUser' => '适用于所有用户',
    'logging_ConfCountCountLogs' => '保留旧日志的数量',
    'logging_ConfCountCountLogsPlace' => '请输入一个数字',
    'logging_ConfCompress' => '压缩',
    'logging_ConfFormat' => '名称格式',
    'logging_ConfFormatDate' => '日期',
    'logging_ConfFormatNumber' => '序列号',
    'logging_ConfUserTitleConfigure' => '配置用户日志轮换',

    'logging_activeServiceLog' => '轮播日志',
    'logging_confLogrotSaveok' => '保存成功',
    'logging_confLogrotEnDisOk' => '保存成功',
    'logging_not_rotation' => '输入日志数量',


);
