<?php

$lang = array (
	'mailclient' => 'Почтовые ящики',
	'on'=> 'Включить',
	'off'=> 'Выключить',
	'status_on'=>'Включен',
	'status_off'=>'Отключен',
	
	'tpl_mail_autoanswer'		=>'Автоответчик',
	'tpl_mail_user'			=>'Пользователь',
	'tpl_mail_box'			=>'Ящик',
	'tpl_mail_interval'		=>'Интервал',
	'tpl_mail_from'			=>'От',
	'tpl_mail_subject'		=>'Тема',
	'tpl_mail_body_mail'		=>'Тело письма',
	'tpl_mail_action'		=>'Действие',
	'tpl_mail_is_active'		=>'Активен',
	'tpl_mail_add'			=>'Добавить',
	'tpl_mail_del'			=>'Удалить',
	'tpl_mail_edit'			=>'Редактировать',
	'tpl_mail_save'			=>'Сохранить',
	'tpl_mail_abort'		=>'Отменить',

	'tpl_mail_antivir_control'	=> 'Управление антивирусом',
	'tpl_mail_antivir_status'	=> 'Состояние:',
	'tpl_mail_on'			=> 'Включить',
	'tpl_mail_off'			=> 'Выключить',
	'tpl_mail_tools'		=> 'Настройки',
	
	'tpl_mail_account'		=> 'Почтовые аккаунты',
	'tpl_mail_account_add'		=> 'Добавление аккаунта',
	'tpl_mail_account_box'		=> 'Аккаунт',
	'tpl_mail_passwd'		=> 'Пароль',
	'tpl_mail_quota'		=> 'Квота',
	'tpl_mail_email'		=> 'Email',
	'tpl_mail_email_mail'		=> 'Почта',
	'tpl_mail_enter_passwd'		=> 'Введите пароль',
	'tpl_mail_open_roundcube'	=> 'Roundcube',
	'tpl_mail_open_squire'		=> 'Squiremail',
	'tpl_mail_open_webmail'		=> 'Webmaillite',

	'tpl_mail_webmail'		=> 'Webmail',

	'tpl_mail_email_default'	=> 'Почтовый ящик по-умолчанию',
	'tpl_mail_domen'		=> 'Домен',
	'tpl_mail_not_install'		=> 'Не установлено',
	'tpl_mail_jmp_email'		=> 'Переслать на емайл',
	'tpl_mail_jmp_to'		=> 'Переслать на ',
	'tpl_mail_jmp_email'		=> 'Переслать на емайл',
	'tpl_mail_jmp_email_all'	=> 'Перенаправление почты',
	'tpl_mail_jmp_domain_all'	=> 'Перенаправление доменов',
	'tpl_mail_enter_email'		=> 'Введите емайл',
	'tpl_mail_failed_delivery'	=> 'Не удалось доставить',
	'tpl_mail_blackhole'		=> 'Blackhole',
	
	'tpl_mail_service_noinst'		=> 'Сервис не установлен',
	'tpl_mail_service_norun'		=> 'Сервис не запущен',
	'tpl_mail_service_control'		=> 'Управление сервисом',
	
	'tpl_mail_record_add'		=> 'Добавление записи',
	'tpl_mail_jmp_domain2from'	=> 'Домен, с которого перенаправлять',
	'tpl_mail_jmp_email2to'		=> 'Почтовый, на который отправлять',
	'tpl_mail_jmp_box_all'		=> 'Перенаправление ящиков',
	'tpl_mail_jmp_box_source'	=> 'Email, с которого перенаправлять',
	'tpl_mail_jmp_box_target'	=> 'Email или конвейер к программе(Pipe to a Program), на который отправлять (можно несколько, через запятую)',
	'tpl_mail_jmp_box_target_save'	=> 'Сохранять письма в исходном ящике (должен быть создан в разделе почтовые аккаунты)?',
	'tpl_mail_jmp'			=> 'Перенаправление',

	'tpl_mail_control_opendkim'	=> 'Управление opendkim',
	'tpl_mail_control_opendmarc'	=> 'Управление opendmarc',
	'tpl_mail_control_clamav'	=> 'Управление clamav',
	'tpl_mail_control_spam'		=> 'Управление Spamassassin',
	'tpl_mail_enter_to_email'	=> 'Войти в почтовый ящик',
	'tpl_mail_fine_tuning'		=> 'Тонкая настройка',
	'tpl_mail_options'		=> 'Опции',
	'tpl_mail_status'		=> 'Статус',
	'tpl_mail_filter'		=> 'Фильтрация почты',
	'tpl_mail_filter_control'	=> 'Управление фильтрами',
	'tpl_mail_filters'		=> 'Фильтры',
	'tpl_mail_control'		=> 'Управление',
	'tpl_mail_mass_install'		=> 'Массовая установка',
	'tpl_mail_control_queue'	=> 'Управление очередью',
	'tpl_mail_control_spf'		=> 'Управление SPF',
	'tpl_mail_control_dmarc'	=> 'Управление DMARC',
	'tpl_mail_filter_name'		=> 'Назание фильтра',
	'tpl_mail_rules'		=> 'Правила',
	'tpl_mail_filter_header'	=> 'Фильтр',

	'tpl_mail_rules_from'		=> 'От',
	'tpl_mail_rules_subject'	=> 'Тема',
	'tpl_mail_rules_to'		=> 'Получатель',
	'tpl_mail_rules_reply'		=> 'Ответчик',
	'tpl_mail_rules_bodytest'	=> 'Тело письма',
	'tpl_mail_rules_any_header'	=> 'Любой заголовок',
	'tpl_mail_rules_any_recipient'	=> 'Любой получатель',
	'tpl_mail_rules_no_deviver'	=> 'Не было отправлено',
	'tpl_mail_rules_error'		=> 'Содержит ошибки',
	'tpl_mail_rules_id'		=> 'ID в очереди',
	'tpl_mail_rules_status'		=> 'Спам статус',
	'tpl_mail_rules_bar'		=> 'Спам уровень',
	'tpl_mail_rules_scope'		=> 'Спам объем',

	'tpl_mail_rules_contains'	=> 'Содержит',
	'tpl_mail_rules_match'		=> 'Совпадение',
	'tpl_mail_rules_no_contains'	=> 'Не содержит',
	'tpl_mail_rules_equals'		=> 'Равно',
	'tpl_mail_rules_begin'		=> 'Начинаетя с',
	'tpl_mail_rules_end'		=> 'Заканчивается на',
	'tpl_mail_rules_no_begin'	=> 'Не начинается с',
	'tpl_mail_rules_no_end'		=> 'Не заканчивается на',
	'tpl_mail_rules_no_match'	=> 'Не совпадает',
	'tpl_mail_rules_above'		=> 'Больше(числа)',
	'tpl_mail_rules_no_above'	=> 'Не больше(числа)',
	'tpl_mail_rules_below'		=> 'Меньше (числа)',
	'tpl_mail_rules_no_below'	=> 'Не меньше (числа)',

	'tpl_mail_rules_discrab'	=> 'Отклонить',
	'tpl_mail_rules_redirect'	=> 'Перенаправить',
	'tpl_mail_rules_fail'		=> 'Отказ',
	'tpl_mail_rules_stop'		=> 'Остановить фильтр',
	'tpl_mail_rules_deliver'	=> 'Положить в папку',
	'tpl_mail_rules_pipe'		=> 'Переправить программе',
	
	'tpl_mail_mass_install_prog'	=> 'Массовая установка ПО',
	'tpl_mail_setup'		=> 'Установить',
	'tpl_mail_more'			=> 'Подробнее',
	'tpl_mail_hide'			=> 'Скрыть',

	'tpl_mail_message_time'		=> 'Время',
	'tpl_mail_message_id'		=> 'ID сообщения',
	'tpl_mail_message_sources'	=> 'Отправители',
	'tpl_mail_message_target'	=> 'Получатели',
	'tpl_mail_message_size'		=> 'Размер',
	'tpl_mail_message_status'	=> 'Статус',
	'tpl_mail_message_action'	=> 'Действие',
	'tpl_mail_message_queue'	=> 'В очередь',

	'tpl_mail_receive_name'		=> 'Настройка сервера входящей почты',
	'tpl_mail_receive_installed'	=> 'Установлен',
	'tpl_mail_receive_working'	=> 'Работает',
	'tpl_mail_receive_more'		=> 'Подробнее',
	'tpl_mail_receive_hide'		=> 'Скрыть',
	'tpl_mail_receive_install'	=> 'Установить',
	'tpl_mail_receive_delete'	=> 'Удалить',
	'tpl_mail_receive_reinstall'	=> 'Переустановить',
	'tpl_mail_receive_start'	=> 'Запустить',
	'tpl_mail_receive_stop'		=> 'Остановить',
	'tpl_mail_receive_restart'	=> 'Перезапустить',

	'tpl_mail_email_clients'	=> 'Почтовые клиенты',

	'tpl_mail_send_name'		=> 'Настройка сервера исходящей почты',
	'tpl_mail_send_warning'		=> 'При установке сервер исходящей почты Exim будет удален',
	'tpl_mail_send_postfix'		=> 'Postfix',
	'tpl_mail_send_exim'		=> 'Exim',
	'tpl_mail_send_warning_postfix'	=> 'При установке сервер исходящей почты Postfix будет удален',
	'tpl_mail_send_dkim'		=> 'OpenDKIM',
	'tpl_mail_send_dmarc'		=> 'OpenDMARC',
	'tpl_mail_send_antispam'	=> 'Антиспам',
	'tpl_mail_send_antivirus'	=> 'Антивирус',

	'tpl_mail_spf_control'		=> 'Управление SPF',
	'tpl_mail_dmarc_control'	=> 'Управление DMARC',

	'tpl_mail_spf_select_user'	=> 'Выберите пользователя',
	'tpl_mail_spf_no_domain'	=> 'Нет доступных доменов, или не найдены зоны для доменов',
	'tpl_mail_spf_domain'		=> 'Домен',
	'tpl_mail_spf_action'		=> 'Действие',
	'tpl_mail_spf_saved'		=> 'Запись',
	'tpl_mail_dmarc_select_user'	=> 'Выберите пользователя',
	'tpl_mail_dmarc_no_domain'	=> 'Нет доступных доменов',
	'tpl_mail_dmarc_domain'		=> 'Домен',
	'tpl_mail_dmarc_action'		=> 'Активация',
	'tpl_mail_dmarc_jmp'		=> 'Действие',
	'tpl_mail_dmarc_mailto'		=> 'Адрес для отчетов',
	'tpl_mail_dmarc_saved'		=> 'Запись',

	'tpl_mail_rouncube'		=> 'Roundcube',
	'tpl_mail_webmaillite'		=> 'WebMailLite',

	'msg_mail_err_mysql_connect'	=> 'Ошибка соединения с MySQL сервером: ',
	'msg_mail_webmail'		=> 'Webmail',
	'msg_mail_delete'		=> 'Удалить',
	'msg_mail_process_ok'		=> 'Процес был выполнен успешно.',
	'msg_mail_process_last_log'	=> 'Последняя строка команды выполнения: ',
	'msg_mail_not_your_domain'	=> 'Это не ваш домен',
	'msg_mail_enter_def_action'	=> 'Укажите действие по умолчанию',
	'msg_mail_enter_email'		=> 'Ввведите почтовый ящик',
	'msg_mail_process_ok'		=> 'Операция выполнена успешно',
	'msg_mail_choose_user'		=> 'Выберите пользователя',
	'msg_mail_enter_domain'		=> 'Введите домен',
	'msg_mail_already_domain'	=> 'Такой домен уже существует',
	'msg_mail_chouse_option'	=> 'Укажите опцию',
	'msg_mail_already_autoanswer'	=> 'Автоответчик уже существует',
	'msg_mail_enter_time'		=> 'Укажите время',
	'msg_mail_enter_text'		=> 'Введите текст',
	'msg_mail_enter_subject'	=> 'Тема',
	'msg_mail_enter_body'		=> 'Тело письма',
	'msg_mail_ver_txt'		=> ' версия:',

	'msg_mail_run'			=> 'Запущен',
	'msg_mail_stoped'		=> 'Остановлен',
	'msg_mail_success_edit'		=> 'Редактирование прошло успешно',
	
	'js_mail_process_progress'		=> 'Идет процесс установки... Пожалуйста, подождите.',
	'js_mail_process_finish'		=> 'Процесс завершен',
	'js_mail_not_install'			=> 'Не установлен',

	'js_mail_wrong_pass'			=> 'Некорректный пароль!',
	'js_mail_client_prog'			=> 'Требуется установить почтовые клиенты',
	'js_mail_progress'			=> 'Выполняется...',
	'js_mail_process_on'			=> 'Включен',
	'js_mail_process_off'			=> 'Отключен',
	'js_mail_email_error'			=> 'Введите правильный почтовый ящик',
	'js_mail_passwd_error_len'		=> 'Пароль не может быть пустым',
	'js_mail_err_source_domain'		=> 'Введите верный начальный домен',
	'js_mail_err_target_domain'		=> 'Введите верный домен назначения',
	'js_mail_err_source_email'		=> 'Введите верный начальный почтовый ящик',
	'js_mail_err_target_email'		=> 'Введите верный почтовый ящик назначения',
	'js_mail_err_already'			=> 'Домен/почтовый ящик уже есть в списке',
	'js_mail_jmp_to'			=> 'Переслать на ',
	'mailclient_del_process' => 'Удаляется...',

	'mailclient_emailexist'			=> 'Почтовый ящик уже существует',
	'mailclient_invalid_comand'			=> 'Не правильная команда',	
	'mailclient_status'			=> 'Статус',		
	'mailclient_command_succsecfully'			=> 'Команда выполнена',

	"mailclient_addmail_failed_overlimit"=>"Превышен лимит почтовых аккаунтов. Максильное количество почтовых аккаунтов ",
	"mailclient_addmail_failed_quotaformat"=>"Неверный формат квоты.",
	"mailclient_spf_addemail"=>"SPF",
	"mailclient_dkim_addemail"=>"DKIM",
	"mailclient_dmarc_addemail"=>"DMARC",
  	"mailclient_new_quota"=>"Новая квота, мб",
	"mailclient_new_pass"=>"Новый пароль",
	"mailclient_change_quota"=>"Сменить квоту",
	"mailclient_change_pass"=>"Сменить пароль",
    "mailclient_change_pass_quota"=>"Сменить пароль, квоту",
  	"mailclient_change_auto_text"=>"Сменить текст",
  	"mailclient_change"=>"Сохранить",
	"mailclient_successfully_done"=>"Успешно выполнено",
	"mailclient_no_rights"=>"У Вас недостаточно прав для выполнения данной операции",
	"mailclient_empty_field"=>"Поле должно быть заполнено",

	"mailclient_usernothaveemailbox"=>"Пользователь не имеет почтовых ящиков или нет соответствий фильтру",
	"mailclient_usernothaveredirect"=>"Пользователь не добавил перенаправлений",
	"mailclient_user_nothavesites"=>"Пользователь не имеет добавленных сайтов",

	"mailclient_autoresponder"=>"Включить автоответчик",
	"mailclient_text_autoresponder"=>"Наберите текст для автоответчика",
	"mailclient_error_number"=>"Не правильный формат значения",
	"mailclient_not_text"=>"Текст сообщения должен быть заполнен",
	"mailclient_autoresponder_check"=>"Автоответчик",
	"mailclient_autoresponder_text"=>"Текст сообщения",
	"mailclient_data_not_corected"=>"Некоректные данные",
	"mailclient_change_text"=>"Изменить текст",
	"mailclient_change_text_check"=>"Потвердить",
	"mailclient_change_succecfully"=>"Данные успешно изменены",
	"mailclient_status"=>"Включено",
	"mailclient_saving"=>"Идет сохранение",
	"mailclient_loging"=>"Почтовые логи",
	"mailclient_load_statistic"=>"Загрузить статистику",
	"mailclient_not_email"=>"У пользователя нет почтовых ящиков",
	"mailclient_not_email_statistic"=>"К сожалению, сегодня еще статистики нет.",
	"mailclient_statistic"=>"Статистика получения и оправки писем",
	"mailclient_filter"=>"Фильтры электронной почты",
	"mailclient_email_filter"=>"Выберите почтовый ящик",
	"mailclient_filter_name"=>"Название фильтра",
    "mailclient_filter_condition"=>"Условие фильтра",
    "mailclient_filter_act"=>"Действие фильтра",
	"mailclient_filter_create"=>"Создать фильтр",
	"mailclient_filter_ot"=>"От.",
	"mailclient_filter_tema"=>"Тема",
	"mailclient_filter_do"=>"До.",
	"mailclient_filter_reply"=>"Ответить",
	"mailclient_filter_text"=>"Текст",
	"mailclient_filter_any_title"=>"Любой заголовок",
	"mailclient_filter_not_previously_delivered"=>"Ранее не доставлялось",
	"mailclient_filter_error_message"=>"Является сообщением об ошибке",
	"mailclient_filter_ind_list"=>"Индетификатор списка",
	"mailclient_filter_state_spam"=>"Состояние нежелательной почты",
	"mailclient_filter_junk_mail"=>"Панель для нежелательной почты",
	"mailclient_filter_spam_evaluation"=>"Оценка нежелательной почты",
	"mailclient_filter_contains"=>"Содержит",
	"mailclient_filter_regex"=>"Соответствует regex",
	"mailclient_filter_not_contains"=>"Не содержит",
	"mailclient_filter_equal"=>"Равняется",
	"mailclient_filter_starts"=>"Начинается с",
	"mailclient_filter_end"=>"Завершается на",	
	"mailclient_filter_not_starts"=>"Не начинается",
	"mailclient_filter_not_end"=>"Не заканчивается на",	
	"mailclient_filter_not_equal"=>"Не соответствует",
	
	"mailclient_filter_dell_message"=>"Удалить сообщение",	
	"mailclient_filter_redirect"=>"Перенаправить",
	"mailclient_filter_error_mes"=>"Ошибка с сообщением",	
	"mailclient_filter_leave_processing_rules"=>"Оставить правила обработки",	
	"mailclient_filter_deliver_folder"=>"Доставить в папку",
	"mailclient_not_user"=>"Пользователь не соответствует",	
	"mailclient_name_filter"=>"Не верное название фильтра минимум 5 символов (a-z0-9_)",
	"mailclient_not_filter_1"=>"Не соответствие фильтру 1",	
	"mailclient_not_filter_2"=>"Не соответствие фильтру 2",
	"mailclient_not_action"=>"Не существующее действие",
	"mailclient_not_text_filter"=>"Текстовый фильтр не соответствует",	
	"mailclient_not_email_reg"=>"Email не соответствует регулярному выражению",
	"mailclient_folder"=>"test/spam — папка и имя файла в директории email",
	"mailclient_error_folder"=>"Директория не соответствует регулярному выражению",
	"mailclient_email_redirect"=>"Email для редиректа",
	"mailclient_not_filter_include"=>"Установленных фильтров нет",
	"mailclient_n_filter"=>"Название фильтра",
    "mailclient_filter_header_all" => "Все фильтры",
    "mailclient_filter_header_add" => "Добавить фильтр",


	"mailclient_action"=>"Действие",
	"mailclient_description_text"=>"*Внимание! При составлении фильтра на текст учитывайте то что проверяется полностью все заголовки и тело письма.",
	"mailclient_description_filter"=>"Описание",
	"mailclient_description_tema"=>"*Внимание! Некоторые почтовые серверы кодируют тему письма в зависимости от длины символов. Учитывайте это при составлении фильтров.",
	"mailclient_description_text2"=>"**Некоторые почтовые серверы кодируют тело письма Content-Transfer-Encoding: base64. В таких случаях пользовательский фильтр бессмысленный.",
	"mailclient_description2"=>"*Фильтр с одинаковым названием будет перезатерт созданным фильтром.",
	"mailclient_description3"=>"**Очередность фильтров имеет значение. Фильтры выполняются сверху вниз (После фильтра «Удалить сообщение» дальнейшие фильтры с одним и тем же условием работать не будут).",
	"mailclient_mailing"=>"Почтовая рассылка",
	
	
	"mailclient_not_group"=>"Нет списков подписчиков",
	"mailclient_add_group"=>"Добавить список подписчиков",
	"mailclient_group_mailing_name"=>"Название списка",	
	"mailclient_group_mailing_description"=>"Описание списка",
	"mailclient_num_piople"=>"Количество людей",
	"mailclient_view_list"=>"Управление списком",
	"mailclient_view"=>"Посмотреть",		
	"mailclient_remove_group"=>"Удалить список",
	"mailclient_add_in_list"=>"Добавить в список",	
	"mailclient_error_group"=>"Название списка не соответствует регулярному выражению",
	"mailclient_group_file_suceesuele"=>"Список подписчиков успешно создан.",
	"mailclient_error_group_file"=>"Название списка уже существует",
	"mailclient_name_user"=>"Имя подписчика",
	"mailclient_name_user2"=>"Фамилия подписчика",
	"mailclient_phone"=>"Телефон",
	"mailclient_address"=>"Адрес",
	"mailclient_not_data"=>"Не относится к данным",	
	"mailclient_name_user_error"=>"Имя или фамилия подписчика не соответствует регулярному выражению",
	"mailclient_phone_error"=>"Номер телефона не соответствует регулярному выражению",	
	"mailclient_address_error"=>"Адресс не соответствует регулярному выражению",		
	"mailclient_not_all_data"=>"Нет всех значений",	
	"mailclient_group_mailing_none"=>"Список подписчиков пуст",
	"mailclient_field"=>"Колонка",
	"mailclient_not_email_parser"=>"К сожаленью парсер не нашел email подписчиков",
	"mailclient_not_file_prepere"=>"Отсутствует файл обработки массива",
	"mailclient_num_equal"=>"Количество совпадений - ",
	"mailclient_num_black_list"=>"Подписчиков в черных списках - ",
	"mailclient_num_error"=>"Количество ошибок - ",	
	"mailclient_add_users"=>"Добавлено подписчиков - ",
	"mailclient_error_file_data"=>"Запрещенный тип данных - ",
	"mailclient_error_file_save"=>"Не удалось сохранить файл",
	"mailclient_parse_email"=>"Такой email существует",
	"mailclient_succes_remove"=>"Список подписчиков успешно удален.",
	"mailclient_subscription"=>"Подписан",
	"mailclient_subscription_send"=>"Состояние",
	"mailclient_subscription_data"=>"Дата подписки",
	"mailclient_not_number"=>"не число",
	"mailclient_not_file"=>"нет файла для редактирования",
	//"mailclient_group_time_start"=>"Время запуска 00:00",
	//"mailclient_group_time_start2"=>"Время запуска",		
	//"mailclient_error_description"=>"Описание не соответствует регулярному выражению",
	//"mailclient_error_time_start"=>"Время запуска не соответствует регулярному выражению",
	//"mailclient_start"=>"Запуск",
	//"mailclient_start_mail"=>"Запуск рассылки",
	
	"mailclient_save_changes"=>"Сохранить изменения",
	"mailclient_add_user"=>"Добавить подписчика",
	"mailclient_email_user"=>"Email подписчика",

    "mailclient_add_user_header"=>"Добавить подписчиков",
    "mailclient_add_user_process_header"=>"Добавление подписчиков",
	"mailclient_error_active"=>"Действие не удовлетворяет регулярному выражению",
	//"mailclient_error_active"=>"Email должно быть заполненым",
	"mailclient_succesfulle_add_user"=>"Подписчик успешно добавлен.",
	"mailclient_error_add_user"=>"Ошибка в сохранении подписчика. Возможно отсутствует список.",


	"mailclient_remove_succesfully"=>"Подписчик успешно удален.",
	"mailclient_remove_send"=>"Подписчик отписан от рассылки",
	"mailclient_add_send"=>"Подписчик подписан на рассылку",
	"mailclient_add_black_list"=>"Черный список",
	"mailclient_add_black_list_succ"=>" добавлен в черный список",	
	"mailclient_add_black_list_succ_user"=>"Подписчик находится в черных списках",
	"mailclient_list_send"=>"Списки рассылок",	
	"mailclient_mail"=>"Письма",

	"mailclient_text_1"=>"Значения которые при отправке письма заменяются",
	"mailclient_text_name"=>'{$name} - имя подписчика',
	"mailclient_text_email"=>'{$email} - email подписчика',
	"mailclient_text_last_name"=>'{$lastname} - фамилия подписчика',
	"mailclient_text_phone"=>'{$phone} - телефон подписчика',
	"mailclient_text_address"=>'{$address} - адрес подписчика',
	"mailclient_user_variable"=>' - пользовательская переменная',
	"mailclient_text_unsubscribe"=>'Отписаться',	
	"mailclient_message_mailing"=>'Письма рассылки',
	"mailclient_message_not"=>'У вас нет писем',
	"mailclient_message_thema"=>'Тема письма',
    "mailclient_message_body"=>'Тело письма',
	"mailclient_message_from"=>'От кого',
	"mailclient_error_thema"=>'Тема письма не соответствует регулярному выражению',	
	"mailclient_message_list"=>'Список писем',
	"mailclient_add_message"=>'Добавить письмо',
	"mailclient_error_id"=>'id сообщения не соответствует регулярному выражению.',
	"mailclient_piople"=>'человек',
	"mailclient_add_new_message"=>'Добавление нового сообщения',
	"mailclient_edit_message"=>'Редактирование сообщения',
	"mailclient_create_mailling"=>'Создать рассылку',
	"mailclient_select_mail"=>'Выберите письмо для рассылки',
	"mailclient_select_group_mailing"=>'Выберите список рассылки',
	"mailclient_email_output"=>'Выберите список рассылки',
	"mailclient_test_mail"=>'Тестовое письмо',
	"mailclient_email_recipient"=>'Email получателя',
	"mailclient_create_mailling_cron"=>'Создать рассылку',
	"mailclient_send_now"=>'Отправить сейчас',
	"mailclient_send_succec"=>'Письмо успешно отправлено',
	"mailclient_add_mailing_send"=>'Рассылка писем добавлена в задание',	
	"mailclient_send_error"=>'Ошибка отправки письма',
	"mailclient_send_mailing"=>'Отправленные рассылки',
	"mailclient_send_data"=>'Дата отправления',
    "mailclient_letter_list"=>'Письмо, список',
    "mailclient_mailing_id"=>'ID рассылки',
    "mailclient_send_status"=>'Статус',
	"mailclient_num_piople_mailing"=>'Человек в рассылке',
	"mailclient_send_email"=>'Всего отправлено писем',
    "mailclient_open_email"=>'Открыто',
    "mailclient_delivered_email"=>'Доставлено',
	"mailclient_not_send_email"=>'Заблокировано',
	"mailclient_date"=>'Дата',
	"mailclient_send_later"=>'Отправить позже',
	"mailclient_send"=>'Отправить',	
	"mailclient_succec_remove"=>'Успешно удалено',
	"mailclient_send_ok"=>'Отправлен',	
	"mailclient_send_not"=>'Блокирован',
	"mailclient_send_expectation"=>'Ожидание отправки',
	"mailclient_not_message"=>'Нет сообщений для рассылки',
	"mailclient_not_list_group"=>'Нет списков подписчиков',
	"mailclient_data_time"=>'Дата и время на сервере',	
	"mailclient_not_ecvaldata_time"=>'Указанное время меньше чем время на сервере.',
	"mailclient_autocorrect"=>'Автозамена переменных сработает только если email существует в выбранном списке получателей.',
	"mailclient_attentconfonseroff"=>'Внимание! Сервис не запущен, но его секция включена в конфигурацию - это может привести к некорректной работе почты. Запустите сервис или уберите его из конфигурации кнопкой ниже',
	"mailclient_used_total_message"=>'Использовано МБ / Всего МБ / Сообщений',
	"mailclient_overquota"=>'Превышена квота',
    "mailclient_dbconnfailedbrainysql"=>'Ошибка подключения к серверу баз данных MySql',
    "mailclient_no_domains"=>'Нет добавленных доменов',
    "mailclient_please_wait"=>'Пожалуйста, подождите.',
    "mailclient_view_list_header"=>'Просмотр списка',
    "mailclient_list_header"=>'Списки подписчиков',


    "mailclient_add_single_user"=>'Добавить одного подписчика',
    "mailclient_file_import"=>'Импортировать из файла',
    "mailclient_copy_insert"=>'Копировать/вставить',

    "mailclient_add_user_text_line1"=>'Каждый подписчик с новой строки.',
    "mailclient_add_user_text_line2"=>'В качестве разделителей данных одного подписчика используется любой символ из |,;:',
    "mailclient_add_user_text_line3"=>'Допускаются файлы .txt, .csv.',
    "mailclient_add_user_text_line4"=>'Для нормальной работы с кириллицей сохраняйте файл в кодировке utf8.',
    "mailclient_add_user_text_placeholder"=>'ivanivanov@gmail.com;Иван;Иванов;Другие данные',

    "mailclient_mailing_header" => 'Рассылки',
    "mailclient_mailing_details_header" => 'Детали рассылки',
    "mailclient_links_header" => 'Переходы по ссылкам',
    "mailclient_create_mailing_header" => 'Создать рассылку',
    "mailclient_mailing_date_header" => 'Выберите дату и время',
    "mailclient_create_message" => 'Создать письмо',
    "mailclient_create_list_mailing" => 'Создать список рассылки',
    "mailclient_open" => 'Открыто',

    'mailclient_all_links' => 'Все ссылки',
    'mailclient_links' => 'Ссылки',
    'mailclient_coversions' => 'Переходы',

    'mailclient_each_recipient_header' => 'Подробнее по каждому получателю',

    'mailclient_authmailok' => 'Успешный вход',
    'mailclient_customdomain' => 'Произвольный домен',
    'mailclient_customdomain_hint' => 'Введите домен',
    'mailclient_customdomain_failedformat' => 'Неверный формат произвольного домена.',

    'mailclient_clamav_autostart' => 'Автозагрузка',
    'mailclient_confirm_remove_email' => 'Подтвердите удаление почтового аккаунта',
    'mailclient_add_email' => 'Добавьте почтовый ящик',

    'mailclient_qualify_domain_title' => 'Настройка исходящей почты',
    'mailclient_qualify_domain_hint' => 'Для отправки писем с подписью DKIM, SPF, используя функцию mail без заголовков, нужно задать домен в qualify_domain, который имеет DKIM, SPF запись',
    'mailclient_qualify_label' => 'Значение qualify_domain',
    'mailclient_qualifyCantSetQualifyNotJail' => 'Невозможно сменить qualify_domain. Пользователь не в jail окружении. Пожалуйста, обратитесь к администратору.' ,
    'mailclient_not_quality_domain' => 'В файле конфигурации отсутствует qualify_domain',
    'mailclient_qualify_save_failed' => 'Неверный формат домена.',
    'mailclient_qualify_save_ok' => 'Сохранено успешно.',
    'mailclient_error_add_root' => 'Пользователю запрещено добавить данный почтовый ящик',
    'mailclient_not_dirctory_email' => 'Нет директории почтового ящика',

    'mailclientmailTableNoDom' => 'Пользователь не имеет добавленных доменов',
    'mailclientmailTableTitle' => 'Маршрутизация почты',
    'mailclientmailTableTh1' => 'Домен',
    'mailclientmailTableTh2' => 'Маршрутизация',
    'mailclientmailRouteUpdateOk' => 'Успешно обновлено',
    'mailclientmailRouteSelDom' => 'Выберите домен',
    'mailclientmailRouteSelDomCur' => 'Текущий домен',
    'mailclientmailRouteLocal' => 'Локальный почтовый обменник',
    'mailclientmailRouteRemote' => 'Удаленный почтовый обменник',
    'mailclientmailOtherMx' => 'Использование сторонних MX записей',
    'mailclientmailOtherMxTypeHint'=>'<b>Локальный почтовый обменник.</b> Система будет принимать почту для этого домена. Система будет доставлять почту в локальный почтовый ящик. <br/><b>Удаленный почтовый обменник.</b> Система не будет принимать почту для этого домена. Система всегда будет отправлять все письма этого домена на почтовый сервер с меньшим числом MX.',
    'mailclient_uppercase' => 'Локальную часть почтового аккаунта, используйте в нижнем регистре.',
    'mailclient_empty_mail_account' => 'Не добавлен почтовый ящик, в почтовых аккаунтах',
    'mailclient_name_from' => 'Имя отправителя',
    'mailclient_error_name_from' => 'Ошибка имени отправителя',
	'mailclient_empty_mail_service' => 'Не установлены почтовые программы (Roundcube,SquirrelMail)',
    'mailclient_searchmail'=>'Поиск почтового ящика',


);
