<?php

$lang = array (
	'sendserver' => '发送邮件服务器',
	'receiveserver' => '接收邮件服务器',
	'customazing' => '配置',
	'version' => '版本',
	'installed' => '已安装',
	'install' => '安装',
	'delete' => '删除',
	'reinstall' => '重新安装',
	'stop' => '停止',
	'start' => '启动',
	'restart' => '重新启动',
	'send' => '发送',
'mailserver_incl' => '启用',
'mailserver_off' => '禁用',
'mailserver_queue_close' => '关闭',
'Mailserver_queue_delete' => '全部删除',
'mailserver_queue_delete_force' => '强行清空队列',
'mailserver_queue_delete_frozen' => '删除冻结',
'mailserver_queue_delete_ok' => '队列已成功清除',
'mailserver_queue_delete_progress' =>' 正在清除队列。请等一下',
'mailserver_queue_count_mess' => '队列中的邮件数：',
'mailserver_queue_mess_resend' => '重新发送',

'mailserver_reject_remote_mail' => '拒绝发送到服务器的邮件',
'mailserver_reject_spf' => '在 SPF 失败时拒绝邮件',
'mailserver_reject_dmarc' => '在 DMARC 失败时拒绝邮件',
'mailserver_reject_bounce' => '超过配额时退回用户的邮件',
'mailserver_reject_smtp_sender' => '设置 SMTP 检查发件人标题',

'Msg_mail_no_admin' => '不太正确',
'msg_mail_remove_all' => '删除任何包',
'msg_mail_progress_txt' => '进行中...',
'msg_mail_module_on' => '启用',
'Msg_mail_module_off' => '禁用',

'mailserver_custom_save' => '黑名单已更新',
'mailserver_list_msg' => '邮件队列列表',
'mailserver_not_list_msg' => '邮件队列列表为空。',
'Mailserver_count_msg' => '消息数',
'mailserver_not_id_msg' => '缺少邮件 ID',
'mailserver_not_server_send' => '发送信件的服务器缺失或指定不正确',
'mailserver_request_succecf' => '请求已完成',
'mailserver_not_dell_force' => '邮件服务器不支持强制删除',
'mailserver_not_dell_frozen' => '邮件服务器不支持删除冻结的邮件',
'mailserver_limit_send' => '每小时发送电子邮件的限制：',
'mailserver_save' => '保存',
'mailserver_list_black' => '管理自定义 RBL（黑名单）',
'Mailserver_start_ok' => '启动',
'Mailserver_stop_ok' => '停止',
'mailserver_start_failed' => '启动失败，错误',
'Mailserver_no_queue' => '队列中没有消息',

    'mailserver_qualify_domain_title' => '设置qualify_domain',
    'mailserver_qualify_domain_hint' => '要使用没有标题的邮件功能发送带有 DKIM、SPF 签名的信件，您需要在qualify_domain 中设置一个具有 DKIM 或 SPF 记录的域',
    'mailserver_qualify_label' => 'qualify_domain 值',
    'Mailserver_qualify_save' => '保存',
    'mailserver_qualify_save_failed' => '域格式无效。',
    'mailserver_qualify_save_ok' => '保存成功。服务已经重启。',
    'mailserver_max_size_out_message' => '最大邮件大小 Mb',
    'Mailserver_error_format_number' => '错误格式。必须有数字',
    'mailserver_success' => '成功完成',
    'mailserver_not_quality_domain' => '配置文件中缺少qualify_domain',
    'mailserver_mailorleaveemptydmarc' => '电子邮件地址或留空',
    'mailserver_queuetitle' => '队列',
    'Mailserver_select_user' => '请选择一个用户',
    'mailserver_empty_named_spf' => '要使 cpf 记录正常工作，必须安装 bind 并且必须为您的站点设置 dns 区域。',
    'mailserver_empty_named_dmarc' => '为了使 dmarc 记录正常工作，必须安装 bind，并且必须为您的站点设置 dns 区域。',
    'mailserver_empty_install_exim' => 'Exim 未安装，所做的更改不会被保存。',

);
