<?php

$lang = array (
	'mailserver' => 'Почтовый сервер',
	'sendserver' => 'Сервер исходящей почты',
	'receiveserver' => 'Сервер входящей почты',
	'customazing' => 'Настройка',
	'version' => 'версия',
	'installed' => 'Установлено',
	'install' => 'Установить',
	'delete' => 'Удалить',
	'reinstall' => 'Переустановить',
	'stop' => 'Остановить',
	'start' => 'Запустить',
	'restart' => 'Перезапустить',
	'send' => 'Отправить',
	'mailserver_incl' => 'Включить',	
	'mailserver_off' => 'Выключить',	
	'mailserver_queue_close' => 'Закрыть',
	'mailserver_queue_delete' => 'Очистить очередь',
	'mailserver_queue_delete_force' => 'Очистить очередь принудительно',
	'mailserver_queue_delete_frozen' => 'Удалить замороженные',
	'mailserver_queue_delete_ok' => 'Очередь очищена успешно',
	'mailserver_queue_delete_progress' => 'Очередь очищается. Пожалуйста подождите',
	'mailserver_queue_count_mess' => 'Количество сообщений в очереди: ',
	'mailserver_queue_mess_resend' => 'Переотправить',
	
	'mailserver_reject_remote_mail' => 'Отклонять почту направленную на сервер',
	'mailserver_reject_spf' => 'Отклонять почту при неудаче SPF',
	'mailserver_reject_dmarc' => 'Отклонять почту при неудаче DMARC',
	'mailserver_reject_bounce' => 'Отклонять почту пользователей при превышении квоты',
	'mailserver_reject_smtp_sender' => 'Установить SMTP проверку заголовков отправителя',
	
	'msg_mail_no_admin' => 'Не достаточно прав',
	'msg_mail_remove_all' => 'Удалить любые связки',
	'msg_mail_progress_txt' => 'Выполняется...',
	'msg_mail_module_on' => 'Включен',
	'msg_mail_module_off' => 'Отключен',
	
	'mailserver_custom_save' => 'Список блеклистов обновлен',
	'mailserver_list_msg' => 'Список почтовой очереди',	
	'mailserver_not_list_msg' => 'Список почтовой очереди пуст.',
	'mailserver_count_msg' => 'Количество сообщений',
	'mailserver_not_id_msg' => 'Отсутствует id письма',
	'mailserver_not_server_send' => 'Отсутствует или не правильно указан сервер отправки писем',
	'mailserver_request_succecf' => 'Запрос выполнен',
	'mailserver_not_dell_force' => 'Почтовый сервер не поддерживает принудительное удаление',
	'mailserver_not_dell_frozen' => 'Почтовый сервер не поддерживает удаление замороженных писем',
	'mailserver_limit_send' => 'Ограничение на отправку писем в час:',	
	'mailserver_save' => 'Сохранить',
	'mailserver_list_black' => 'Manage Custom RBLs (список блеклистов)',
	'mailserver_start_ok' => 'Запущен',
	'mailserver_stop_ok' => 'Остановлен',
	'mailserver_start_failed' => 'Запуск завершился с ошибкой',
	'mailserver_no_queue' => 'Нет сообщений в очереди',

    'mailserver_qualify_domain_title' => 'Настройка qualify_domain',
    'mailserver_qualify_domain_hint' => 'Для отправки писем с подписью DKIM, SPF, используя функцию mail без заголовков, нужно задать домен в qualify_domain, который имеет DKIM или SPF запись',
    'mailserver_qualify_label' => 'Значение qualify_domain',
    'mailserver_qualify_save' => 'Сохранить',
    'mailserver_qualify_save_failed' => 'Неверный формат домена.',
    'mailserver_qualify_save_ok' => 'Сохранено успешно. Сервис перезапущен.',
    'mailserver_max_size_out_message' => 'Максимальный размер письма Mb',
    'mailserver_error_format_number' => 'Ошибки формата. Должны быть цифры',
    'mailserver_success' => 'Успешно выполено',
    'mailserver_not_quality_domain' => 'В файле конфигурации отсутствует qualify_domain',
    'mailserver_mailorleaveemptydmarc' => 'Email адрес или оставьте пустым',
    'mailserver_queuetitle'=>'Очередь',
    'mailserver_select_user'=>'Пожалуйста, выберите пользователя',
    'mailserver_empty_named_spf'=>'Для правильной работы cpf записи, должен быть установлен bind, и поднята днс зона для вашего сайта.',
    'mailserver_empty_named_dmarc'=>'Для правильной работы dmarc записи, должен быть установлен bind, и поднята днс зона для вашего сайта.',
    'mailserver_empty_install_exim'=>'Не установлен exim, внесенные изменения не будут сохранены.',	

);
