<?php

$lang = array(
    'msg_js_mysql_status'	=> 'Не работает',
    'msg_mysql_error_num_db'	=> 'Ошибка. Вы достигли максимального количества баз.',
    'msg_mysql_ok_priv'		=> 'Привелегии применены.',
    'msg_mysql_err_check_db'		=> 'Ошибка проверки DB.',
    'msg_mysql_err_check_user'		=> 'Ошибка проверки пользователя.',
    'msg_mysql_ok_user_del'		=> 'Пользователь успешно удален.',
    'msg_mysql_err_user_del'		=> 'Некорректное имя пользователя.',
    'msg_mysql_ok_db_del'		=> 'База успешно удалена.',
    'msg_mysql_err_db_del'		=> 'Ошибка удаления базы.',

    'tpl_remove_delete'		=> 'Удалить',
    'tpl_remove_configure'	=> 'Настроить',
    'tpl_main_menu_mysql'	=> 'MySql',
    'tpl_main_menu_process'	=> 'MySql processlist',
    'tpl_mysql_nomysql'		=> 'Не установлено',
    'tpl_mysql_nomyadmin'	=> 'Не установлено',
    'tpl_mysql_more'		=> 'Подробнее',
    'tpl_mysql_hidden'		=> 'Скрыть',
    'tpl_mysql_status_info'	=> 'MySql статус: ',
    'tpl_mysql_cnf_save'	=> 'Сохранить',
    'tpl_mysql_install_phpadmin'	=> 'Установить phpMyAdmin',
    'tpl_mysql_phpadmin_status'	=> 'Phpmyadmin статус',
    'tpl_mysql_myadmin_install'	=> 'Установить',
    'tpl_mysql_nodb'		=> 'Не добавлено ни одной базы данных',
    'tpl_mysql_add_user'	=> 'Добавить пользователя',
    'tpl_mysql_add_db'		=> 'Добавить базу данных',
    'tpl_mysql_jmp_promptly'		=> 'Перейти в phpMyAdmin сразу',
    'tpl_mysql_jmp_pass'		=> 'Перейти в phpMyAdmin с паролем',
    'tpl_mysql_jmp_only'		=> 'Перейти в phpMyAdmin',
    'tpl_mysql_select_all'		=> 'Отметить всё',
    'tpl_mysql_external_access'		=> 'Открыть внешний доступ',
    'tpl_mysql_external_access_all'	=> 'Открыть внешний доступ любому IP',
    'tpl_mysql_no_user'			=> 'Не добавлено ни одного пользователя',

    'tpl_mysql_no_user_select' => 'Нет пользователей',
    'tpl_mysql_no_base_select' => 'Нет баз данных',

    'tpl_mysql_hide'			=> 'Скрыть',
    'tpl_mysql_name'			=> 'MySQL',
    'tpl_mysql_version'			=> 'Версия MySql:',
    'tpl_mysql_reinstall'		=> 'Переустановить',
    'tpl_mysql_for_expert'		=> 'Для экспертов',
    'tpl_mysql_for_user'		=> 'Для пользователей',
    'tpl_mysql_passwd_rename'		=> 'Идет процесс смены пароля. Подождите пожалуйста.',
    'tpl_mysql_update'			=> 'Обновление',
    'tpl_mysql_update_force'		=> 'Форсированое обновление',

    'js_mysql_delete'		=> 'Выполняем удаление... ',
    'js_mysql_install'		=> 'Выполняем установку... ',
    'js_mysql_passwd_file'	=> 'Пожалуйста заполните поля пароля',
    'js_mysql_install_pass'	=> 'Установка завершена',
    'js_mysql_remove_pass'	=> 'Удаление завершено',
    'js_mysql_no_install'	=> 'Не установлено',
    'js_mysql_no_error'		=> 'Без ошибок',
    'js_mysql_error'		=> 'Ошибка:',
    'js_mysql_process_done'	=> 'Процесс запущен подождите...',
    'js_mysql_check_msg'	=> 'Идет процесс смены пароля. Не трогайте mysql сервер',
    'js_mysql_server_notwork'	=> 'Mysql сервер не работает. Пожалуйста обратитесь к администратору',
    'js_mysql_db_noconnect'	=> 'Ошибка подсоединения к базе. Пожалуйста обратитесь к администратору',
    'js_mysql_db_nodata'	=> 'Ошибка в передаче данных. Попробуйте позже.',
    'js_mysql_db_nodata_nopass'	=> 'Новый пароль не может быть пустым. Пожалуйста, введите новый пароль.',
    'js_mysql_passwd_root'	=> 'Пароль mysql root был изменен',
    'js_mysql_change_config'	=> 'Конфигурация mysql сервера изменена',
    'js_mysql_restore_config'	=> 'Востановлена конфигурация по умолчанию',
    'mysql_show_all_users'	=> 'Вывод всех пользователей',
    'mysql_show_error_users'	=> 'Массив пользователей пустой.',
    'mysql_show_error_root'	=> 'У вас не достаточно прав. Уберите user_edit',
    'mysql_show_all_db'	=> 'Вывод баз пользователя',
    'mysql_show_error_db'	=> 'Массив баз пустой.',
    'mysql_name_user_db_error'	=> 'Имя пользователя пустое.',	
    'mysql_pwd_user_db_error'	=> 'Пароль для пользователя базы пустой.',
    'mysql_not_name_db'	=> 'Название базы данных должно быть заполнено.',	
    'mysql_add_user_ok'	=> 'Пользователь добавлен.',
    'mysql_not_work_mysql'	=> 'Не работает mysql',
    'mysql_not_root_password'	=> 'Неверный Root пароль mysql. Пожалуйста, свяжитесь с администратором',
    'mysql_user_exist'	=> 'Пользователь существует',		
    'mysql_add_db_ok'	=> 'База данных создана',
    'mysql_add_db_exists'	=> 'База данных существует',	
    'mysql_list_privilegies'	=> 'Список привилегий. ',	
    'mysql_not_privilegies'	=> 'У пользователя нет привилегий. Список привилегий пуст.',
    'mysql_not_write_privilegies'	=> 'Неправильно написана привилегия',
    'mysql_not_ip_parce'	=> 'Неправильное значение ip адреса.',
    'mysql_not_edit'	=> 'Попытка редактирования не своих данных',

    'mysql_adddb_wrongformat'	=> 'Пожалуйста используйте только буквы a-z и цифры 0-9.',

    'mysql_adddb_emptypass'	=> 'Пожалуйста заполните пароль.',

    'mysql_adddb_failed_overlimit'	=> 'Превышен лимит количества баз данных. Максимальное количество баз данных ',

    'mysql_manage_db' => 'База данных MySQL',

    'mysql_select_usermain' => 'Выберите пользователя',
    'mysql_listdb_user' => 'Базы данных',
    'mysql_loaddata_pleasewait' => 'Пожалуйста, подождите',
    'mysql_user_notselect' => 'Не один пользователь не добавлен или не выбран',

    'mysql_run_isok' => 'Работает',
    'mysql_run_isfailed' => 'Остановлен',

    'mysql_intalling' => 'Идет установка',	
    'mysql_intalling_successfully' => 'Установка завершена',

    'mysql_phpmyadmin_ver' => 'Версия',
    'mysql_phpmyadmin_demo' => '!!! PHPMYADMIN не доступен в демо версии.',
    'mysql_phpmyadmin_demo_2' => 'в обычной версии он будет доступен.',
    'mysql_message_remove_mysql' => 'При удалении mysql почтовые сервисы и почта будут недоступны.',
    'mysql_message_remove_mysql_2' => 'Во время установки или переустановки mysql почтовые сервисы будут временно отключены.',
    'mysql_message_stop_mysql' => 'При остановке mysql почтовые сервисы будут будут недоступны.',
    'mysql_exit' => 'Отмена',	
    'mysql_continue' => 'Продолжить',
    'mysql_change_password' => 'Изменить пароль',	
    'mysql_short_password' => 'Пароль меньше 6 символов',		
    'mysql_succecfully' => 'Выполнено',			
    'mysql_disabled_mysqld' => 'Это действие при выключенном mysqld сервисе невозможно',			
    'mysql_root_password' => 'Root пароль: ',
    'mysql_root_password_show' => 'Показать',
    'mysql_root_password_hide' => 'Скрыть',
    'mysql_confirm_remove_user' => 'Подтвердите удаление пользователя ',
    'mysql_confirm_remove_db' => 'Подтвердите удаление базы данных ',
    'mysql_control_db' => 'Управление сервером БД',
    'mysql_version' => 'Версия БД:',
    'mysql_control' => 'Управление сервером',
    'mysql_status' => 'Статус БД:',
    'mysql_vers' => 'Версия',
    'mysql_controm_phpmyadmin' => 'Управление phpMyAdmin',
    'mysql_welcome' => 'Добро пожаловать в',
    'mysql_autorisation' => 'Авторизация',
    'mysql_user' => 'Пользователь:',
    'mysql_pass' => 'Пароль:',
    'mysql_input' => 'Войти',
    'mysql_sintax_error' => 'Синтаксическая ошибка my.cnf',
    'mysqlPhpMyAdminGetVersion' => 'Проверить обновление',
    'mysqlPhpMyAdminAvailNewVersion' => 'Доступна новая версия ',
    'mysqlPhpMyAdminAvailNewVersionNot' => 'Уже установлена самая последняя версия phpMyAdmin',
    'mysqlPhpMyAdminAvailNewVersionNotIns' => 'Сначала нужно установить',
    'mysqlPhpMyAdminNewVersionInstall' => 'Обновить',
    'mysqlPhpMyAdminUpdateOk' => 'Обновлено успешно ',
    'mysql_download_dump' => 'Загрузить дамп.',
    'mysql_download_dump_error' => 'Ошибка загрузки файла',
    'mysql_download_dump_error_type' => 'Ошибка типа файлов. Допустимые типы - sql',
    'mysql_download_dump_error_connect' => 'Ошибка соединения с базой данных',
    'mysql_download_success' => 'Успешно выполнено',
    'mysql_download_table_already_exists' => 'В базе данных есть таблицы из дампа.',
    'mysql_download_not_db_user' => 'База не пренадлежит пользователю.',
    'mysql_empty_remote_ip' => 'Для открытия удаленного доступа, должен быть добавлен внешний ip',
    'mysql_installonpostg' => 'Установить/включить Postgresql →',
);

?>