<?php

$lang = array(
    'packet_manager'	=> 'Пакетный менеджер',
    'packet_manager_title2' => 'Менеджер приложений',
    'msg_package_status'	=> 'Не работает',
    'msg_package_err_login'	=> 'У вас недостаточно прав для захода на данную страницу',

    'tpl_package_del'			=> 'Удалить',
    'tpl_package_save'			=> 'Сохранить',
    'tpl_package_installed'		=> 'Установлен',
    'tpl_package_working'		=> 'Работает',
    'tpl_package_log_show'		=> 'Смотреть лог последней установки/удаления',
    'tpl_package_go_process'		=> 'Идет процесс... ',
    'tpl_package_install'		=> 'Установить',
    'tpl_package_delete'		=> 'Удалить',
    'tpl_package_control'		=> 'Управление',
    'tpl_package_start'			=> 'Старт',
    'tpl_package_stop'			=> 'Стоп',
    'tpl_package_restart'		=> 'Перезапустить',
    'tpl_package_kill'			=> 'Принудительно остановить',
    'tpl_package_autoload'		=> 'Автозагрузка',

    'js_package_delete'		=> 'Выполняем удаление...',
    'packet_manager_succecfully'		=> 'Успешно изменено',

    'packet_manager_brainysql'	=> 'Сервер баз данных BrainySQL',
    'packet_manager_memcached'	=> 'Кэширование памяти',
    'packet_manager_ffmpeg'	=> 'Powerful UNIX VIDEO ENCODER',
    'packet_manager_imagemagick'	=> 'Инструмент для работы с изображениями',
    'packet_manager_httpry'	=> 'Сетевой анализатор HTTP-трафика',
    'packet_manager_certbot'	=> 'Скрипт для работы с Let’s Encrypt сертификатами',
    'packet_manager_megacli'	=> 'Приложение для отображение информации о RAID',
    'packet_manager_iotop'	=> 'Анализ нагрузки на дисковую подсистему',
    'packet_manager_atop'	=> 'Интерактивный монитор производительности',
    'packet_manager_iftop'	=> 'Статистика сетевого интерфейса',
    'packet_manager_logrotate'	=> 'Утилита автоматического сжатия, удаления журналов системы',
    'packet_manager_smartmon'	=> 'Утилита мониторинга состояния накопителя',
    'packet_manager_php52'	=> 'php 5.2',
    'packet_manager_php53'	=> 'php 5.3',
    'packet_manager_php54'	=> 'php 5.4',
    'packet_manager_php55'	=> 'php 5.5',
    'packet_manager_php56'	=> 'php 5.6',
    'packet_manager_php70'	=> 'php 7.0',
    'packet_manager_php71'	=> 'php 7.1',
    'packet_manager_php72'	=> 'php 7.2',
    'packet_manager_git'	=> 'Распределённая система управления версиями',
    'packet_manager_shellinabox'	=> 'Браузерный shell клиент',
    'packet_manager_postgresql'	=> 'База данных postgresql',
    'packet_manager_phppgadmin'	=> 'Администрирование сервера PostgreSQL',
    'packet_manager_redis'      => 'База данных для хранилища ключей',
    'packet_manager_openvpn'      => 'OpenVPN транспорт',
    'packet_manager_lognotexist'=>'Лога не существует',
);

?>