<?php

$lang = array(
   // 客户
     'tpl_c_serv_control_select_ip' => '选择 IP',
     'tpl_c_serv_control_select_php' => '选择 PHP / NodeJS 版本',
     'tpl_c_serv_control_all_sites' => '所有站点',
     'tpl_c_serv_control_bridge' => '网桥',
     'tpl_c_serv_control_ver_php' => 'PHP 版本',
     'tpl_c_serv_control_control' => '控制'，

   // 服务器
    'tpl_s_serv_control_php' => 'PHP',
    'tpl_s_serv_control_delete' => '删除',
    'tpl_s_serv_control_reinstall' => '重新安装',
    'tpl_s_serv_control_status' => '服务器状态',
    'tpl_s_serv_control_more' => '更多详情',
    'tpl_s_serv_control_hide' => '隐藏',
    'tpl_s_serv_control_choose_bridge' => '选择网桥的选项',
    'tpl_s_serv_control_yes' => '是',
    'tpl_s_serv_control_no' => '否',
    'tpl_s_serv_control_available_bridges' => '可用网桥'，
    'tpl_s_serv_control_default_bridge' => '默认网桥'，
    'tpl_s_serv_control_choose_php' => '选择 PHP 版本的选项',
    'tpl_s_serv_control_available_php' => '可用的 PHP 版本',
    'tpl_s_serv_control_default_php' => '默认 PHP 版本',
    'tpl_s_serv_control_apply' => '应用',
    'tpl_s_serv_control_save_config' => '保存当前配置',
    'tpl_s_serv_control_load_config' => '加载当前配置',
    'tpl_s_serv_control_cancel' => '取消',
    'tpl_s_serv_control_params_config' => '保存的配置参数',

    'tpl_s_serv_control_open_bridge' => '打开网桥',
    'tpl_s_serv_control_open_php' => '打开 PHP 版本',
    'tpl_s_serv_control_default_bridge' => '默认网桥',
    'tpl_s_serv_control_default_php' => 'PHP 默认',
    'tpl_s_serv_control_select_bridge' => '选择网桥的选项',
    'tpl_s_serv_control_select_php' => '选择 PHP 选项',

    'tpl_s_serv_control_delete_conf' => '删除保存的配置',
    'tpl_s_serv_control_action' => '动作',
    'tpl_s_serv_control_edit_php_ini' => '编辑基本的 php.ini 选项',
    'tpl_s_serv_control_edit_beginners' => '对于初学者',
    'tpl_s_serv_control_edit_experts' => '专家',
    'tpl_s_serv_control_save' => '保存',
    'tpl_s_serv_control_ver_select' => '选择版本',

    'tpl_c_serv_control_control_fpm' => '控制 fpm',
    'tpl_c_serv_control_start' => '开始',
    'tpl_c_serv_control_stop' => '停止',
    'tpl_c_serv_control_restart' => '重启',
    'tpl_c_serv_control_force_restart' => '强制重启',

    'tpl_c_serv_control_client_options' => '客户端选项',

     'tpl_c_serv_control_connect_php_php' => '将 PHP 连接为 mod_php',
     'tpl_c_serv_control_connect_php_cgi' => '将 PHP 连接为 cgi',
     'tpl_c_serv_control_connect_php_fcgi' => '将 PHP 连接为 fcgi',
     'tpl_c_serv_control_connect_php_suphp' => '将 PHP 连接为 suphp',
     'tpl_c_serv_control_connect_php_ruid2' => '将 PHP 连接为 ruid2',
     'tpl_c_serv_control_connect_php_fpm' => '将 PHP 连接为 fpm',
     'tpl_c_serv_control_connection' => '连接',
     'tpl_c_serv_control_additions' => '附加组件',
     'tpl_c_serv_control_additions_connection' => '附加连接',

    'tpl_s_serv_control_name' => '名称',
     'tpl_s_serv_control_stat' => '状态',
     'tpl_s_serv_control_install' => '安装',
     'tpl_s_serv_control_del' => '删除',
     'tpl_s_serv_control_hookup' => '连接'，
     'tpl_s_serv_control_select_all' => '全选',
     'tpl_s_serv_control_cancel_all' => '停用一切',
     'tpl_s_serv_control_connected' => '已连接',


     'tpl_s_serv_control_save_config_php' => '保存当前的 php 配置',
     'tpl_s_serv_control_load_config_php' => '加载当前的 php 配置',
     'tpl_s_serv_control_version_selection' => '选择版本',

     'tpl_s_serv_control_control_fpm' => '控制 fpm',

    'tpl_s_serv_control_command_already_done' => '命令已经成功完成',

     'tpl_s_serv_control_isntall_megapack' => '安装现成的包',
     'tpl_s_serv_control_isntall_megapack_select_webserver' => '选择一个网络服务器',

     'tpl_s_serv_control_isntall_megapack_select_php' => '选择php版本',
     'server_control_mess_repo_update' => '正在更新php扩展列表',
     'server_control_mess_repo_update_ok' => 'php 扩展列表更新成功',

    'server_control_n' => '虚拟主机重建成功。',
    'server_control_n_f_u' => '没有用户数据',
    'server_control_n_f_a' => '别名字段填写不正确。请仅使用字母、数字、破折号和点。 ',
'server_control_n_f_e' => '别名已经存在于主域',
'server_control_are' => '别名已经存在',
'server_control_alias_alredy_domain' => '别名已在域字段中注册。',
'server_control_c' => 'Dir 字段填写不正确。请仅使用字母、数字、破折号和斜线。',
'server_control_d_f' => '域字段填写不正确。请仅使用字母、数字、破折号和点。',
'server_control_d_c' => 'Dir 字段应该完成',
'server_control_dom_c' => '域字段应该完成',
'server_control_dom_a_f' => '别名字段填写不正确。请仅使用字母、数字、空格、分号、逗号、破折号和点。',
'server_control_dom_a_a_e' => '别名已经存在',
'server_control_dom_d_f_c' => '目录字段填写不正确。请仅使用字母、数字、破折号和正斜杠。',
'server_control_dom_d_f_i' => '域字段不正确。请仅使用字母、数字、破折号和句点。',
'server_control_dom_d_f_s' => '必须填写目录字段',
'server_control_dom_d_f_s_c' => '域字段必须填写',
'server_control_i_s' => '安装成功',
'server_control_i_ns' => '安装完成，但出现错误',
'server_control_i' => '正在安装',
'server_control_s_a' => '设置已应用',
'server_control_i_d' => '正在删除',
'server_control_d_s' => '删除成功',
'server_control_d_a' => '卸载完成但出错',
'server_control_c_o' => '选项配置已保存',
'server_control_c_d' => '保存的配置已删除',
'server_control_o' => '处理',
'server_control_i_i' => '正在连接...',
'server_control_r_h' => '正在重建虚拟主机。',
'server_control_z_v' => '请求进行中',
'server_control_r_o' => '编辑基本的 php.ini 选项',
'server_control_f_u' => '对于用户',
'server_control_f_e' => '专家',
'server_control_s_v' => '选择版本',
'server_control_w_s' => '网络服务器',
'server_control_a_2' => 'apache2.2',
'server_control_a_24' => 'apache2.4',
'server_control_ng' => 'nginx',
'server_control_a_n' => 'apache2.2 + nginx',
'server_control_a24_n' => 'apache2.4 + nginx',
'server_control_ko' => '客户端选项',
'server_control_start' => '开始',
'server_control_stop' => '停止',
'server_control_restart' => '重启',
'server_control_frestart' => '强制重启',
'server_control_m_f' => '控制 fpm',
'server_control_s_w' => '选择版本',
'server_control_save' => '保存',
	'server_control_r_i' => '重新安装',
'server_control_m_d' => '默认网桥：',
'server_control_v_php' => '默认 php 版本：',
'server_control_prim' => '应用',
'server_control_s_m' => '选择网桥的能力：',
'server_control_y' => '是',
'server_control_no' => '否',
'server_control_sv_php' => '选择php版本的选项：',
'server_control_d_m' => '可用网桥：',
'server_control_d_v_php' => '可用的 php 版本：',
'server_control_i_php_m' => '将 php 连接为 mod_php',
'server_control_i_php_c' => '将 php 连接为 cgi',
'server_control_i_php_f' => '将 php 连接为 fcgi',
'server_control_i_php_su' => '将 php 连接为 suphp',
'server_control_i_php_ruid' => '将 php 连接为 mod_ruid2',
'server_control_i_php_fpm' => '将 php 连接为 fpm',
'server_control_u_cache' => '更新 php 扩展列表',
'server_control_dop' => '附加组件',
'server_control_name' => '名称',
'server_control_status' => '状态',
'server_control_install' => '安装',
'server_control_del' => '删除',
'server_control_sel_all' => '全选',
'server_control_podcl' => '连接',
'server_control_ins' => '已安装',
'server_control_pod' => '已连接',
'server_control_s_t_c' => '保存当前的 php 配置',
'server_control_l_t_c' => '加载保存的 php 配置',
'server_control_i_php7' => '连接 php 7.0 附加组件',
'server_control_mark_all' => '检查所有',
'server_control_deactivate_all' => '全部停用',
'server_control_to_appplay' => '应用',
'server_control_supl_php' => 'php 7.0 附加组件',
'server_control_supl56' => '连接 php 5.6 附加组件',
'server_control_supl_php56' => 'php 5.6 附加组件',
'server_control_proceccing' => '处理',
'server_control_supl55' => 'php 5.5 附加组件',
'server_control_supl54' => '连接 php 5.4 附加组件',
'server_control_supl_54' => 'php 5.4 附加组件',
'server_control_supl53' => '连接 php 5.3 附加组件',
'server_control_supl_53' => 'php 5.3 附加组件',
'server_control_supl52' => '连接 php 5.2 附加组件',
'server_control_supl_52' => 'php 5.2 附加组件',
'server_control_installing' => '正在安装',
'server_control_installing_s' => '安装成功',
'server_control_installing_e' => '安装完成但出现错误',
'server_control_d_s_e' => '域编辑成功',
'server_control_s_ added' => '域名添加成功',
	'server_control_d_already' => '域已经存在',
'server_control_not_start' => '这种类型的网络服务器没有服务器状态模块',
'server_control_s_ok' => '停止',
'server_control_start_ok' => '开始',
'server_control_domain_sus_delete' => '域删除成功',
'server_control_not_version_aiab' => '版本更改不可用',
'server_control_ability_bridg' => '选择网桥的能力：',
'server_control_ability_php' => '选择php的能力：',
'server_control_key_loaded' => '密钥已加载',
'server_control_csr_created' => 'CSR 创建',
'server_control_error' => '错误',
'server_control_error_read_file' => '读取文件时出错',
'server_control_key_created' => '密钥已创建',
'server_control_edit' => '编辑',
'server_control_select_bridg' => '选择网桥：',
'server_control_not_domain' => '未找到域。',
'server_control_not_paf_domain' => '域字段必须填写',
'server_control_is_not_ip' => '这个IP地址不属于你',
'server_control_error_dir' => '更改目录目录时出错',
'server_control_not_bridg' => '不存在这样的网桥。可用的桥接 - ',
'server_control_not_php' => '没有这样的 php 版本。可用版本是 ',
'server_control_phpvers_default' => '域编辑成功。 PHP默认是',
'server_control_phpvers_default1' => '域名添加成功。 PHP默认是',
'server_control_all_version' => '.可用版本是 ',
'server_control_bridg_default' => '域编辑成功。默认网桥是',
'server_control_bridg_default1' => '域添加成功。默认网桥是',
'server_control_not_root' => '您没有足够的权限。删除 user_edit 字段 ',
'server_control_list_domain' => '收到域列表。',
	'server_control_email_exist' => '这个域有邮件账户。请先删除它们。',

'server_control_error_user' => '参数错误',
'server_control_err_ip' => 'IP 地址错误。它们可能尚未定义。',

'server_control_overlimit_domains' =>' 已达到站点数量限制。最大站点数',

'server_control_overlimit_dnz_zones' =>' 已达到 DNS 区域数量的限制。 DNS 区域的最大数量',
'server_control_alias_alr_exist' => '别名已经存在。',

'server_control_label_sel_admin' => '用户名',
'server_control_please_wait' => '请稍候',
'server_control_pleas_wait_adding' => '添加中请稍候',

'server_control_no_site_ added' => '还没有添加站点',
'server_control_user_notselect' => '指定的搜索条件没有域',
'server_control_seluserplease' => '请选择一个用户',
'server_control_selversion' => '选择版本',
'server_control_fpm_restart_all' => '在所有 FPM 上运行',
    'server_control_viewprogress' => '查看进程',
    'server_control_stopprogress' => '停止安装',
    'server_control_processrun' => '正在安装...',
    'server_control_warning' => '停止 php 安装过程可能会导致 php 出现故障。请确认停止进程。',
    'server_control_warning_yesstop' => '停止',
    'server_control_warning_nocont' => '继续'，
    'server_control_pleaseselectphp' => '选择php版本',
    'server_control_pleaseselectphp_all_install' => '所有php版本都已经安装',
    'server_control_pleaseselectphp_reinstall' => '选择要重新安装的 php 版本',
    'server_control_pleaseselectphp_all_reinstall' => '还没有安装php版本',

    'server_control_configsaveok' => '已应用设置',
    'server_control_warning_mega' => '停止捆绑安装过程会导致 php 和 webserver 的错误工作。请确认停止进程。',
    'server_control_extensionphptitletable' => 'PHP 扩展',
'server_control_sel_bridge' => '选择网桥：',
'server_control_demo_message' => '抱歉，此操作在演示版中被禁用。',
    'server_control_nothingtodel' => '请选择要删除的内容。',
    'server_control_nothingtodel_notinstall' => '没有安装任何东西。请在“Web 服务器”选项卡上安装所需的软件包集',
    'server_control_fpm_startok' => '启动成功',
    'server_control_fpm_ok_mess' => '成功',
    'server_control_star' => '* 字符仅在别名中可用',

    'server_control_confirmdeldom' => '确认域删除',
    'server_control_confirmdeldom_withfiles' => '删除文件和域文件夹',

    'server_control_deldomadeny' => '您没有删除指定域的权限。',

    'server_control_mod_modsec' => '控制 ModSecurity',
    'server_control_mod_modsec_check_label' => '激活',
    'server_control_defaulthint_stat_modsec' => '尚未配置 mod_security 状态',

    'server_control_mod_modsec_stat_change' => 'ModSecurity 状态已更改',
    'server_control_mod_modsec_stat_off' => 'ModSecurity 被禁用。请联系您的服务器管理员。',

    'server_controlAliasHint' => '该字段是可选的。要输入多个别名，请用空格、换行符、逗号或; ',
    'server_statLogDomains' => '域记录状态',
    'server_control_seluserLogs' => '选择用户',
    'server_control_LogDomain' => '域',
    'server_control_LogDomainAccess' => '访问日志',
    'server_control_LogDomainError' => '错误日志',
    'server_control_LogDomainDomainNotExist' => '用户没有域',
    'server_control_LogDomainDomainWrongUsername' => '无效用户名',
    'server_control_LogDomainDomainSetOk' => '日志状态更改成功',
    'server_control_MenuStatusLog' => '管理日志状态',
    'server_control_hintLogAccess' => '记录状态 access_log /etc/httpd/vhost_logs/domain_access 和/ 或/etc/nginx/vhost_logs/domain_access',
    'server_control_hintLogError' => '日志状态 error_log /etc/httpd/vhost_logs/domain_error 和/ 或/etc/nginx/vhost_logs/domain_error',
'server_control_logs' => '日志'，
    "server_tcp_socket_err_create" => "套接字创建错误",
    "server_tcp_socket_err_conn" => "套接字连接错误",
    "server_showAll" => "显示全部",
    "server_listDomColUser" => "用户",
    "server_hintDenyEditBridgeRoot" => "编辑网桥不可用，因为用户启用了 jailphp。您可以在此处禁用 jailphp <a target=``_blank`` href=``index.php?do=hostacc&subaction=jail``> </a>" ,
    'server_control_captionDomain' => '域',
    'server_control_captionDomainHolder' => '请输入域名或别名',
    'server_controlAllVersionPhps' => '所有 php 版本',
    'server_controlAllUsers' => '所有用户',
    'server_controlFilterDoms' => '搜索：',
    'server_controlpath_config' => '配置文件路径',
    'server_control_dont_user_jail' => '所选用户没有被放入 PHP 监狱',
    'server_control_dont_file_config' => '配置文件 php.ini，未找到。',
    'server_control_extensions_php_user_jail' => '监狱用户的扩展',
    'server_control_whait_reinstall_php' => '请稍候，正在安装 php',
    'server_control_whait_delete_php' => '正在删除php，请稍候',
    'server_control_whait_reinstall_webserver' => '等待安装包',
    'server_control_error_directive' => '输入指令值时出错',
    'server_control_error_paramert' => '参数错误。',
    'server_control_error_pm_start_servers' => 'pm.start_servers 必须至少为 pm.min_spare_servers 且至少为 pm.max_spare_server',
    'server_control_error_pm_start_servers2' => 'pm.min_spare_servers 不能超过 pm.max_spare_server',
    'server_control_error_rm_sites' => '删除站点时出错，站点目录中有其他主机帐户站点。',
    'server_control_warning_delete' => '停止删除 php 或 webserver 进程可能会导致 php 和 webserver 出现故障。请确认停止进程。',
    'server_control_stopprogress_delete' => '停止删除',
    'server_forbidden_add_subdomain' => '防止将子域添加到其他主机帐户',
    'server_forbidden_add_subdomain_message' => '添加子域失败，根域使用不同的主机帐户',
'server_control_error_aliases' =>' 别名填写不正确。别名字段必须包含有效的域。',
    'server_forbidden_add_subdomainHintEdit' => '如果禁用，操作从安装的那一刻开始 - 之前添加的子域不会进行任何更改',
'server_control_erroractmpm' => '激活新 MPM 时出错',
    'server_control_setupdefaultmpm' => '默认设置。',
    'server_control_applysuccesscurap' => '已成功应用于当前 Apache。',
    'server_control_adddomain' => '添加站点',
	'server_control_configfpm_phpcgi' => '为 PHP CGI 配置 FPM 池参数',
    'server_control_areaapplyvalues' => '这些值的范围是指定主机账户的所有站点。',
'server_control_bridgerules' =>' mod_php 网桥仅适用于 MPM Prefork。 http2 协议仅适用于 MPM Worker 和 Event。',
'server_control_usempm' => '使用 Apache MPM 模块',
    'server_defaultpage_title' => '默认页面',
    'server_defaultpage_managebrainy' => '此服务器由 BrainyCP 控制面板管理。如果您希望看到该站点，那么您可能：',
    'server_defaultpage_notadddomain' => '没有在站点部分添加域名；',
    'server_defaultpage_notclearcache' => '没有清除浏览器缓存；',
    'server_defaultpage_wrongip' => '将域链接到错误的 IP 地址。',
    'server_defaultpage_yourhostingpanel' => '您的主机控制面板 -',
'server_sitecreateok' => '您的网站已成功创建',
'server_domaincreateok' => '您的域已成功创建',
'server_replacefielindextostartwork' => '用您自己的文件替换域文件夹中给定的 index.html 文件，您的站点将开始工作。',
    'server_sitesuspmessage' => '您的网站已注册',
'server_seitesuspmess2' => '被阻止',
'server_panelcaption' => '控制面板',
'server_locksiteextend' => '您看到此页面是因为您的网站已被封锁。有关详细信息，请联系您的服务器管理员。',
'server_loginotheruser' => '以其他用户身份登录',
    'server_panelsuspmessage' => '您的帐户',
    'server_lockpanelextend' => '您看到此页面是因为您的帐户已被封锁。有关详细信息，请联系您的服务器管理员。',

    'js_nodejs_action' => '此端口上的 NodeJS 应用程序将重新启动',
    'web_nodejs_app_ok' => 'NodeJS 应用重启成功，应用端口：',
    'web_nodejs_app_err' => '使用端口重新启动 NodeJS 应用程序时发生错误：',
    'web_nodejs_app_no' => '找不到带有端口的 NodeJS 应用程序',
    'server_defaultpage_emptycert' => '使用 https 协议时没有证书。',

);

?>
