<?php

$lang = array(
  'ssh'	=> 'SSH服务',
    'msg_save_new_params' => '新参数保存成功',
    'msg_restore_old_params' => '',
    'msg_save_new_expert' => '新参数保存成功',
    'command_ssh_stop' => '停止',
    'command_ssh_start' => '开始',
    'command_ssh_restart' => '重启',
    'btn_ssh_save' => '保存更改',
    'btn_ssh_restore' => '恢复默认配置',
    'msg_select_yes' => '是',
    'msg_select_no' => '否',
    'msg_select_default' => '未定义',
'ssh_not_alloved' => '您没有足够的权限访问此页面',
'ssh_managmant' => '管理 SSH:',
'ssh_for_lilok' => '标准视图',
'ssh_for_experts' => '专家',
'ssh_status_ssh' => 'SSH 状态：',
'ssh_parametrs' => '参数',
'ssh_val' => '值',
'ssh_detail' => '说明',
'ssh_failed' => '请求完成但有错误',
'ssh_sc_error' => '脚本错误：',
    'ssh_stat_run' => '运行',
    'ssh_stat_stop' => '停止',
    'msg_restore_opt_ok' => '之前的配置已成功恢复',
    'ssh_docwithoutname' => '无标题文档',
'sshparams_port' => 'SSHD 在哪个端口上监听。默认值为 22. ',
    'sshparams_allowagentforward' => '允许 ssh-agent 重定向。默认为是',
    'sshparams_allowtcpforward' => '允许或拒绝 TCP 转发。默认为是',
    'sshparams_allowgateway' => '允许远程主机访问转发端口。默认值为否. ',
    'sshparams_allowx11' => '允许图形 X11 重定向。默认为否',
    'sshparams_x11offset' => 'sshd 作为 X11 重定向可用的第一个显示的数量。默认值为 10',
    'sshparams_x11userlocalhost' => 'sshd 是否应将 X11 重定向的范围限制为本地地址。默认为是',
    'sshparams_printmot' => '当用户交互登录时，sshd 是否应该显示 /etc/motd。默认为是',
    'sshparams_printlast' => 'sshd 是否应该在用户交互登录时显示上次会话的日期和时间。默认为是',
    'sshparams_tcpkeepalive' => '系统是否应该向客户端发送 TCP 消息以保持连接。默认为是',
    'sshparams_uselogin' => '登录标识符是否应该用于交互式会话。默认值为否. ',
    'sshparams_usepriv' => '确定 sshd 是否应该共享权限。默认为是',
    'sshparams_permituser' => 'sshd 是否应该接受 ~/.ssh/environment 和 ~/.ssh/authorized_keys 中的 environment= 选项。默认为否',
    'sshparams_compress' =>' 指示是否启用数据压缩。可以是&apos;是&apos; - 允许压缩。 &apos;延迟&apos; - 压缩被推迟，直到用户成功通过身份验证。 &apos;没有&apos; - 禁止压缩。默认为 & apos; 延迟 & apos ;. ',
    'sshparams_clientaliveinterval' => '以秒为单位设置时间间隔。如果在此时间间隔内没有与客户端通信，sshd 将通过加密通道发送消息。',
    'sshparams_clalivemax' => '设置 sshd 在没有收到客户端任何响应的情况下连续发送给客户端的消息数量',
    'sshparams_showpatchlevel' => '显示补丁级别',
    'sshparams_usedns' =>' 指定 sshd 是否应检查主机名，并使用此名称将客户端传输的 IP 地址与从 DNS 接收的 IP 地址进行比较。默认为是',
    'sshparams_addressfamily' => '地址',

	
	
);

?>
