<?php

$lang = array(
  'ssh'	=> 'SSH сервис',
    'msg_save_new_params'	=> 'Новые параметры успешно сохранены',
    'msg_restore_old_params'	=> '',
    'msg_save_new_expert'	=> 'Новые параметры успешно сохранены',
    'command_ssh_stop'		=> 'Стоп',
    'command_ssh_start'		=> 'Старт',
    'command_ssh_restart'	=> 'Перезапустить',
    'btn_ssh_save'		=> 'Сохранить изменения',
    'btn_ssh_restore'		=> 'Востановить конфигурацию по умолчанию',
    'msg_select_yes'		=> 'да',
    'msg_select_no'		=> 'нет',
    'msg_select_default'	=> 'Неопределенно',
	'ssh_not_alloved'	=> 'У Вас недостаточно прав для захода на данную страницу',	
	'ssh_managmant'	=> 'Управление SSH:',		
	'ssh_for_lilok'	=> 'Стандартный вид',	
	'ssh_for_experts'	=> 'Для экспертов',		
	'ssh_status_ssh'	=> 'Статус SSH:',	
	'ssh_parametrs'	=> 'Параметр',	
	'ssh_val'	=> 'Значение',		
	'ssh_detail'	=> 'Описание',	
	'ssh_failed'	=> 'Запрос завершен с ошибкой',
	'ssh_sc_error'	=> 'Ошибка скрипта:',
    'ssh_stat_run'	=> 'Запущен',
    'ssh_stat_stop'	=> 'Остановлен',
    'msg_restore_opt_ok'	=> 'Прошлая конфигурация успешно восстановлена',
    'ssh_docwithoutname'=>'Документ без названия',
	'sshparams_port'=>'На каком порту слушает SSHD. По умолчанию 22.',
    'sshparams_allowagentforward'=>'Разрешить перенаправление ssh-agent. По умолчанию yes.',
    'sshparams_allowtcpforward'=>'Разрешить или запретить перенаправление TCP. По умолчанию yes.',
    'sshparams_allowgateway'=>'Разрешить удаленным хостам доступ к перенаправленным портам. По умолчанию - no.',
    'sshparams_allowx11'=>'Разрешить перенаправление графический подсистемы X11. По умолчанию no.',
    'sshparams_x11offset'=>'Номер первого дисплея, доступного sshd в качачестве перенаправления X11. По умолчанию 10.',
    'sshparams_x11userlocalhost'=>'Должен ли sshd ограничить область перенаправления X11 локальным адресам. По умолчанию yes.',
    'sshparams_printmot'=>'Должен ли sshd выводить на экран /etc/motd при интерактивном входе пользователя. По умолчанию yes.',
    'sshparams_printlast'=>'Должен ли sshd выводить на экран дату и время последего сеанса при интерактивном входе пользователя. По умолчанию yes.',
    'sshparams_tcpkeepalive'=>'Должна ли система посылать TCP сообщения клиенту с целью поддержания соединения. По умолчанию yes.',
    'sshparams_uselogin'=>'Должен ли использоваться индификатор login для интерактивного сеанса. Значение по умолчанию - no.',
    'sshparams_usepriv'=>'Определяет, должен ли sshd разделять привилегии. По умолчанию yes.',
    'sshparams_permituser'=>'Должен ли sshd воспринимать ~/.ssh/environment и опцию environment= в ~/.ssh/authorized_keys. По умолчанию no.',
    'sshparams_compress'=>'Указывает, разрешено ли сжатие данных. Может быть &apos;yes&apos; - сжатие разрешено. &apos;delayed&apos; - сжатие отложено до тех пор, пока пользователь успешно не аутентифицируется. &apos;no&apos; - сжатие запрещено. По умолчанию - &apos;delayed&apos;.',
    'sshparams_clientaliveinterval'=>'Задает временной интервал в секундах. Если в течении этого интервала не было обмена данными с клиентом sshd посылает сообщение по зашифрованному каналу.',
    'sshparams_clalivemax'=>'Задает количество сообщений к клиентам, которые sshd посылает подряд, не получая какого либо ответа от клиента.',
    'sshparams_showpatchlevel'=>'Показывать уровень патча',
    'sshparams_usedns'=>'Указывает, должен ли sshd проверять имя хоста и используя это имя сверять IP адрес переданный клиентом с полученным от DNS. Значение по умолчанию - yes',
    'sshparams_addressfamily'=>'AddressFamily',

	
	
);

?>