<?php

$lang = array (
	'apacserver' => '服务器管理',
	'directory_password' => '设置目录密码',
	'apacserver_pass_selectdom' => '选择域',
	'apacserver_pass_nodominacc' => '首先，您需要将域添加到您的帐户',
	'apacserver_dir_safe' => '目录不存在或格式不正确',
	'apacserver_pass_safe' => '密码强度低',
	'apacserver_add_dir_failed_already_exist' => '此文件夹的密码已存在.',
	'apacserver_add_www_redir_ok' => '成功添加重定向',
	'apacserver_delete_www_redir_ok' => '成功删除重定向',
	'apacserver_add_www_failed_exist' => '这种类型的重定向已经存在.',
	'apacserver_add_www_failed_bad_from' => '网站名称格式不正确',
	'apacserver_add_www_failed_bad_to' => '目标格式无效',
	'apacserver_add_www_failed_not_perm' => '无权进行此操作!',
	'apacserver_add_http_failed_exist' => '此站点已存在重定向.',
	'apacserver_add_http_redir_ok' => '成功添加重定向',
	'apacserver_delete_http_redir_ok' => '成功删除重定向',
	
	'tpl_apac_delete' 	=> '删除',
	'msg_apac_ok' 		=> '成功',
	'msg_apac_not_perm' 	=> '未执行',
	
	'tpl_apac_jmp_site' 	=> '网站重定向',
	'tpl_apac_add_site' 	=> '添加站点',
	'tpl_apac_site' 	=> '网站',
	'tpl_apac_www' 		=> 'www',
	'tpl_apac_nowww' 	=> '无www',
	'tpl_apac_both' 	=> '两个',
	'tpl_apac_pattern' 	=> '按模式',
	'tpl_apac_destination' 	=> '目的地',
	'tpl_apac_add_jpm' 	=> '请稍候，添加重定向... ',
	'tpl_apac_forwarding' 	=> '重定向',
	'tpl_apac_forwarding_listhttp' 	=> '重定向列表',
	'tpl_apac_action_list' 	=> '站点、用户、分配、重定向、操作',
	
	'tpl_apac_user' 	=> '用户',
	'tpl_apac_action' 	=> '操作',

	'tpl_apac_jmp_far' 	=> '重定向 HTTP — HTTPS',
	'tpl_apac_add_folder' 	=> '设置目录密码',
	'tpl_apac_jmp_type' 	=> '重定向类型',
	'tpl_apac_select_http' 	=> 'https 到 http',
	'tpl_apac_select_https' 	=> 'http 到 https',
	'tpl_apac_folders' 	=> '目录',
	'tpl_apac_folder' 	=> '目录',
	'tpl_apac_action_list1' 	=> '站点、用户、重定向、操作',
	'tpl_apac_action_list2' 	=> '目录、用户、密码、操作',

	'tpl_apac_set_pass_folder' 	=> '设置目录密码',
	'tpl_apac_passwd' 	=> '密码',
	'tpl_apac_nopass_folder' 	=> '没有为任何文件夹设置密码',

	'tpl_apac_select_www' 		=> '在 www.',
	'tpl_apac_select_nowww' 	=> '在 .',
	'tpl_apac_jmp_www' 	=> '重定向 WWW',


	'js_apac_jmp_table' 	=> '该列表已包含此站点的批量重定向数据',
	'js_apac_add_domain' 	=> '需要将域添加到帐户',
	'apacserver_list_directory' 	=> '受密码保护的目录列表',
	'apacserver_list_not_directory' 	=> '受密码保护的目录列表为空',
	'apacserver_list_http' 	=> '域列表',
	'apacserver_none_list_http' 	=> '域列表为空',
	'apacserver_list_directory_http' 	=> '目录列表',	
	'apacserver_none_list_directory_http' 	=> '目录列表为空',
	'apacserver_not_remove' 	=> '这不是你的',
	'apacserver_not_type' 	=> '不存在的类型',
	'apacserver_list_forwarding' 	=> '重定向列表',
	'apacserver_not_list_forwarding' 	=> '重定向列表为空',	
	'apacserver_not_unic_id' 	=> 'unic_id 输入不正确，或者这个重定向不再存在.',		
	'apacserver_not_domain' 	=> '域不存在.',
	'apacserver_not_forward' 	=> '未正确分配重定向',
	'apacserver_not_path_forward' 	=> '未指定重定向路径',	
	'apacserver_del_process' 	=> '已删除...',

	'apacserver_setpass_login' 	=> '账号',
	'apacserver_notset_any_redir_site' 	=> '未设置重定向到任何站点.',
	'apacserver_notset_any_redir_http' 	=> '未设置到任何站点的 HTTP 重定向.',
	'apacserver_seluser' => '选择用户',
	'apacserver_http_failedadd' => '参数错误，未选择用户. ',
	'apacserver_error_pages' => '错误页面',
	'apacserver_list_error_pages' 	=> '自定义错误页面',
	'apacserver_error' 	=> '错误',
	'apacserver_code_error' 	=> '错误代码',	
	'apacserver_file' 	=> '文件扩展名',	
	'apacserver_fild_load' 	=> '加载字段',
	'apacserver_download' 	=> '加载',
	'apacserver_visible_file' 	=> '查看',
	'apacserver_delete' 	=> '删除',
	'apacserver_save' 	=> '保存',	
	'apacserver_not_site' 	=> '用户没有网站',	
	'apacserver_not_file_download' 	=> '不支持的文件类型',
	'apacserver_error_file_download' 	=> '文件上传错误',
	'apacserver_optimization' 	=> '网站优化',	
	'apacserver_optimization_gzip' 	=> '启用 gzip 压缩',
	'apacserver_optimization_cesh' 	=> '启用浏览器静态缓存',
	'apacserver_successfully' 	=> '保存更改',
	'apacserver_time_cash' 	=> '缓存时间: ',
	'apacserver_day' 	=> '天',
	'apacserver_incorecly' 	=> '值不正确',
	'apacserver_optimisation_files' 	=> '优化文件',
	'apacserver_bacup_copy' 	=> '备份路径',
	'apacserver_save_bacup_copy' 	=> '保存备份',
	'apacserver_not_files_optimisation' 	=> '没有找到优化文件',	
	'apacserver_error_directory' 	=> '目录与正则表达式不匹配',		
	'apacserver_action' 	=> '操作',			
	'apacserver_action_restore' 	=> '恢复',	
	'apacserver_path' 	=> '目录',		
	'apacserver_date' 	=> '日期',
	'apacserver_error_id' 	=> '错误 ID 备份',
	'apacserver_error_domain' 	=> '域与正则表达式不匹配',	
	'apacserver_error_user' 	=> '用户不匹配正则表达式',
	'apacserver_restore_succesfully' 	=> '从备份恢复的文件',	
	'apacserver_remove_succesfully' 	=> '备份已删除',
	'apacserver_empty_path' 	=> '要创建备份，请指定路径.',
	'apacserver_empty_path_1' 	=> '要创建备份，请指定文件夹',

    'apacserver_wrongdest1' 	=> '目标格式无效。以非http格式指定.',
	'apacserver_gpagespeed_link_text' 	=> '用 Google PageSpeed Insights进行检查',
    'apacserver_extCache' 	=> '缓存扩展: ',
    'apacserver_extCacheEx' 	=> '通过指定扩展名 ; , | 或空白。例如: ttf|jpg|jpeg|png|ico|css|bmp|swf|js|txt|tar|zip|pdf|tar.gz|woff|woff2',
    'apacserver_extCacheTimeMin' 	=> '分钟',
    'apacserver_extCacheTimeHour' 	=> '小时',

    'apacserver_cacheHintWrongExt' => '扩展名列表的格式不正确',
    'apacserver_cacheHintWrongExtExp' => '缓存时间格式不正确',
    'apacserver_cacheHintSaveok' => '保存成功',
    'apacserver_cacheWaitPlease' => '请稍候',
    'apacserver_dostatforthisext' => '通过 nginx 处理这些扩展的静态信息',
    'apacserver_error_reserv_directory' => '错误。系统保留的目录.',
    'apacserver_error_type_files' => '<br>支持的文件类型 html, htm, php',
    'apacserver_optimization_off_nginx' => '禁用Nginx中的动态缓存',
    'apacserver_empty_ssl_domain' => '重定向错误。域未安装 ssl 证书.',
    'apacserver_addredir' => '添加重定向',
    'apacserver_optimiz_title' => '优化',
    'apacserver_addpasstitle' => '添加密码',
	'apacserver_extCacheEx_1' 	=> '常用扩展列表: ttf|jpg|jpeg|png|ico|css|bmp|swf|js|txt|tar|zip|pdf|tar.gz|woff|woff2',	
	
	
);