<?php
$lang = array (
'blacklist' => 'IP 黑名单',
'blacklist_ip' => '检查过的ip',
'blacklist_check' => '检查',
'blacklist_save' => '保存',
'blacklist_error_domain' => '指定的域与正则表达式不匹配',
'blacklist_succesfully' => '成功完成。',
'blacklist_error_ip' => 'ip 地址输入错误或为空',
'blacklist_dnsbl_server' => 'DNSBL 服务器',
'blacklist_status' => '状态',
'blacklist_black' => '黑名单',
'blacklist_ok' => '不在黑名单中',
'blacklist_detail' => '附加信息',
'blacklist_list_dnsbl' => 'DNSBL 服务器列表',
'blacklist_check_ip_dnsbl' => '检查黑名单中的ip',
'blacklist_monitor' => '按本地ip时间监控',
'blacklist_period_minutes' => '时段分钟',
'blacklist_error_minutes' => '分钟输入错误',
'blacklist_many_minutes' => '很多分钟',
'blacklist_disabled_scan' => '扫描已禁用',
'blacklist_whit_scan' => '请稍候，正在扫描',
'blacklist_whait_save' => '保存中请稍候',
'blacklist_block_ip' => '阻止的 ip',
    'blacklist_check_ip_header' => '检查ip',
    'blacklist_resultcheck' => '检查结果',
);