<?php

$lang = array(
    'certs_control' => 'SSL/TLS控制',
    'service_serv' => '服务',
    'service_domain' => '域',
    'service_expire' => '到期日期',
    'service_expire_up' => '有效期至',
    'service_keysize' => '密钥大小',
    'service_issuer' => '颁发机构',
    'service_action' => '动作',
    'service_action_loadnewcert' => '加载新的',
    'service_apply_exist' => '应用现有证书',
    'service_install_newcert' => '安装新证书',
    'service_install_newcert_title' => '选择一个或多个服务来安装证书',
    'service_certificate' => '证书',
    'service_privatekey' => '私钥',
    'service_cabunlde' => '证书颁发机构包',
    'service_install_newcert' => '安装',
    'service_reinstall_cert' => '安装新证书',
    'service_install_error_nosel' => '选择要为其安装证书的服务',
    'service_applyexist' => '应用现有证书',
    'service_applyexist_ok' => '申请成功',
    'service_install_new_ok' => '新证书安装成功',
    'service_save' => '保存',
    'service_cancel' => '取消',
    'service_cert_del' => '移除证书',
    'service_overwrite_cert_q' => '覆盖证书？',
    'service_overwrite_cert_yes' => '是',
    'service_overwrite_cert_no' => '否',
    'service_cert_not_ins' => '未安装证书',
    'service_cert_del_confirm' => '确认证书删除',
    'service_cert_del_confirm_yes' => '是',
    'service_cert_del_confirm_no' => '否',
    'service_cert_del_complete' => '证书已删除',
    'service_cert_view' => '查看证书',

    'service_cert_install_wrong_cert' => '证书未安装，请检查输入的证书、密钥和证书颁发机构包的正确性',


    'tpl_certs_cert' => '证书',
    'tpl_certs_del' => '删除',
    'tpl_certs_certdel' => '移除证书',
    'tpl_certs_cerdeactiv' => '停用证书',
    'tpl_certs_key' => '密钥',
    'tpl_certs_certkey' => '删除密钥',
    'tpl_certs_gen_csr' => '生成 CSR',
    'tpl_certs_select_key' => '选择密钥',
    'tpl_certs_key_new' => '新密钥',
    'tpl_certs_domain_name' => '域名',
    'tpl_certs_key_size' => '选择大小',

    'tpl_certs_country' => '国家',
    'tpl_certs_state' => '状态',
    'tpl_certs_city' => '城市',
    'tpl_certs_company' => '公司',
    'tpl_certs_division' => '部门',
    'tpl_certs_create_csr' => '创建 CSR',
    'tpl_certs_load_crt' => '上传证书',
    'tpl_certs_name' => '名称',
    'tpl_certs_copy_file_crt' => '复制证书文件',
    'tpl_certs_insert_file_crt' => '插入证书文件',
    'tpl_certs_download_crt' => '下载 CRT',
    'tpl_certs_your_crt' => '你的 CRT',

    'tpl_certs_domain' => '域',
    'tpl_certs_certs' => '证书',
    'tpl_certs_lenkey' => '密钥长度',
    'tpl_certs_status' => '状态',
    'tpl_certs_func' => '功能',
    'tpl_certs_edit' => '编辑',
    'tpl_certs_save' => '保存',
    'tpl_certs_del_key' => '删除密钥',

    'tpl_certs_c_keys' => '密钥',
    'tpl_certs_c_crts' => '证书',
    'tpl_certs_c_setting_crts' => '安装证书',
    'tpl_certs_c_list_keycerts' => '域名和证书列表',
    'tpl_certs_c_create_priv_key' => '创建私钥',
    'tpl_certs_c_name' => '名称',
    'tpl_certs_c_key_size' => '密钥长度',
    'tpl_certs_c_create_key' => '创建密钥',
    'tpl_certs_c_download_priv_key' => '上传私钥',
    'tpl_certs_c_copy_key' => '复制密钥',
    'tpl_certs_c_insert_file_key' => '插入带有密钥的文件',
    'tpl_certs_c_load_key' => '加载密钥',
    'tpl_certs_c_your_private_keys' => '你的私钥',

    'tpl_certs_c_generate_csr' => '生成 CSR',
    'tpl_certs_c_select_key' => '选择一个密钥',
    'tpl_certs_c_new' => '新建',
    'tpl_certs_c_name_domain' => '域名',
    'tpl_certs_c_select_size' => '密钥长度',

    'tpl_certs_c_install_cert' => '安装证书',
    'tpl_certs_c_select_domain' => '选择域',
    'tpl_certs_c_select_crt' => '选择证书',
    'tpl_certs_c_or_load_new' => '或者在下面上传',
    'tpl_certs_c_cert1' => '证书 (CRT)',
    'tpl_certs_key1' => '私钥（KEY）',
    'tpl_certs_c_list_domain_crts' => '域名和证书列表',

    'tpl_certs_s_domain_name' => '域名',
    'tpl_certs_s_ip_addr' => 'IP 地址',
    'tpl_certs_s_root_dir' => '根目录',
    'tpl_certs_s_owner' => '所有者',
    'tpl_certs_s_key_size' => '密钥大小',
    'tpl_certs_s_domain_def' => '默认域',
    'tpl_certs_s_action' => '动作',
    'tpl_certs_s_domain_def_ip' => '将默认域设置为 IP',

    'tpl_certs_s_service_cert' => '服务证书',
    'tpl_certs_s_list_certs' => '证书列表',


    'msg_cert_err_nodomain' => '错误,域名丢失',
    'msg_cert_err_nocode' => '错误,国家/地区代码的长度必须为 2 个字符。例如 RU, UK ',
    'msg_cert_err_State' => '错误,状态必须以a-z格式填写',
    'msg_cert_errCity' => '错误,城市必须填写a-z格式',
    'msg_cert_errCompany' => '错误,公司必须填写a-z格式',
    'msg_cert_errOtdel' => '错误,部门必须填写a-z格式',

    'msg_cert_create_info0' => '证书',
    'msg_cert_create_info1' => '已成功创建',
    'msg_cert_err_create_domain' => '错误,加载此域的密钥时出现问题',
    'msg_cert_err_del_cert' => '错误,无法删除您的密钥，因为它已被主机 ',
    'msg_cert_err_del_cert_cert' => '错误,无法删除您的证书，因为主机正在使用它 ',
    'msg_cert_ok_del_cert' => '密钥及其证书已成功删除',
    'msg_cert_ok_del_cert1' => '证书已被删除',
    'msg_cert_err_load_certs' =>' 错误,证书未加载 ',
    'msg_cert_let_info0' => '证书',
    'msg_cert_let_info1' => '已经配置并应用',

    'msg_cert_ok_unset_dom' => '证书已从域中删除',
    'msg_cert_apply_lets_cert' => '请稍候,创建证书的过程正在进行中',

    'msg_cert_installed_ok' => '证书安装',

    'msg_cert_not_installed_yet' => '证书未安装',
    'msg_key_not_installed_yet' => '未安装密钥',
    'msg_cert_install_foremail' => '安装邮件证书',
    'msg_cert_used_foremail' => '用于邮件',

    'msg_cert_generate_cert' => '生成证书',

    'msg_cert_nocertkey' => '没有这样的密钥和证书，没有什么可以删除的',

'certs_control_gen_process' => '生成...',
'certs_control_apply_cert_process' => '申请...',
'certs_control_remove_cert_process' => '正在删除...',
'certs_control_install_newcert_process' => '安装中...',


    'certs_control_error_validcert' => '错误,密钥与给定的证书不匹配',
    'certs_control_error_validcert_chain' => '错误,证书颁发机构包与给定的证书不匹配 ',

    'certs_control_failed_gen_letsen' => '生成证书时出错,域必须链接！',
    'certs_control_failed_gen_letsen_dns_record' => '生成证书时出错,检查域是否有 dns 记录',
    'certs_control_failed_gen_letsen_dns_record_error_arg' => '生成证书时出错,未知参数集 ',
    'certs_control_failed_gen_letsen_dns_record_AAAA' => '生成证书时出错,面板中没有虚拟主机有ipv6，删除dns条目AAAA',
    'certs_control_failed_gen_letsen_serv' => '生成证书时出错,服务器主机名必须链接到服务器 ip! ',
    'certs_control_failed_gen_letsen_domain' => '生成证书时出错,该域必须链接到服务器 ip,检查域的 dns 记录',
    'certs_control_failed_gen_letsen_error_domain' => '生成证书时出错,禁止为此域颁发证书',


    'certs_control_certload_ok' => '证书上传成功',
    'certs_control_keyload_ok' => '密钥加载成功',

    'certs_control_certload_failedname' => '证书未加载,证书名称有误',
    'certs_control_keyload_failedname' => '密钥未加载,键名错误',

    'certs_control_certload_wrongformat' => '无效的证书格式',
    'certs_control_keyload_wrongformat' => '错误的密钥加载格式',
    'msg_certs_control_certs_info0' => '证书',
    'msg_certs_control_certs_info1' => '申请成功',
    'cert_control_seluser' => '名称',
    'cert_control_load_wait' => '请稍候',
    'cert_control_gen_lets' => '生成 Lets Encrypt',
    'cert_control_gen_lets_renew' => '生成新的 Lets Encrypt 证书',
    'cert_control_letsen_autorenew' => '证书自动更新',
    'cert_control_letsen_autorenew_stat_save' => '已保存',
    'certs_control_domain_setdef' => '域默认设置为 IP',
    'certs_control_ipdomain' => 'IP 地址',
    'certs_control_gen_letsen_hostname_ok' => 'Lets Encrypt 证书生成成功',
    'certs_control_active_autorenew_lets_hostname' => '证书自动更新',
'certs_control_no_keys' => '无密钥',
'certs_control_no_certs' => '无证书',
'certs_control_no_domains' => '未添加域',
    'certs_control_no_cert' => '移除证书',
    'certs_control_gennew_letsen' => '生成新的 Lets Encrypt',

    'certs_control_nottimeyet' => '证书',
    'certs_control_nottimeyet2' => '仍然有效',
    'certs_control_pleasereloadpage' => '智能证书将在 20 秒内应用。请重新加载页面以恢复工作',
    'certs_control_pleasereloadpage_del' => '智能证书将在 20 秒后删除。请重新加载页面以恢复工作',

    'certs_control_pleasewaitloadinfocert' => '请稍候,正在加载证书信息',
    'certs_control_letsfailedexistgen' => '证书尚未过期，因此无法为域生成新证书',

    'certs_warn_notinstall_certbot' => 'CertBOT 未安装,请安装 CertBOT',
    'certs_warn_notinstall_certbot_btn' => '安装 CertBOT',
    'certs_warn_nothing_sel' => '请选择证书',

    'certslets_tip_help' => '服务器的主机名将用于生成 Lets Encrypt 证书。您可以在 <a target=_blank href=/index.php?do=properties> 服务器配置 </a> 部分更改主机名。 <br/> 请确保绑定到您的主机名服务器 ',

    'certs_error_nxdomaingencertlets' => '您需要从 IP 服务器为域添加一条 A 记录',
    'certs_error_genletssuffauth' => '没有足够的权限来授权域',
    'certs_error_genletssuffauth_check' => '检查域是否绑定到该特定服务器',
    'certs_check_gencertforpanel_host' => '为 panel.hostname 生成证书',
    'certs_check_gencertforpanel_host_hint' => '要生成证书，请确保面板域已绑定到您的服务器',
    'certs_select_cert' => '选择证书',
    'certs_data_cert' => '证书数据',
    'certs_too_many_cert' => '稍后生成证书,已达到证书生成限制',
    'certs_too_many_cert_services' =>' 稍后生成服务证书,已达到证书生成限制',
    'certs_too_many_error' => '生成证书时出错,太多失败的证书创建,检查重定向的站点配置，并在几小时后重试',
    'certsfailedGenUnauth' => '授权失败,请检查站点设置中是否设置了重定向，域根目录授权密码',
    'certs_error_user' => '用户错误',
    'certs_error_domain' => '域错误',
    'certs_remove_domain_default_ip' => '删除IP上的默认域',
    'certs_wildcard' => '通配符',
    'certs_wildcard_text' => '通配符 - 生成以下形式的证书的能力：',
    'certs_error_api_cloudflare' => '该站点已连接到 cloudflare，在验证来自 cloudflare 服务的数据时检测到错误。检查来自 cloudflare 的数据以及域的 ns 服务器',
    'certs_gencerttitle' => '生成证书',
    'certs_certdomaccpanel' => '面板可用域的证书：',
    'certs_thiscertnotallow' => '此证书不能与其他证书一起生成,所以上面的证书在生成的时候是不可用的',
    'certs_limitslets' => 'Lets Encrypt加密限制',
'certs_control_cloudflare' => '如果域已连接到 cloudfare 服务，请禁用代理，或通过面板中的 cloudflare 菜单添加您的域',
'certs_control_remove_cert_service' => '确认删除服务证书,<br> <br> 警告，删除服务证书会导致服务进一步停止，建议重新安装证书，或应用现有的证书',
    'certs_control_api_empty_user' => 'ISP 面板中没有这样的用户：',
    'certs_control_api_get_user_certs' => '已为用户成功获取证书列表',
    'certs_control_api_error_parametrs' => '参数块错误',
    'certs_control_api_error_rm_cert' => '无法删除所需的证书，因为它正在使用中',
    'certs_control_api_success_rm_cert' => '已成功为用户删除密钥和证书',
    'certs_control_api_empty_domain' => '域名未找到',
    'certs_control_get_log_letcen' => '查看Lets Encrypt加密日志',
    'certs_control_filed_crt' => '生成证书时出错',
    'certs_control_empty_log_letcen' => '未找到日志文件',

);

?>