<?php

$lang = array(
    'ftp'                   => 'FTP',
    'start'                 => '开启',
    'stop'                  => '停止',
    'Default_vsftpd' => '重置默认 vsftpd.conf',
    'Default_pureftpd' => '恢复标准的 pure-ftpd.conf',
    'Default_proftpd' => '重置默认 proftpd.conf',
    'homedir_user' => '用户主目录',
    'delete_homedir_user' => '删除用户根目录',
    'ftp_path' => '主目录',
    "ftp_quota_use" => "已使用",
    "ftp_quota_avail" => "可用",
    "ftp_change_pass" => "更改密码",
    "ftp_change_pass_placeholder" => "输入新密码",
    "ftp_change_quota" => "更改配额",
    "ftp_change_quota_placeholder" => "输入配额大小",
    "Ftp_change_current_quota" => "当前配额",
    "ftp_action" => "操作",
    "ftp_error_add_user_exist" => "存在同名用户",
    "ftp_success_add_user" => "用户已添加",
    "ftp_deleted" => "已删除",
    "ftp_installed" => "已安装",
    "ftp_reinstalled" => "重新安装",
    "ftp_install" => "安装",
    "ftp_reinstall" => "重新安装",
    "ftp_delete" => "删除",
    "ftp_start" => "开始",
    "ftp_stop" => "停止",
    "ftp_restart" => "重启",
    "ftp_stat" => "状态",
    "ftp_server" => "FTP 服务器",
    "ftp_stat_started" => "开始",
    "Ftp_stat_started_failed" => "运行出错",
    "ftp_stat_stopped" => "已停止",
    "ftp_stat_restarted" => "重启成功",
    "Ftp_process_launched" => "操作正在运行，请稍候...",
    "ftp_process_finished" => "操作完成",
    "ftp_configure_share" => "配置",
    "ftp_conf_edit" => "编辑设置",
    "ftp_conf_save" => "保存",
    "Ftp_conf_save_file" => "保存到文件",
    "ftp_conf_save_success" => "保存成功",
    "Ftp_restore_default_settings" => "恢复默认设置",
    "ftp_restore_default_settings_success" => "恢复默认设置",
    "ftp_repairmyconf" => "恢复我的设置",
    "Ftp_repairmyconf_success" => "我的设置已恢复",
	
    "ftp_login" => "登录",
    "ftp_path" => "主文件夹",
    "ftp_usage" => "已使用",
    "ftp_quota" => "配额",
    "ftp_action" => "动作",
    "ftp_search_user" => "查找",
    "ftp_accounts" => "FTP 帐户",
    "ftp_search_user_holder" => "输入登录信息",
    "ftp_pagesize" => "每页帐户数",

    "ftp_useradd" => "添加 FTP 用户",
    "ftp_pass_new" => "密码",
    "ftp_homedir" => "主文件夹",
    "ftp_newuser_add" => "添加 FTP 账户",
    "ftp_newuser_add_success" => "用户添加",
    "ftp_edit_user_sub" => "编辑用户",
    "ftp_delete_user_sub" => "删除",
    "ftp_edit_user_quota" => "编辑配额",
    "ftp_edit_user_pass" => "更改密码",
    "ftp_edit_user_quota_title" => "FTP 配额",
    "ftp_edit_user_quota_mb" => "Mb",
    "ftp_edit_user_quota_cancel" => "取消",
    "ftp_edit_user_quota_file" => "更改文件配额",

    "ftp_edit_pass_enter" => "密码",
    "ftp_edit_pass_enter_again" => "重复密码",
    "ftp_edit_pass_strength_pass" => "密码强度",
    "ftp_edit_cancel" => "取消",
    "ftp_del_user" => "删除用户",
    "ftp_del_homedir" => "删除用户主文件夹",
    "ftp_del_user_cancel" => "取消",
    "ftp_del_user_confirm" => "删除",
    "ftp_del_user_process" => "正在删除...",
    "ftp_config_ftp_client" => "配置FTP客户端",
    
   "ftp_count_accept" => "申请",
    "ftp_user_exist" => "用户已经存在",
    "ftp_import_ok" => "导入成功",
    "ftp_import_failed" => "导入失败，错误",

    "ftp_selectftpacc" => "选择用户",

    "ftp_searchftpacc" => "请输入您的用户名",

    "ftp_addaftpsubacc" => "添加 FTP 子账户",

    "ftp_noftpins" => "未安装FTP服务器。请联系您的管理员",

    "ftp_user_login_new_wrong" => "无效的用户名格式",
    "ftp_user_login_new_wrong_null" => "请输入您的登录名",
    "ftp_user_login_pass_null" => "输入密码",
    "ftp_user_userdir_null" => "输入您的主文件夹",
    "ftp_user_userdir_wrong" => "无效的主文件夹格式",

    "ftp_user_quota_null" => "输入配额大小",
    "ftp_user_quota_wrong" => "配额格式无效。必须是整数",

    "ftp_user_add_ok" => "用户添加成功",

    "ftp_generatelog_userfolder" => "生成日志",
    "ftp_generatelog_ok" => "日志生成成功",
    "ftp_cron_run_failed" => "警告！CROND 未在服务器上运行。该模块可能无法正常工作。安装并运行 crond 以确保正确运行。",
	
    "ftp_suspended_acc" => "添加、编辑、删除 FTP 帐户已被阻止。请联系您的管理员。",
    "ftp_setting" => "FTP 服务器设置",
    "ftp_not_instaled" => "未安装",
    "ftp_p_f" => "纯ftpd",
    "ftp_proftpd" => "proftpd",
    "ftp_det" => "更多",
    "ftp_hide" => "隐藏",
    "ftp_ns" => "未选中",
    "ftp_f_e" => "高级",
    "ftp_f_l" => "对于用户",
    "ftp_y" => "是",
    "ftp_n" => "否",
    "ftp_on" => "开启",
    "ftp_off" => "关闭",

    "ftp_pass_change_ok" => "密码修改成功",
    "ftp_quota_change_ok" => "配额更改成功",

    "ftp_adduser_failed_overlimit" => "超出 FTP 帐户限制。最大 FTP 帐户数",

    "ftp_nousers added" => "没有创建用户",
    "ftp_noaccounts" => "没有账户",
    "ftp_not_passwd_for_passwd" => "密码不匹配",
    "ftp_main_ftpacc" => "主 FTP 帐户。无法删除",
    "ftp_quota_not_use" => "未使用配额",
    "ftp_quota_hint" => "输入 0 表示无限配额",
    "ftp_user_readonly" => "只读",
    "ftp_user_readonly_res_ok_save" => "FTP 账户访问更改成功",
    "ftp_pathMainFTP" => "主 FTP 帐户的主文件夹",
    "ftp_remove_user_error" => "删除文件时出错。此目录包含站点",
    "ftpChangePassMain" => "注意！更改主FTP账号密码也会设置相同的新密码进入面板。",
	
);

?>