<?php
$lang = array(
 "hashmon" => "哈希值管理",
    "hashmon_path" => "监控目录",
    "hashmon_addnewmon" => "编辑监控任务",
    "hashmon_addnewmonbtn" => "添加",
    "hashmon_period_run" => "运行周期",
    "hashmon_period_run_day" => "每日",
    "hashmon_period_run_week" => "每周",
    "hashmon_period_run_month" => "每月",
    "hashmon_period_run_time" => "运行时间",
    "hashmon_period_run_time_hh" => "hh",
    "hashmon_period_run_time_mm" => "mm",
    "hashmon_period_run_time_weeksel" => "选择一周中的几天运行",
    "hashmon_period_run_time_weeksel_mon" => "星期一",
    "hashmon_period_run_time_weeksel_tue" => "星期二",
    "hashmon_period_run_time_weeksel_wed" => "星期三",
    "hashmon_period_run_time_weeksel_tue" => "星期四",
    "hashmon_period_run_time_weeksel_fri" => "星期五",
    "hashmon_period_run_time_weeksel_sat" => "星期六",
    "hashmon_period_run_time_weeksel_sun" => "星期日",
    "hashmon_period_run_time_datesel" => "指定运行日期",
    "hashmon_period_run_time_datesel_del" => "删除",
    "hashmon_period_run_time_datesel_add" => "添加启动日期",
    "hashmon_period_run_time_sendemailafterscan" => "完成后发送邮件",
    "hashmon_period_run_time_status" => "状态",
    "hashmon_run_includeonly" => "仅搜索",
    "hashmon_run_includeonly_placeholder" => "指定文件扩展名，以,; 或空格分隔。例如：php, txt; sh py。指定目录：dir:/home/folder。允许多行",
    "hashmon_run_includeonly_placeholder_full" => "指定文件扩展名以,;或空格分隔。<br/>例如：php, txt; sh py。<br/>指定目录：dir:/home/文件夹。<br/>指定目录搜索选定的扩展名：dir: / folder / || txt || php <br/> 允许多行",
    "hashmon_run_exclude" => "排除文件",
    "hashmon_run_exclude_placeholder" => "指定用,; 或空格分隔的文件扩展名。例如：php, txt; sh py.",

   "hashmon_createhash" => "创建快照",
    "hashmon_hashlist_path" => "路径",
    "hashmon_hashlist_date" => "创建时间",
    "hashmon_hashlist_mainhash" => "Main",
    "hashmon_hashlist_option" => "选项",
    "hashmon_hashlist_delete" => "删除",
    "hashmon_hashlist_select" => "选择比较",

    "hashmon_wrongdir" => "指定的目录无效",
    "hashmon_pleasewait" => "请稍候",
    "hashmon_nofindbymask" => "没有找到指定监控过滤器的文件",
    "hashmon_findbymask" => "已创建快照",
    "hashmon_pathnotexist" => "指定的目录不存在",
    "hashmon_option_removehash" => "删除快照",
    "hashmon_option_setmain" => "设置快照为主",
    "hashmon_option_viewhash" => "查看快照",
    "hashmon_option_denydeletehash" => "您不是此快照的所有者",
    "hashmon_option_comparehash" => "比较",
    "hashmon_option_uncheck" => "删除选择",
    "hashmon_option_complete_compare" => "比较成功完成",
    "hashmon_hashlist_no" => "还没有拍照",
    "hashmon_hashlist_table_title" => "快照列表",
    "hashmon_comphash_table_title" => "当前运行的快照比较进程列表",
    "hashmon_comphash_table_title_noproc" => "没有进程在运行",
    "hashmon_comphash_table_title_captch1" => "快照 1",
    "hashmon_comphash_table_title_captch2" => "快照 2",
    "hashmon_comphash_table_title_captch_createtime" => "创建时间",
    "hashmon_comphash_table_title_comp_starttime" => "开始时间",
    "hashmon_comphash_table_title_comp_completeperc" => "已完成：",
    "hashmon_comphash_table_title_finish" => "已完成的快照比较列表",
    "hashmon_stop_comp" => "停止",

    "hashmon_comphash_table_compared_no" => "未执行图像比较",
    "hashmon_comphash_table_compared_view" => "查看结果",
    "hashmon_comphash_table_compared_manage" => "控制",
    "hashmon_comphash_table_compared_remove_rescomp" => "删除",
    "hashmon_comphash_table_compared_view_rescomp" => "查看",
    "hashmon_comphash_table_compared_del_deny" => "无权删除结果",
    "hashmon_comphash_table_compared_view_deny" => "无权查看结果",

    "hashmon_comphash_table_compared_view_title" => "查看图片对比结果",
    "hashmon_comphash_table_compared_view_newin" => "新文件：",
    "hashmon_comphash_table_compared_view_remove" => "已删除的文件：",
    "hashmon_comphash_table_compared_view_newin_not" => "未找到",
    "hashmon_comphash_table_compared_view_diff" => "快照之间的文件差异：",
    "hashmon_comphash_table_compared_view_diff_no" => "没有找到文件",
    "hashmon_comphash_seldomain" => "选择域",
    "hashmon_comphash_nodomainuser" => "无域",

    "hashmon_add2cronjobs" => "添加作业",
    "hashmon_updatecronjobs" => "更新",
    "hashmon_removecronjobs" => "撤消",
    "hashmon_namejob" => "作业名称",
    "hashmon_namejob_exist" => "指定名称的作业已经存在。请考虑另一个",
    "hashmon_namejob_exist_noedit" => "指定名称的作业不存在",
    "hashmon_namejob_empty" => "作业名称不能为空",
    "hashmon_wrongdir_format" => "扫描的目录格式无效",
    "hashmon_wrong_namejob" => "作业名称格式无效",
    "hashmon_wrong_findonlywith" => "无效的字段格式仅搜索扩展名",
    "hashmon_wrong_findonlywithout" => "Exclude files with extension, folders 字段的格式无效",
    "hashmon_wrong_period" => "无效格式句号",
    "hashmon_wrong_timehourmin" => "开始时间格式错误",
    "hashmon_wrong_weekdays" => "错误的星期几格式",
    "hashmon_wrong_numbermonth" => "无效的开始日期格式",
    "hashmon_job_save_complete" => "成功保存",
    "hashmon_job_list" => "监控作业列表",

    "hashmon_job_listtable_title_name" => "姓名",
    "hashmon_job_listtable_title_stat" => "状态",
    "hashmon_job_listtable_title_timerun" => "开始时间",
    "hashmon_job_listtable_title_opt" => "选项",
"hashmon_job_listtable_title_nojobsadd" => "没有添加监控任务",
    "hashmon_job_notifyemail" => "通知邮件",
    "hashmon_job_notifyemail_hint" => "监控任务完成后，会向指定邮箱发送一条消息，其中包含更改、删除和添加文件的统计信息",
    "Hashmon_job_notifyemail_format" => "通过或空格输入您的电子邮件",
    "hashmon_job_selmaincapt" => "选择基线快照",
    "hashmon_job_selmaincapt_hint" => "对比选中的快照，检测新增、删除、修改的文件。<br/>如果还没有快照，请先创建，再添加监控任务",
    "Hashmon_delcapt_comp_succ" => "删除的图片对比",
    "Hashmon_emaillistnotify_wrong" => "电子邮件的无效字段格式",
    "Hashmon_notexistmaincapt" => "选定的主图像不存在",
    "hashmon_job_status" => "活动",
    
   'hashmon_period_intime' => 'in',
    'hashmon_period_ondays' => '按数字',
    'hashmon_period_day' => '每日',
    'hashmon_period_week' => '每周',
    'hashmon_period_month' => '每月',
    'hashmon_weekly_short_arr' => array ('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'),
    'hashmon_job_runnow' => '运行',
    'hashmon_job_edit' => '编辑',
    'hashmon_job_remove' => '删除',
    'hashmon_tablejob_title_maincapt' => '基础快照',
    'hashmon_tablejob_removedeny' => '您无权删除此监控作业',
    'hashmon_tablejob_removeok' => '作业已删除',
    'hashmon_email_erorr_send' => '发送带有监控统计信息的电子邮件时出错',
    'hashmon_email_res_monit' => '目录监控结果',
    'hashmon_hash_removerow_selected' => '删除选中的',
    'hashmon_denyusespecsymbol' => '作业名称中不允许有 _ 和空格字符',
    'hashmon_oraddjob' => '或',
    'hashmon_oraddjob_btn' => '添加作业',
    'hashmon_firstcreatehash' => '没有快照。先拍个快照 ',
    'hashmon_selallcheck' => '全选',
    'hashmon_oraddjob_timet' => '将任务添加到计划中',
    'hashmon_timettitle' => '时间表',
    'hashmon_sel2capt2comp' => '请选择 2 张图片进行比较',
    
    

);

?>