<?php

$lang = array(
    'hostacc'           			=> '主机帐户',
    'hostacc_suspended_sites_ok'           => '主机帐户上的站点被阻止.',
    'hostacc_unsuspended_sites_ok'           => '主机帐户上的站点已解锁.',
    'hostacc_suspended_ftp_ok'           => '主机帐户上的 FTP 被阻止.',
    'hostacc_unsuspended_ftp_ok'           => '主机帐户上的 FTP 已解锁.',
    'hostacc_suspended_email_ok'           => '主机账户上的邮件被阻止.',
    'hostacc_unsuspended_email_ok'           => '主机帐户邮件已解锁.',
    'hostacc_suspended_cron_ok'           => '主机帐户上的cron被阻止.',
    'hostacc_unsuspended_cron_ok'           => '主机帐户上的 Cron 已解锁.',
    'hostacc_suspended_panel_ok'           => '用户面板访问被阻止.',
    'hostacc_unsuspended_panel_ok'           => '面板访问已解锁.',
    'hostacc_suspended_shell_ok'           => '外壳用户访问被阻止.',
    'hostacc_unsuspended_shell_ok'           => '外壳访问已解锁.',
    'hostacc_suspended_full_ok'           => '用户访问被完全阻止.',
    'hostacc_unsuspended_full_ok'           => '用户访问完全解锁.',
    'hostacc_unsuspended_user_del'           => '您没有足够的权限删除此用户.',
    'hostacc_unsuspended_user_del_ok'           => '用户已成功删除.',


    'hostacc_stat_susp_sites_title' => '网站屏蔽',
    'hostacc_stat_susp_ftp_title' => 'FTP 阻塞',
    'hostacc_stat_susp_email_title' => '阻止邮件',
    'hostacc_stat_susp_cron_title' => '阻止 Cron',
    'hostacc_stat_susp_shell_title' => 'shell',
    'hostacc_stat_susp_panel_title' => '面板锁',
    'hostacc_stat_susp' => '是',
    'hostacc_stat_unsusp' => '否',
    'hostacc_stat_susp_reason' => '阻塞的原因',
    'hostacc_stat_unsusp_ftpuser_failed' => 'FTP 用户因错误而解锁',

    'hostacc_stat_confirm_susp' => '确认阻塞',
    'hostacc_btn_susp' => '阻止',
    'hostacc_btn_unsusp' => '解除封锁',

    'hostacc_btn_susp_full' => '完全阻止',
    'hostacc_btn_unsusp_full' => '完全解除封锁',
    'hostacc_date_susp' => '上次阻塞的日期',
    'hostacc_date_unsusp' => '最后解锁日期',

    'hostacc_delete_ip_from_acc_failed' => '指定的ip：<br/> {ips} <br/>用于：<br/> {domains} <br/> 要更改上述域的配置中的IP，请选择一个可用 IP 的数量：<br /> ',
    'hostacc_data_unset_plan' => '未指定',
    'hostacc_data_unset_group' => '未指定',

    'lang_rootaccess' => 'ROOT 访问',
    'lang_ftp_access_restart' => 'FTP 重启',
    'lang_ftp_access_install' => 'FTP 重新安装',
    'lang_is_reseller' => '经销商',
    'lang_is_reseller_planview' => '查看经销商计划',
    'lang_is_reseller_groupview' => '查看经销商组',
    'lang_is_reseller_groupcreate' => '创建经销商组',
    'lang_is_reseller_plancreate' => '为经销商创建计划',

    'msg_unlimited0' => '无限制',
    'msg_unlimited' => '&#8734',
    'msg_no_permission_suspend_sites' => '没有停止站点的权限！',
    'msg_no_permission_unsuspend_sites' => '没有权限运行网站！',
    'msg_no_permission_suspend_ftp' => '没有停止 FTP 的权限！',
    'msg_no_permission_unsuspend_ftp' => '没有权限运行 FTP！',
    'msg_no_permission_suspend_shell' => '没有权限停止shell！',
    'msg_no_permission_unsuspend_shell' => '没有权限启动shell！',
    'msg_no_permission_suspend_cron' => '无权停止 CRON！',
    'msg_no_permission_unsuspend_cron' => '没有权限运行 CRON！',
    'msg_no_permission_suspend_panel' => '没有权限停止面板！',
    'msg_no_permission_unsuspend_panel' => '没有启动面板的权限！',
    'msg_no_permission_suspend_full' => '没有权限完全停止工作！',
    'msg_no_permission_unsuspend_full' => '没有完全重启的权限！',

    'msg_no_permission_edit' => '您没有编辑权限',
    'msg_no_group_name' => '没有组名',
    'msg_no_group_add_ok' => '群组添加成功',
    'msg_no_group_edit_ok' => '组编辑成功',
    'msg_seccess_del' => '删除成功',
    'msg_add_host_acct' => '添加主机账户',
    'msg_edit_host_acct' => '编辑主机帐户',
    'msg_save_host_acct' => '保存主机账户',
    'msg_add_plan' => '添加计划',
    'msg_edit_plan' => '编辑计划',
    'msg_edit_user' => '编辑用户',
    'msg_username' => '用户名：',
    'msg_passwd' => '密码：',
    'msg_ip' => 'IP 地址：',
    'msg_group' => '组：',
    'msg_plan' => '计划：',
    'msg_language' => '语言：',
    'msg_count_mailbox' => '邮箱数量：',
    'msg_bandwidth' => '流量：',
    'msg_count_sites' => '站点数量：',
    'msg_count_db' => 'MySQL 数据库：',
    'msg_count_subdomains' => 'DNS 区域的数量：',
    'msg_count_dns_zones' => 'DNS 区域的数量：',
    'msg_count_mailperhour' => '每小时电子邮件数：',
    'msg_count_disk' => '磁盘空间：',
    'msg_count_ftp_acct' => 'FTP 账户：',
    'msg_shell_access' => 'shell访问：',
    'msg_nginx_access' => '允许 nginx 缓存调整大小：',
    'msg_owner' => '所有者：',

    'msg_seccess_ added' => '添加成功',
    'msg_seccess_edit' => '编辑成功',

    'msg_only_number' => '请在字段中只输入一个数字',
    'msg_both_num_leter' => '在字段中只输入数字或英文字母',

    'msg_only_number_bandwith' => '使用数字指定带宽',
    'msg_only_number_sites' => '用数字表示站点的数量',
    'msg_only_number_subdomains' => '使用数字来指定子域的数量',
    'msg_only_number_databases' => '使用数字来指定数据库的数量',
    'msg_only_number_mailbox' => '使用数字指定邮箱数量',
    'msg_only_number_mailperhour' => '使用数字表示每小时的电子邮件数量',
    'msg_only_number_ftp_acct' => '使用数字来指定ftp账户的数量',
    'msg_only_number_disk' => '使用数字指定磁盘',
    'msg_both_lang' => '请选择语言',
    'msg_both_shell' => '指定要使用的shell',
    'msg_both_plan' => '输入计划名称',
    'msg_both_template' => '指定模板',


    'msg_everything_good' => '一切都没有出错',
    'msg_ip_wrong' => 'IP 地址不正确',
    'msg_exists_plan' => '这个计划已经存在',
    'msg_done' => '完成',
    
    'msg_done_pass' => '密码长度必须至少为 7 个字符',
    'msg_done_username' => '用户名不得超过 8 个字符',

    'msg_both_username' => '使用数字和英文字母输入用户名。至少 3 个字符',
    'msg_both_group' => '使用数字和英文字母指定组名',
    
    'msg_no_user_sel' => '这不属于用户',
    'msg_everything' => '没关系',

    'msg_edit_or_add_group' => '添加新组或编辑当前组→',
    'msg_edit_or_add_plan' => '添加新计划或编辑当前计划→',

    'js_lang_select_ok' => '语言更改成功',

    'tpl_host_add_plan' => '添加套餐计划',
     'tpl_host_edit_plan' => '编辑套餐计划',
     'tpl_host_save_plan' => '保存套餐计划',
     'tpl_host_add_new_plan' => '添加新计划',
     'tpl_host_plan_name' => '计划名称：',
     'tpl_host_bandwidth' => '流量：',
     'tpl_host_disk' => '磁盘：',
     'tpl_host_sites' => '站点：',
     'tpl_host_subdomains' => 'DNS 区域：',
     'tpl_host_databases' => '数据库：',
     'tpl_host_mailbox' => '邮箱：',
     'tpl_host_mailperhour' => '每小时电子邮件数：',
     'tpl_host_ftp_acct' => 'FTP 账户：',
     'tpl_host_shell_access' => 'shell访问：',
     'tpl_host_lang' => '语言：',
     'tpl_host_lang_noselect' => '未选中',

    'tpl_host_groups_acct' => '主机帐户组',
    'tpl_host_current_group' => '当前组：',
    'tpl_host_groupEditortitle' => '组编辑器',
    'tpl_host_create_new_group' => '新建',
    'tpl_host_name_new_group' => '新组名：',
    'tpl_host_select_not_defined' => '未定义',
    'tpl_host_select_yes' => '是',
    'tpl_host_select_no' => '否',
    'tpl_host_select_form_save' => '保存',
    'tpl_host_select_form_del' => '删除',

    'tpl_host_list_title' => '所有主机帐户',
    'tpl_host_list_login' => '账号',
    'tpl_host_list_plan' => '计划',
    'tpl_host_list_homefolder' => '主文件夹',
    'tpl_host_list_ip' => 'IP',
    'tpl_host_list_disk' => '磁盘',
    'tpl_host_list_group' => '组',
    'tpl_host_list_control' => '控制',
    'tpl_host_list_edit' => '编辑',
    'tpl_host_list_delete' => '删除',
    'tpl_host_list_t_plan' => '套餐计划',
    'tpl_host_list_t_plans' => '套餐计划',

    'tpl_host_single_title' => '主机账户信息',
    'tpl_host_single_action' => '操作：',
    'tpl_host_single_abort' => '取消',
    'tpl_host_single_create_date' => '创建日期：',
    'tpl_host_single_edit_date' => '最后修改日期：',
    'tpl_host_single_domain' => '域',
    'tpl_host_single_ip' => 'IP',
    'tpl_host_single_home' => '主目录',
    'tpl_host_single_aliases' => '别名',
    'tpl_host_single_triger_on' => '解锁',
    'tpl_host_single_triger_off' => '阻止',
    'tpl_host_single_change_lang' => '更改语言',

    'lang_host_api' => 'API 访问',
    'lang_host_apifull' => '完整的 API 访问权限（管理员）',
    'apifull_off' => '权限不足，无法执行此 API 请求',

    'hostacc_suspended_sites' =>' 添加、编辑、删除站点被阻止，请联系您的管理员。',
'hostacc_del_process' => '正在删除...',
'hostacc_successf_add' => '主机账户添加成功',

    'hostacc_change_pass_label' => '密码',
    'hostacc_change_pass_label1' => '输入新密码',
    'hostacc_change_pass_label2' => '重复新密码',
    'hostacc_change_pass_pass_diff' => '输入的密码不匹配',
    'hostacc_change_pass_exec' => '更改密码',
    'hostacc_change_pass_exec_ok' => '密码修改成功',

    'hostacc_refresh_user_cache' => '刷新用户统计',
    'hostacc_refresh_user_cache_btn' => '刷新',
    'hostacc_refresh_user_cache_ok' => '用户统计信息更新成功',

    'hostacc_user_search' => '搜索',
    'hostacc_return_main' => '← 返回主机账户列表',
    'hostacc_user_search_res_empty' => '没有找到',

    'hostacc_user_search_pleasewait' => '正在搜索...',

    'msg_only_number_dnz_zones' => '使用数字来指定 DNS 区域的数量',
    'hostacc_sel_addgroup' => '添加组',
    'hostacc_sel_addpackage' => '添加套餐',
    'hostacc_noaddhostacc_yet' => '尚未添加主机帐户',
    'hostacc_no_plans' => '尚未添加任何计划',

    'hostacc_updatecache_detail' => '重新计算统计信息：站点数、邮箱数、已用空间数、FTP 帐户数、数据库数。',

    'hostacc_user_alreadyexist' => '同名用户已经存在',
    'hostacc_user_userhaventdomain' => '尚未添加域',
    'hostacc_user_signin' => '账号',
    'hostacc_user_signin_warning' => '当以所选用户登录时，您将无法获得当前用户的授权。 <br/> 确认授权？',
    'hostacc_user_signin_warning_yes' => '是',
    'hostacc_user_signin_warning_no' => '否',
    'hostacc_user_signin_failed' => '授权失败，用户需要重新设置密码。',
    'hostacc_user_signin_process' => '授权...',
    'hostacc_user_plan_not_set' => '未指定',

    'hostacc_header_admin_param' => '禁止任何未定义的内容。',
    'hostacc_header_user_param' => '任何未定义的东西都是允许的。',
    'hostacc_chache_name' => '更改名称',
    'hostacc_input_name' => '请输入一个新名称',
    'hostacc_suc_change' => '成功完成',
    'hostacc_suc_change_empty' => '组名中的空值',
    'hostacc_error_name_group' => '名称错误',
    'hostacc_error_no_user' => '此用户不存在',
    'hostacc_confirm_userdel' => '确认删除用户',
    'hostacc_confirm_userdel_yes' => '是',
    'hostacc_confirm_userdel_no' => '否',

    'hostacc_confirm_universal_yes' => '是',
    'hostacc_confirm_universal_no' => '否',

    'hostacc_usernotexist' => '指定的用户不存在',

    'hostacc_stat_susp_sites_hint' => '站点被阻止',
    'hostacc_stat_susp_ftp_hint' => 'FTP 被阻止',
    'hostacc_stat_susp_email_hint' => '邮件被阻止',
    'hostacc_stat_susp_cron_hint' => 'Cron 被阻止',
    'hostacc_stat_susp_panel_hint' => '面板被锁定',
    'hostacc_stat_susp_full_hint' => '访问完全被阻止',
    'hostacc_stat_susp_reason_hint' => '阻塞的原因：',
    'hostacc_stat_susp_reason_hint_notset' => '未指定',
    'hostacc_incorecly_simbol' => '套餐名称中的禁止字符',

    'hostacc_createjailuser' => 'Jail环境',
    'hostacc_createjailuserhint' => '用户将被置于Jail环境中以限制访问',

    'hostacc_jailTitle' => '配置Jail',
    'hostacc_jailStatusTitle' => 'Jail Shell',
    'hostacc_jailStatusTitlePHP' => 'Jail PHP',
    'hostacc_jailStatusSave' => '保存',
    'hostacc_jailStatusDesel' => '禁用所有 Jail Shell',
    'hostacc_jailStatusSel' => '启用所有 Jail Shell',
    'hostacc_jailStatusDeselPHP' => '禁用所有 PHP Jail',
    'hostacc_jailStatusSelPHP' => '启用所有 PHP Jail',
    'hostacc_jailStatusRebuild' => '保存',
    'hostacc_jailStatusSetResOk' => 'Jail环境改变成功',
    'hostacc_jailStatusSetResFail' => 'Jail环境未改变',
    'hostacc_jailPHPHint' => 'PHP 将在Jail环境中运行，仅适用于 fastcgi 网桥 (php-fpm) ',
    'hostacc_jailnewaccShell' => '将新的主机帐户放入 Jail Shell',
    'hostacc_jailnewaccPhp' => '将新的主机帐户放入 Jail PHP',
    'hostacc_jailStatusAutoNewAcc' => '保存',
    'hostacc_jailStatusAutoNewAccSaveok' => '保存成功，<br/> 如果 Jail 中可用的包列表已更改，则需要使用下表重新构建 Jail ',

    'hostacc_jailerrorMountMysql' => '挂载 mysql 套接字时出错',

    'hostacc_confirmDelPlan' => '确认计划删除',
    'hostacc_limit_mysql_user' => '限制用户的 mysql 连接',
    'hostacc_max_questions' => 'MYSQL 对每小时请求数的限制',
    'hostacc_max_updates' => '每小时 MYSQL 数据编辑限制',
    'hostacc_max_connections' => 'MYSQL 并发连接限制',
    'hostacc_max_user_connections' => '每小时用户连接数的 MYSQL 限制',
    'hostacc_error_msg_questions' => '对 max_questions 使用数字',
    'hostacc_error_msg_updates' => '使用数字输入 max_updates 值',
    'hostacc_error_msg_user_connections' => '使用数字输入 max_user_connections 值',
    'hostacc_error_msg_connections' => '使用数字输入 max_connections 值',
    'hostacc_jailreinit' => '用户Jail环境的重新初始化正在进行中，请等一下。',
    'hostacc_jailreinitParams' => '指定参数：',
    'hostacc_jailreinitParamsHost' => '设置Jail环境状态：',
    'hostacc_jailreinitParamsPHP' => '设置Jail环境php状态：',
    'hostacc_jailreinitParamsPHPForce' => '重建用户虚拟主机：',
    'hostacc_jailreinitParamsHostOn' => '启用',
    'hostacc_jailreinitParamsHostOff' => '禁用',
    'hostacc_jailreinitParamsHostRebuildYes' => '是',
    'hostacc_jailreinitParamsHostRebuildNo' => '否',
    'hostacc_jailreinitBaseOnHostConf' => '根据当前用户设置重新初始化Jail环境。',
    'hostacc_jailConfTitle' => '设置',
    'hostacc_jailListAppAvailInJail' => 'Jail中可用的软件包列表',
    'hostacc_jailListAppAvailInJailHint' => '指定通过； 、空格或每个数据包换行。要在保存后应用更改，您需要为用户重建Jail',
    'hostaccPleaseWaitAuth' => '正在进行授权,请等一下。',

    'hostaccRebuldJailAll' => '重建Jail环境',
    'hostaccRebuldJailAllConfirm' => '确认为所选用户重建Jail环境。 <br/> 预计执行时间为 1 到 20 分钟，具体取决于所选用户的数量。',
    'hostaccRebuldViewLog' => '查看日志',
    'hostaccRebuildAlreadyrun' => 'Jail重建已经在运行。请查看日志',
    'hostaccRebuildStartOk' => 'Jail重建成功开始。单击查看日志按钮查看日志。 <br/> 在Jail重建过程中，禁止任何与Jail有关的操作。 <br/> 请等待操作完成。',
    'hostaccRebuildStartFailed' => '传入用户列表错误',
    'hostaccRebuildViewLogBtn' => '查看Jail重建日志',
    'hostaccRebuildListUser' => '要重建的用户列表：',
    'hostaccRebuildStartJailShell' => '重建Jail Shell',
    'hostaccRebuildStartJailPHP' => '重建 PHP Jail',
    'hostaccRebuildFinish' => 'Jail重建完成',
    'hostaccerror_e' => '错误。 mysql 中的保留值（1E 或 2e 等）',

    'hostacc_max_user_task' => '最大任务数（空 - 无限制）',
    'hostacc_max_user_memory' => '以 MB 为单位的最大内存（空 - 无限制）',
    'hostacc_max_user_cpu' => '最大 CPU 负载百分比（100% - 1 核，[200% ...]，空 - 无限制）',
    'hostacc_max_user_ior' => '最大读取 IO（空 - 无限制）',
    'hostacc_max_user_iow' => '最大写入 IO（空 - 无限制）',
    'hostacc_empty_log_jail' => '没有找到监狱重建日志。',
    'hostacc_user_reserv_system' => '该用户已被系统保留。',
    'hostacc_error_name_numper_all' => '主机帐户不能全是数字。',
    'hostacc_error_connect_mysql' => '无法删除用户。连接到数据库时出错',
    'hostacc_error_umount_user' => '卸载用户目录时出错。',
    'hostacc_error_clear_rc_local' => '清除 rc.local 时出错',
    'hostacc_error_add_user_linux' => '添加 linux 用户时出错',
    'hostacc_error_add_user_err' => '主机帐户已添加。',
    'hostacc_error_error_mount' => '挂载错误',
    'hostaccChangePassForFTP' => '更改 FTP 密码',
    'hostacc_disable_brainy_connect' => 'brainy-socket.service 服务已被禁用。',
    'hostacc_error_brainy_connect_not_found' => '找不到brainy-socket.service。',

    'hostacc_RebuildJailSkeleton' => '重建Jail框架',
    'hostacc_RebuildJailSkeletonOK' => 'Jail框架重建成功。要应用更改，您需要为用户重建Jail',
    'hostacc_RebuildJailSkeletonHint' => '创建/更新系统文件的副本以使 Jail 工作',
    'hostacc_error_set_limit_mysql' => '安装 mariadb 10.4 后，每小时的请求数限制被禁用',
    'hostacc_error_set_limit_mysql_time' => '安装 mariadb 10.4 后，每小时编辑数据的限制被禁用',
    'hostacc_error_set_limit_mysql_connection' => '安装 mariadb 10.4 后，同时连接限制被禁用',
    'hostacc_error_set_limit_mysql_connection_time' => '安装 mariadb 10.4 后，每小时用户连接数限制被禁用',
    'tpl_host_nginx_access' => '允许更改 nginx 的缓存大小：',
    'tpl_host_sharedata_title' => '共享数据',
    'hostacc_listhostacc' => '主机账户列表',
    'hostacc_server_resource_systemd' => '限制用户资源',
    'hostacc_grouprightAdmin' => '管理',
    'hostacc_grouprightUser' => '自定义',
    'hostacc_blockextended' => '扩展阻塞',
    'hostacc_error_remove_user' => '删除用户时出错。面板中 root 的访问被拒绝，该用户在 root 组中管理面板。',
    'hostacc_error_remove_group_root' => '删除或编辑组时出错。面板中的 root 访问被拒绝，此操作将阻止用户进入面板。',
    'hostacc_block_all_sites' => '阻止所有站点',
    'hostacc_block_all_sites_list' => '被屏蔽站点列表',
    'hostacc_stat_susp_email_hint' => '电子邮件被阻止',
    'hostacc_stat_susp_shell_hint' => 'Shell被阻止',
    'hostacc_error_add_system_jail' => '添加系统包或目录时出错',	

);

?>