<?php

$lang = array(
    'network_tools' => '网络工具',
    'network_tools_monit_connect' => '监控连接',
    'msg_menu_iptables' => 'IPTABLES',
    'msg_menu_network' => '网络',
    'msg_addrules_iptables' => '添加新规则：',
    'btn_addrules_iptables' => '添加规则',
    'btn_save_iptables' => '保存所有更改',
    'btn_restore_iptables' => '恢复规则配置',
    'msg_iptables_add' => '添加操作成功完成',
    'msg_iptables_delete' => '删除操作成功',
    'msg_iptables_save' => '保存规则成功',
    'msg_iptables_restore' => '恢复规则操作成功完成',
    'command_iptables_start' => '开始',
    'command_iptables_stop' => '停止',
    'command_iptables_restart' => '重启',
    'tpl_title_connect' => '连接总数：',
    'tpl_title_connect_syn' => 'SYN_RECEIVED 状态下的总连接数：',
    'tpl_title_connect_port' => '所选端口上的总连接数：',
    'tpl_title_net_status' => '上次操作状态：',
    'tpl_title_block_size' => '阻止所有连接总数超过一下值的IP：' ,
    'tpl_btn_list_show_hide' => '显示/隐藏 IP 列表',
    'tpl_btn_list_hideact' => '隐藏 IP 列表',
    'tpl_netstat_iptables_link' => '通过 iptables 阻止 IP',
    'tpl_btn_block_size' => '手动启动',
    'msg_netstat_status_null' => '没有什么可以阻止',
    'msg_netstat_block_onlyip' => '- 指定的 IP 被阻止',
    'msg_netstat_block_size' => '- IP 地址被阻止',
    'btn_run_check_start' => '运行脚本',
    'btn_run_check_stop' => '停止脚本',
    'msg_run_check_stop' => '不起作用',
    'btn_stop_start_log' => '打开/关闭日志',
    'btn_update_log' => '更新日志信息',
    'msg_start_script_info' => '或者运行一个带有句点（以秒为单位）的脚本',
    'msg_checked_log_value' => '启用日志',
    'msg_run_script_status' => '脚本状态：',
    'msg_run_script_start' => '运行',
    'msg_run_script_stop' => '不起作用',
    'msg_info_first_line' => '工作信息',
    'networktools_allports' => '所有人',
    'networktools_rule_wrongformat' => '无效的规则格式',
    'networktools_th_name' => '标题',
    'networktools_th_connect' => '<br/> 连接数',
    'networktools_th_manage' => '管理',
    'networktools_delete_rules' => '删除规则',
    'networktools_get_list_ip' => '显示 IP 列表',
    'networktools_close_journal' => '关闭日志',
    'networktools_period_works_script' => '脚本工作时间',
    'networktools_start_one' => '开始一次',
    'networktools_start_timer' => '按计时器启动',
    'networktools_open_journal' => '打开日志',
    'networktools_num_connect' => '连接数',
    'networktools_not_connect' => '无连接',
    'networktools_port' => '端口',
    'networktools_confirm_lock_ip' => '确认阻止 ip',
    'networktools_confirm_lock_ip_2' => '锁定子网 x.x.x.x / 24',
    'networktools_noactiveconnsuchtype' => '没有这种类型的活动连接',
	
);

?>