<?php
$lang = array(
    'packet_manager2' => '应用管理器',
    'package_installed' => '安装状态',
    'package_working' => '工作状态',
    'package_control' => '管理',
    'package_start' => '开始',
    'package_stop' => '停止',
    'package_restart' => '重启',
    'package_kill' => '强制停止',
    'package_autoload' => '自动加载',
    'package_reinstall' => '重新安装',
    'package_delete' => '删除',
    'package_setting' => '自定义',
    'package_repare_standart_conf' => '恢复默认设置',
    'package_error_parameters' => '参数错误',
    'package_error_parameters_config' => '在配置文件中找不到给定的命令',
    'package_error_comand_os' => '找不到适用于此操作系统的命令',
    'package_successfully' => '完成！',
    'package_not_file_config' => '缺少配置文件',
    'package_editable_conf' => '编辑',
    'package_manager_for_user' => '基础',
    'package_manager_for_expert' => '高级',
    'package_manager_save' => '保存',
    'package_error_config' => '配置错误',
    'package_not_file_repair_conf' => '无法找到要恢复的文件',
    'package_confirm' => '确认此操作',
    'package_install_version' => '安装版本',
    'package_packet' => '包',
    'roundAvailNewVersionNot' => 'Roundcube 的最新版本已经安装',
    'packet_manager_please_wait_password' => 'mysql 密码正在更改，请等一下',
	
);