<?php

$lang = array(
    'packet_manager' => '应用管理器',
    'packet_manager_title2' => '应用管理器',
    'msg_package_status' => '不起作用',
    'msg_package_err_login' => '您没有足够的权限进入此页面',

    'tpl_package_del' => '删除',
    'tpl_package_save' => '保存',
    'tpl_package_installed' => '安装状态',
    'tpl_package_working' => '工作状态',
    'tpl_package_log_show' => '查看上次安装/删除的日志',
    'tpl_package_go_process' => '处理中...',
    'tpl_package_install' => '安装',
    'tpl_package_delete' => '删除',
    'tpl_package_control' => '管理',
    'tpl_package_start' => '开始',
    'tpl_package_stop' => '停止',
    'tpl_package_restart' => '重启',
    'tpl_package_kill' => '强制停止',
    'tpl_package_autoload' => '自动加载',

    'js_package_delete' => '正在删除...',
    'packet_manager_succecfully' => '修改成功',

    'packet_manager_brainysql' => 'BrainySQL 数据库服务器',
    'packet_manager_memcached' => '内存缓存',
    'packet_manager_ffmpeg' => '强大的 UNIX 视频编码器',
    'packet_manager_imagemagick' => '图片工具',
    'packet_manager_httpry' => 'HTTP 流量分析器',
    'packet_manager_certbot' => '使用 Let‘s Encrypt 证书的脚本',
    'packet_manager_megacli' => '显示 RAID 信息的应用程序',
    'packet_manager_iotop' => '分析磁盘子系统的负载',
    'packet_manager_atop' => '交互式性能监视器',
    'packet_manager_iftop' => '网络接口统计',
    'packet_manager_logrotate' => '自动压缩、删除系统日志的实用程序',
    'packet_manager_smartmon' => '驱动器健康监视器实用程序',
    'packet_manager_php52' => 'php 5.2',
    'packet_manager_php53' => 'php 5.3',
    'packet_manager_php54' => 'php 5.4',
    'packet_manager_php55' => 'php 5.5',
    'packet_manager_php56' => 'php 5.6',
    'packet_manager_php70' => 'php 7.0',
    'packet_manager_php71' => 'php 7.1',
    'packet_manager_php72' => 'php 7.2',
    'packet_manager_git' => '分布式版本控制系统',
    'packet_manager_shellinabox' => '浏览器shell客户端',
    'packet_manager_postgresql' => 'Postgresql 数据库',
    'packet_manager_phppgadmin' => 'PostgreSQL 服务器管理',
    'packet_manager_redis' => 'keystore 的数据库',
    'packet_manager_openvpn' => 'OpenVPN 传输',
    'packet_manager_lognotexist' => '日志不存在',
);

?>