<?php

$lang = array(
    'speedtest' => '服务器通道测速',
	'speedtest_header'	=> '服务器通道测速',
	'speedtest_check_btn'	=> '测速到这个节点',
    'speedtest_choose_server'=>'选择服务器',
    'speedtest_check_speed'=>'开始测速',
    'closest_server'=>'最近的服务器',
    'Kiev' => '基辅',
    'Ukraine' => '乌克兰',
    'Moscow' => '莫斯科',
    'Russian_Federation' => '俄罗斯',
    'Russian Federation' => '俄罗斯',
    'Petersburg' => '圣彼得堡',
    'Chelyabinsk' => '车里雅宾斯克',
    'Vladivostok' => '符拉迪沃斯托克',
    'Vilnius' => '维尔纽斯',
    'Lithuania' => '立陶宛',
    'Riga' => '里加',
    'Latvia' => '拉脱维亚',
    'Tallinn' => '塔林',
    'Estonia' => '爱沙尼亚',
    'Prague' => '布拉格',
    'Czech_Republic' => '捷克共和国',
    'Kazakhstan' => '哈萨克斯坦',
    'Astana' => '阿斯塔纳',
    'Minsk' => '明斯克',
    'Belarus' => '白俄罗斯',
    'Tashkent' => '塔什干',
    'Uzbekistan' => '乌兹别克斯坦',
    'Paris' => '巴黎',
    'France' => '法国',
    'Rome' => '罗马',
    'Italy' => '意大利',
    'London' => '伦敦',
    'Great_Britain' => '英国',
    'Amsterdam' => '阿姆斯特丹',
    'Netherlands' => '荷兰',
    'Toronto' => '多伦多',
    'Canada' => '加拿大',
    'Berlin' => '柏林',
    'Germany' => '柏林',
    'Dubai' => '迪拜',
    'United_Arab_Emirates' => '阿联酋',
    'Beijing' => '北京',
    'China' => '中国',
    'New_Delhi' => '新德里',
    'India' => '印度',
    'Washington' => '华盛顿',
    'United_States' => '美国',
    'New_York_City' => '纽约',
    'Poland' => '波兰',
    'Moldova' => '摩尔多瓦共和国',
    'Romania' => '罗马尼亚',
    'Slovakia' => '斯洛伐克共和国',
    'Hungary' => '匈牙利',
    'Bulgaria' => '保加利亚',
    'Czech Republic' => '捷克共和国',
    'Serbia' => '塞尔维亚',
    'Estonia' => '爱沙尼亚',
    'Kharkiv' => '哈萨克斯坦',
    'Lviv' => '利沃夫',
    'Odessa' => '敖德萨州',
    'Belgorod' => '贝尔戈罗德',
    'Rostov-on-Don' => '顿河罗斯托夫',
    'Lublin' => '卢布林',
    'Wroclaw' => '弗罗斯拉夫',
    'Poznan' => '波兹南',
    'Krakow' => '克拉科夫',

	

);

?>