<?php

$lang = array(
	'antivirus'	=> 'Антивирус',
    'msg_antivir_status'	=> 'Не работает',
    'msg_antivir_err_login'	=> 'У вас недостаточно прав для захода на данную страницу',
    'msg_antivir_folder_not_faund'	=> 'Директории не существует',
    'msg_antivir_err_process'	=> 'Ошибка выполнения процесса. Последняя строка выполнения:',
    'msg_antivir_ok_process'	=> 'Процесс был выполнен успешно.',

    'tpl_antivir_common'	=> 'Общие',
    'tpl_antivir_check_folder'	=> 'Проверка каталогов',
    'tpl_antivir_setting'	=> 'Настройка',
    'tpl_antivir_install'	=> 'Установка антивируса',
    'tpl_antivir_auto_del'	=> 'Автоматическое удаление',
    'tpl_antivir_auto_isolation'	=> 'Автоматическое отправка в карантин',
    'tpl_antivir_scan'		=> 'Сканировать',
    'tpl_antivir_more'		=> 'Подробнее',
    'tpl_antivir_hidden'	=> 'Скрыть',
    'tpl_antivir_log_scan'	=> 'История сканирования',
    'tpl_antivir_show_file'	=> 'Отобразить файл',
    'tpl_antivir_settingss'	=> 'Настройки',
    'tpl_antivir_auto_update_db'	=> 'Автоматическое обновление антивирусных баз',
    'tpl_antivir_last_update'	=> 'Последнее обновление',
    'tpl_antivir_save'		=> 'Сохранить',
    'tpl_antivir_update'	=> 'Обновить',
    'tpl_antivir_more'		=> 'Подробнее',
    'tpl_antivir_hidden'	=> 'Скрыть',

    'tpl_antivir_go_process'	=> 'Идет процесс. Пожалуйста, подождите',
    'tpl_antivir_begin_process'	=> 'Идет процесс сканирования. Пожалуйста, подождите',
    'tpl_antivir_save_conf'	=> 'Настройки сохранены',
	'antivirus_not_root'	=> 'У вас недостаточно прав.',
	'antivirus_scan_susspend'	=> 'Сканирование успешно выполнено.',	
	'antivirus_scan_nosusspend'	=> 'Сканирование выполнено с ошибкой',		
	'antivirus_scan_check'	=> 'Запрос выполнен',
	'antivirus_scan_histiry'	=> 'История сканирования получена.',	
	'antivirus_scan_histiry_null'	=> 'Массив истории сканирования пустой',
	'antivirus_not_data'	=> 'Просматриваемый файл пустой.',
	'antivirus_not_id_history'	=> 'Такой id истории нет.',	
	'antivirus_not_root1'	=> 'У вас недостаточно прав.',	
	'antivirus_update_susspend'	=> 'Обновление успешно выполнено.',
	'antivirus_update_nosusspend'	=> 'Обновление выполнено с ошибкой',	
	'antivirus_update_limit'	=> 'Превышено время обновления.',
	'antivirus_clear_history'	=> 'Очистить историю сканирования',
	'antivirus_run_clear_history'	=> 'Идет очистка истории',
	'antivirus_clear_history_sus'	=> 'История очищена.',
	'antivirus_move_carantyn'	=> 'Перенесен в карантин',
	'antivirus_delete'	=> 'Удален',
	'antivirus_searche_bad_files'	=> 'Найдено инфицированных файлов:',
	'antivirus_virus'	=> 'Вирус',	
	'antivirus_karantine'	=> 'Карантин',
	'antivirus_delete_qw'	=> 'Удалить',
	'antivirus_all'	=> 'Все',
	'antivirus_delete_all'	=> 'Удалить все',	
	'antivirus_file'	=> 'Файл',
	'antivirus_karantine_all'	=> 'В карантин все',
	'antivirus_karantine_out'	=> 'В карантин',
	'antivirus_perfom'	=> 'Выполнить',	
	'antivirus_path_karantine'	=> 'Путь к карантину:',
    'antivirus_no_history'	=> 'История пуста',
    'antivirus_not_install'	=> 'Сервис не установлен',
    'antivirus_stopscan'	=> 'Остановить',
    'antivirus_checkrunprocess'	=> 'Проверка запущенных процессов...',
    'antivirus_processrun'	=> 'Выполняется поиск...',
    'antivirus_scan_terminate'	=> 'Сканирование прервано',
    'antivirus_update_start1'	=> 'Обновление запущено',
    'antivirus_update_finish1'	=> 'Обновление завершено',
    'antivirus_manage'	=> 'Управление',
    'antivirus_viewfile'	=> 'Посмотреть файл',
    'antivirus_update_title'	=> 'Обновление',
);

?>