<?php
$lang = array (
	'blacklist' => 'Черные списки ip',
	'blacklist_ip' => 'Проверяемый ip',
	'blacklist_check' => 'Проверить',
	'blacklist_save' => 'Сохранить',
	'blacklist_error_domain' => 'Указаный домен не подходит под регулярное выражение',	
	'blacklist_succesfully' => 'Успешно выполнено.',	
	'blacklist_error_ip' => 'ip адрес введен неправильно или пустой',
	'blacklist_dnsbl_server' => 'DNSBL сервер',	
	'blacklist_status' => 'Статус',	
	'blacklist_black' => 'В блеклисте',
	'blacklist_ok' => 'Не в блеклисте',
	'blacklist_detail' => 'Дополнительная информация',
	'blacklist_list_dnsbl' => 'Список DNSBL серверов',	
	'blacklist_check_ip_dnsbl' => 'Проверка ip в черных списках',
	'blacklist_monitor' => 'Мониторинг по времени локальные ip',	
	'blacklist_period_minutes' => 'Период минут',
	'blacklist_error_minutes' => 'Минуты введены не правильно.',
	'blacklist_many_minutes' => 'Сильно много минут',	
	'blacklist_disabled_scan' => 'Сканирование отключено',	
	'blacklist_whait_scan' => 'Подождите, идет сканирование',
	'blacklist_whait_save' => 'Подождите, идет сохранение',
	'blacklist_block_ip' => 'Заблокированные ip',
    'blacklist_check_ip_header' => 'Проверить ip',
    'blacklist_resultcheck' => 'Результаты проверки',
);
