<?php

$lang = array(
    'access_denied'                 => 'У Вас недостаточно прав для доступа к данному разделу',
    'access_deniedtitle'                 => 'Доступ запрещен',
    'index'                 => 'Главная страница',       
    'input'                 => 'Вход', 
    'login'                 => 'Логин',
    'logout'                => 'Выход',
    'password'              => 'Пароль',
    'ip_manager'            => 'IP менеджер',
    'ipmanager'             => 'IP менеджер',
    'memmanager'             => 'Менеджер ресурсов',
    'login_form'            => 'Форма входа',
    'navigation'            => 'Навигация',
    'ip_list'               => 'Список IP',
    'send'                  => 'Отправить',
	'add'                   => 'Добавить',
    'delete'                => 'Удалить',
    'add_time'              => 'Временно добавить',
    'mysql'                 => 'MySQL',
    'plans'                 => 'Тарифы',
    'plan'                  => 'Тариф',
    'new_plan'              => 'Новый тариф',
    'planname'              => 'Имя тарифа',
    'plan_properties'       => 'Свойства тарифа',
    'host_accounts'         => 'Хост-аккаунты',
    'host_account'          => 'Хост-аккаунт',
    'quota'                 => 'Квота',
    'yes'                   => 'Да',
    'no'                    => 'Нет',
    'change'                => 'Изменить',
    'install'               => 'Установить',
	'reinstall'             => 'Переустановить',
    'restart'               => 'Перезапустить',
	'force_restart'         => 'Принудительно перезапустить',
    'start'                 => 'Запустить',
    'stop'                  => 'Остановить',
    'controls'              => 'Управление',
    'edit'                  => 'Редактировать',
    'edit_plain'            => 'Редактировать как текст',
    'set'                   => 'Установить',
    'update'                => 'Обновить',
    'version'               => 'Версия',
    'current_version'       => 'Текущая версия',
    'add_user'              => 'Добавить пользователя',
    'add_db'                => 'Добавить базу данных',
    'name'                  => 'Имя',
    'add_user_to_db'        => 'Добавить пользователя в базу данных',
    'user'                  => 'Пользователь',
    'db'                    => 'База данных',
    'exist_users'           => 'Существующие пользователи',
    'exist_dbs'             => 'Существующие базы данных',
    'privileges'            => 'Привилегии',
    'data'                  => 'Данные',
    'structure'             => 'Структура',
    'default_mycnf'         => 'Восстановить стандартный my.cnf',
    'change_root_pass'      => 'Изменить пароль root',
    'server_control'        => 'Управление сервером',
    'complectation'         => 'Комплектация',
    'php_install'           => 'Установка php',
    'apache_install'        => 'Установка apache',
    'apache_control'        => 'Управление apache',
    'change_passwords'      => 'Сменить пароли',
    'nginx_install'         => 'Установка nginx',
    'autostatic'            => 'Проксировать статику',
    'nginx_control'         => 'Управление nginx',
    'server_install'        => 'Установка сервера',
    'server_complectation'  => 'Комплектация сервера',
    'edit_apacheconf'       => 'Редактировать конфигурацию apache',
    'edit_nginxconf'        => 'Редактировать конфигурацию nginx',
    'add_site'              => 'Добавить сайт',
    'site'             		=> 'Сайт',
	'site_name'             => 'Имя сайта',
    'site_alias'            => 'Псевдоним сайта',
    'site_admin'            => 'Администратор сайта',
    'site_root'             => 'Корневая папка сайта',
    'default_conf'          => 'Восстановить стандартную конфигурацию',
	'email'             	=> 'Email',
    'ip'                    => 'IP',
    'domain'                => 'Домен',
    'aliases'               => 'Алиасы',
    'dir'                   => 'Директория',
    'reload_hosts'          => 'Пересобрать виртуальные хосты',
    'remove_host'           => 'Удалить виртуальный хост',
    'current_complectation' => 'Текущая комплектация',
    'basedir'               => 'Базовая директория',
	'enter'                 => 'Войти',
    'options'               => 'Опции',
	'please_wait'			=> 'Пожалуйста, подождите',
	'processing'			=> 'Идет процесс. Пожалуйста, подождите',
    'deleting'			=> 'Удаляется...',
    'access_error'          => 'Ошибка доступа',

    'topinfo_count_sites'               => 'Сайтов',
	'topinfo_ftp'               => 'FTP аккаунтов',
    'topinfo_bandwidth'               => 'Трафик',
    'topinfo_databases'               => 'Баз',
    'topinfo_emailboxes'               => 'Ящиков',
    'topinfo_mailperhour'               => 'Писем в час',
    'topinfo_plan'               => 'Тариф',
    'topinfo_disk'               => 'Место',
    'topinfo_ip'               => 'IP',
    'topinfo_shell_access'               => 'Shell',
    'topinfo_language'               => 'Язык',
    'topinfo_username'               => 'Логин',
    'topinfo_rootdir'               => 'Домашняя папка',
    'topinfo_group'               => 'Группа',
    'topinfo_clamav' => 'Clamav',
    'topinfo_exim' => 'Exim',
    'topinfo_dovecot' => 'Dovecot',
    'topinfo_postfix' => 'Postfix',
    'topinfo_webserver' => 'webserver',
    'topinfo_cron' => 'Cron',
    'topinfo_db' => 'db',
    'topinfo_named' => 'Named',
    'topinfo_loadavg' => 'Load_AVG',
    'topinfo_diskspace' => 'Disk',
    'topinfo_proftpd' => 'FTP',
    'topinfo_pureftpd' => 'FTP',
    'topinfo_brainy' => 'Brainy',
    'topinfo_opendkim' => 'OpenDKIM',
    'topinfo_brainysqld' => 'BrainySQL',
    'topinfo_postgresql' => 'PostgreSQL',
    'topinfo_fail2ban' => 'fail2ban',

    'topinfo_g_nginx' => 'Nginx',

    'topinfo_csf' => 'CSF',
    'topinfo_spamassassin' => 'SpamAssassin',

    'topinfo_saveok' => 'Сохранено успешно',
    'common_seluserplease' => 'Выберите пользователя',
    'common_user_notselect' => 'Пользователь не выбран',
	'nothing_found' => 'Ничего не найдено',
	'search_is_runnig' => 'Идет поиск',
	'common_notselect' => 'Не выбран',
	'common_putname_label' => 'Введите имя',
	'common_user_current' => 'Текущий пользователь',
    'common_value_unlim' => 'неограниченно',
    'main_title'  => 'BrainyCP — панель управления сервером',
    'post_title'  => ' — BrainyCP',
	
	'min' => 'мин.',
	
	'topinfo_tip' => 'Данные обновляются в фоновом режиме',
	'topinfo_tip_one' => 'каждую',
	'topinfo_tip_not_one' => 'каждые',

    'common_killall_ok' => 'Процесс остановлен принудительно',
	
	'upload_caption' => 'Файл не выбран',
	'upload_btn_text' => 'Выберите файл',

    'common_pagegencountonpage' => 'Количество на странице: ',
	
	'navigate_header_list'=>'Разделы по категориям',
	'navigate_header_tile'=>'Все разделы',

    'context_menu_password' => 'Установить пароль на директорию',
    'context_menu_optimization' => 'Ускорить сайт',
    'context_menu_www' => 'Включить перенаправление',
    'context_menu_certs_control' => 'Установить SSL сертификат',
    'context_menu_certs_control_lets' => 'Установить Lets Encrypt сертификат',
    'context_menu_http' => 'Настроить HTTPS переадресацию',
    'context_menu_server_control_1' => 'Изменить PHP директивы',
    'context_menu_openfolder' => 'Управлять файлами в файлменеджере',
    'context_menu_antivirus' => 'Проверить сайт антивирусом',
    'context_menu_logging' => 'Логи',
    'context_menu_web_statistics' => 'Статистика',
    'context_menu_webserver_config' => 'Донастроить виртуальные хосты',
    'context_menu_mailforward' => 'Настроить переадресацию почты',
    'context_menu_spf' => 'Управлять SPF',
    'context_menu_opendkim' => 'Управлять DKIM',
    'context_menu_mail_antivirus' => 'Проверить почтовую папку антивирусом',
    'context_menu_mail_statistic' => 'Почтовая статистика',
    'context_menu_mail_filter' => 'Добавить фильтр',
        'auth_title'=>'BrainyCP — страница авторизации',

    'common_config_monitor' => 'Настроить',
    'common_config_updatecaption' => 'Обновление: ',
    "common_inhour"=>"в",
	"common_every1hour"=>"каждый",
    "common_every2to24"=>"каждый",
    "common_hour1hour"=>"час",
    "common_hour2to4"=>"часа",
    "common_hour5to24"=>"часов",

    "common_every1minute"=>"каждую",
    "common_every2to60"=>"каждые",
    "common_minute1hour"=>"минуту",
    "common_minute2to4"=>"минуты",
    "common_minute5to60and0"=>"минут",
    "common_everyhoursend"=>"каждого часа",

	"gen_pass" => "Сгенерировать пароль",
	"difficult_pass" => "Сложность",

    "common_demo_version" => "Панель работает в демо режиме. Файл менеджер работает в режиме только чтение.",
    'common_demo_message' => 'Извините, в демо версии данное действие отключено.',

	"choose_file" => "Выберите файл",
	"no_file" => "Файл не выбран",

    "child_human_log_mysqldb" => "Создание резервной копии базы данных ",
    "child_human_log_preparelog1" => "Подготовка файлов пользователя. ",
    "child_human_log_preparelog2" => "Копирование файлов. ",
    "child_human_log_preparelog3" => "Создание необходимых директорий. ",
    "child_human_log_process" => " ",
    "child_human_log_data_backup" => "Запись информации о бэкапе. ",
    "child_human_log_remove_temp" => "Удаление временных файлов. ",
    "child_human_log_finish_oper" => "Завершающие операции. ",
    "child_human_log_finish_emailsendcomplete" => "Отправка емейла если установлено. ",
    "child_human_log_finish_calcbackupsfordelete" => "Вычисление количества резервных копий.",
    "child_human_log_finish_completecreatebackup" => "Процесс создания резервной копии успешно завершен.",
    "child_human_log_startcreate_backup" => "Начало создания резервной копии. Пользователь ",
    "child_human_log_uptodrop" => "Загрузка бэкапа на Dropbox. ",
    "child_human_log_uptogdrive" => "Загрузка бэкапа на GoogleDrive. ",
    "child_human_log_yadisk_putfile" => "Загрузка бэкапа на YandexDisk. ",
    "child_human_log_ftp" => "Загрузка бэкапа на FTP. ",

    "child_human_log_uptodrop_rest" => "Загрузка бэкапа с Dropbox. ",
    "child_human_log_uptogdrive_rest" => "Загрузка бэкапа с GoogleDrive. ",
    "child_human_log_yadisk_putfile_rest" => "Загрузка бэкапа с YandexDisk. ",
    "child_human_log_ftp_rest" => "Загрузка бэкапа с FTP. ",


    "child_human_logtrans_start" => "Начало переноса аккаунта.",
    "child_human_logtrans_transuser" => "Перенос пользователя ",
    "child_human_logtrans_transuserend" => "Завершен перенос пользователя ",
    "child_human_logtrans_restoreuser" => "Восстановление пользователя.",
    "child_human_logtrans_restoredbuser" => "Восстановление пользователей баз данных пользователя.",
    "child_human_logtrans_restoredbuserdbs" => "Восстановление баз данных пользователя.",
    "child_human_logtrans_autoins_backup" => "Восстановление списка установленных CMS пользователя.",
    "child_human_logtrans_restore_backups_jobs" => "Восстановление списка заданий бэкапирований пользователя.",

    "child_human_logtrans_restore_restoreftpacc" => "Восстановление ФТП аккаунтов пользователя.",
    "child_human_logtrans_restore_restorevhosts" => "Восстановление виртуальных хостов пользователя.",
    "child_human_logtrans_restore_change_ips_domains" => "Смена айпи виртуальных хостов пользователя.",
    "child_human_logtrans_restore_vhostsrebuild" => "Перестройка виртуальных хостов пользователя.",
    "child_human_logtrans_restore_addzones" => "Добавление ДНС зон пользователя.",
    "child_human_logtrans_restore_restore_emails_user" => "Восстановление почтовых аккаунтов.",
    "child_human_logtrans_restore_restore_emails_routes" => "Восстановление маршрутизации почты.",
    "child_human_logtrans_restore_email_forward" => "Восстановление почтовых перенаправлений.",
    "child_human_logtrans_restorequalifyDomainJail" => "Восстановление qualifydomain для jail пользователей",
    "child_human_logtrans_restore_dns_user" => "Восстановление необходимых файлов.",
    "child_human_logtrans_restore_dkimkeys_user" => "Восстановление ключей DKIM.",
    "child_human_logtrans_restore_webserver_includes_user" => "Восстановление настроек виртуальных хостов.",
    "child_human_logtrans_restore_passdir_user" => "Восстановление настроек пользователя.",
    "child_human_logtrans_restore_httpredir_user" => "Восстановление HTTP переадресаций.",
    "child_human_logtrans_restore_siteredir_user" => "Восстановление переадресаций сайта.",
    "child_human_logtrans_restore_opti_user" => "Восстановление настроек оптимизации сайтов.",
    "child_human_logtrans_crontab" => "Восстановление CRON заданий пользователя.",

    "child_human_logtrans_restorebackuphint" => "Начато восстановление пользователя ",
    "child_human_logtrans_restorebackuphintend" => "Завершено восстановление пользователя ",
    "child_human_logtrans_clearuserdata" => "Удаление текущего пользователя перед восстановлением",
    "child_human_logtrans_restore_passdir_user" => "Восстановление настроек пользователя.",

    "child_human_logtrans_userexist" => "Пользователь с таким именем уже существует ",

    "child_human_dns_type_cluster" => "Тип синхронизации: кластер",
    "child_human_dns_type_server" => "Тип синхронизации: сервер",
    "child_human_dns_ipaddress" => "IP адрес синхронизации: ",
    "child_human_dns_typeserver" => "Тип сервера: ",
    "child_human_backup_prepare" => "Выполнение запроса...",

    "common_wrongname_pass" => "Неправильный логин или пароль",

    "child_human_backup_control_sum" => "Подсчет контрольной суммы бэкапа",
    "child_human_backup_logtrans" => "Лог: ",
    "child_human_backup_logtrans_ok" => "Резервная копия успешно сохранена",

    "common_autoloadservice_after_reset_server" => "Автозагрузка сервиса после перезапуска сервера",
    "common_autoloadservice_title" => "Автозагрузка",

    "child_human_hostaccsetjailhost" => "Восстановление настроек jail окружения пользователя.",
    "child_human_hostaccsetjailphp" => "Восстановление настроек jail php пользователя.",
    "child_human_backup_opensslcrypt" => "Шифрование/дешифрование бэкапа",
    "child_human_backup_openssldecryptFailed" => "Дешифрование завершилось с ошибкой. Восстановление прервано. Изменений не внесено.",

    "child_human_hostaccJaillOffBeforeRestore" => "Восстановление пользователя.",
    "child_human_hostaccRestoreContinue" => "Копирование файлов.",

    "current_lang" => "Русский",

    "child_human_listDBrestoredb" => "Список восстановления базы данных: ",
    "child_human_listDBuserrestore" => "Список восстановления пользователей баз данных: ",

    'common_showAllData' => 'Показать все',
   'common_server_resource_limit' => 'Ограничение серверных ресурсов',  
   'common_access_is_denied' => 'Доступ запрещен',

    "child_human_logtransStart" => "Пожалуйста, подождите, выполняется перенос пользователя",

    "child_human_logtransStartFromRemote" => "Пожалуйста, подождите, выполняется перенос пользователя с удаленного сервера",

    'child_human__yandexGetBackup' => 'Получение бэкапа с ЯндексДиска',
    'common_control_packet_menager' => 'Управление через пакетный менеджер',
    'common_install_version' => 'Установленная версия',
    'commonGmailWarning' => 'Доступно менее xxxМб, создание резервной копии невозможно. Пожалуйста освободите место.',
    'commonFewSpace' => 'Недостаточно места. Необходимо дополнительно ',
    'commonFewSpaceMsg' => 'Необходимо дополнительно ',
    'commonSizeMb' => 'мб',
    'commonEnoughSpace' => 'Места достаточно. Загрузка.',
    'human_backupNoAvailUserForBackup' => 'Пользователи, указанные в задании бэкапирования, недоступны для бэкапирования',

    'human_dropbox_message_createbackup_failed' => 'Ошибка подключения при создании бэкапа на Dropbox. Подключение к Dropbox невозможно, проверьте актуальность токенов.',
    'human_gdrive_message_createbackup_failed' => 'Ошибка подключения при создании бэкапа на Gdrive. Подключение к Gdrive невозможно, проверьте актуальность токенов.',
    'human_yandex_message_createbackup_failed' => 'Ошибка подключения при создании бэкапа на Yandex. Подключение к Yandex невозможно, проверьте актуальность токенов.',
    'human_ftp_message_createbackup_failed' => 'Ошибка подключения при создании бэкапа на FTP. Подключение к FTP невозможно, проверьте правильность логина, пароля.',
    'human_FailedConnWhileCreateBackupRemote' => 'Ошибка подключения при создании бэкапа на удаленный сервер. Пожалуйста, проверьте настройки соединения.',

    "humanUserListLockBackup" => "Для указанных пользователей невозможно сделать резервную копию, так как другой процесс создания резервной копии уже запущен: ",
    "humanUserListLockRestore" => "Для указанных пользователей невозможно сделать резервную копию, так как другой процесс восстановления резервной копии уже запущен: ",

    "humanUserListLockBackupRestAct" => "Для указанных пользователей невозможно выполнить восстановление резервной копии, так как другой процесс создания резервной копии уже запущен: ",
    "humanUserListLockRestoreRestAct" => "Для указанных пользователей невозможно выполнить восстановление резервной копии, так как другой процесс восстановления резервной копии уже запущен: ",
    "humanDownBackuoFromFTP" => "Загрузка бэкапа с FTP",
    "humanDownBackuoFromFTPFewSpace" => "Недостаточно места на FTP",

    "childHumanBackupGdriveFailedConn" => "Ошибка подключение к gDrive. Восстановление прервано. Изменений не внесено.",
    "childHumanBackupGdriveFailedConnUpload" => "Ошибка подключение к gDrive. Бэкап на gDrive не загружен.",
    "childHumanBackupGdriveConnOk" => "Подключение к gDrive успешно.",

    "childHumanRestoreEmail" => "Список восстановления почтовых аккаунтов: ",
    "childHumanRestoreAll" => "все",
    "commonAllItems" => "Все",
    "childHumanmakeDataBackupInfo" => "Запись информации о бэкапе",
    'child_humanGetdropboxBackup' => 'Получение бэкапа с Dropbox',
    "childHumanmakeUnlock" => "Разблокировка пользователя",
    'commonCustomRestFromfileUserNotExistStop' => 'Восстановление прервано, так как резервная копия выборочная и не содержит информации о пользователе. Указанного пользователя нет в системе: ',
    "childHumanrestorefromfileStream" => "Восстановление резервной копии из выбранного архива",
    "childHumanrestoreLoggingRotate" => "Восстановление настроек ротации логов",
    "childHumanrestoreHashmon" => "Восстановление настроек контроля хеш сумм",
    "childHumanrestoreGroups" => "Восстановление группы пользователя",
    "childHumanrestorePlans" => "Восстановление тарифа пользователя",
    "childHumanrestoreCrons" => "Восстановление крон заданий пользователя",
    'child_letsRegen' => 'Генерация сертификата letsencrypt для нового айпи адреса',
    "common_userNotInJailphp" => "Редактирование php.ini недоступно - пользователь не помещен в Jail PHP",
    "common_restphpiniuserjailok" => "Восстановлен php.ini успешно",
    "childHumanrestorephpini" => "Восстановление настроек phpini",
    "child_human_checkauthRemoteServer" => "Проверка авторизации на удаленный сервер",
    'common_file' => 'Файл',
    'common_erroroccu' => 'Произошла ошибка: ',
    'common_users'               => 'Пользователи',
    'common_applybtn'               => 'Применить',
    'common_domains'               => 'Домены',
    'common_cancelbtn'               => 'Отмена',
    'common_selectAll'=>'Выбрать все',
    'common_processfinish'=>'Процесс завершен',
	'common_paramwitherror' => 'Параметры содержат ошибку',
	'common_status'=>'Статус',
	'common_configtitle' => 'Конфигурация',
    'common_denyaccess' => 'Нет доступов',
    'common_see' => 'Посмотреть',
	'common_param'=>'Параметры',
	'common_diskpart'=>'Дисковые разделы',
	'common_countconnport'=>'Количество соединений на порт',
	'common_dnscount'=>'DNS зон',
    "common_fastsearche" => "Поиск находит сайты, пакеты, email",
	'common_failedparam_pass'=>'В пароле запрещено использовать символы \\\ / &apos; &quot;',
    "license_empty" => "У вас нет лицензии",	
    "license_check_data" => "Проверьте дату:",	
    "license_panel" => "Панель управления",	
    "license_correct_date" => "Если она отличается, исправьте дату используя:",	
    "license_support" => "Если дата правильная, обратитесь в техподдержку на сайте",
	'access_denied_cluster' => 'Сервер подключен в кластер, управление данным модулем только на master сервере.',
	
);
?>
