<?php

$lang = array(
    'crontab'           => 'Настройка CRON',
    'clear_script'          => 'Чистый скрипт',
    'cron_ownvalue'          => '...',
    'cron_mon'          => 'Понедельник',
    'cron_tue'          => 'Вторник',
    'cron_wed'          => 'Среда',
    'cron_thu'          => 'Четверг',
    'cron_fri'          => 'Пятница',
    'cron_sat'          => 'Суббота',
    'cron_sun'          => 'Воскресенье',
    'cron_*_short'          => '*',
    'cron_mon_short'          => 'Пн',
    'cron_tue_short'          => 'Вт',
    'cron_wed_short'          => 'Ср',
    'cron_thu_short'          => 'Чт',
    'cron_fri_short'          => 'Пт',
    'cron_sat_short'          => 'Сб',
    'cron_sun_short'          => 'Вс',
    'cron_min_fail_format'          => 'Неверный формат период запуска минуты',
    'cron_hours_fail_format'          => 'Неверный формат период запуска часы',
    'cron_days_fail_format'          => 'Неверный формат период запуска дни',
    "cron_suspended_acc"=>"Добавление, редактирование, удаление Cron заданий заблокировано. Пожалуйста, обратитесь к администратору.",
	
    'cron_install'          => 'Установлен',
    'cron_noinstall'          => 'Не установлен',
    'cron_add_comand'          => 'Добавить команду',
    'cron_delete'          => 'Удалить',
	'cron_delete_process'  => 'Удаляется...',
    'cron_edit'          => 'Редактировать',	
    'cron_save'          => 'Сохранить',		
    'cron_cansel'          => 'Отменить',	
    'cron_service'          => 'CROND сервис',	
    'cron_status'          => 'Статус CROND сервиса',
    'cron_install_cr'          => 'Установить CROND',
    'cron_delete_cr'          => 'Удалить CROND',
    'cron_reinstall_cr'          => 'Переустановить CROND',
    'cron_detail'          => 'Подробнее',
    'cron_hide'          => 'Скрыть',
    'cron_control'          => 'Управление CROND',
    'cron_start'          => 'Старт',
    'cron_stop'          => 'Стоп',
    'cron_reboot'          => 'Рестарт',
    'cron_task'          => 'Задания CROND',
    'cron_select_user'          => 'Выбрать пользователя',
    'cron_nocheck'          => 'не выбран',
    'cron_add'          => 'Сохранить email',
    'cron_changes'          => 'Изменения успешно сохранены.',
    'cron_null'          => 'Не правильный формат email',
    'cron_minute'          => 'Минута',
    'cron_hour'          => 'Час',
    'cron_day'          => 'День',
    'cron_month'          => 'Месяц',
    'cron_week'          => 'недели',
    'cron_comand'          => 'Команда',
    'cron_user_email'          => 'Email (для отправки уведомлений):',
    'cron_save_ok'          => 'Данные успешно изменены',

    'cron_command_err'          => 'Ошибка в поле команда',
    'cron_day_err'          => 'Некорректно указан день недели',
    'cron_month_err'          => 'Некорректно указан месяц',
    'cron_username_err'          => 'Некорректное имя пользователя',
    'cron_params_err'          => 'Ошибка в параметрах',
    'cron_start_ok'          => 'Запущен',
    'cron_stop_ok'          => 'Остановлен',
    'cron_start_failed'          => 'Запуск завершился с ошибкой',
    'cron_inprogress_oper'          => 'Пожалуйста, подождите',
    'cron_inprogress_oper_finish'          => 'Операция завершена',
    'cron_notins_ok'          => 'Не установлен',
    'cron_ins_ok'          => 'Установлен',
	'cron_no_tasks'          => 'Нет заданий',
    'cron_job_add_ok'          => 'Задание успешно добавлено',
    'cron_demo_mess'          => 'В демо режиме все изменения имеют только визуальный характер, на самом деле крон задания не редактируется, не создаются и не удаляются.',

    'cron_testrunjob'          => 'Выполнить',
    'cron_hintAddJob'          => 'Пример команды для добавления:<br/>1. /usr/bin/phpXX/bin/php /home/user/script.php, где ХХ - версия php<br/><br/>2. Скрытие вывода сообщений скрипта<br/> /usr/bin/phpXX/bin/php -q /home/user/script.php >/dev/null 2>/dev/null<br/><br/> 3. /usr/bin/wget -t 1 -O - `http://site.com/script.php?p1=a&p2=b`',
    'cron_hintAddJobPHPAllow' => 'Доступные версии php: ',
    'cron_comand_sucessf' => 'Команда выполнена.<br>',

    'cronChangeJobStatusOk' => 'Статус задания изменен успешно',
    'cronChangeJobStatusHint' => 'Активация/деактивация задания',

	
);

?>

