<?php

$lang = array(
    'ftp'                   => 'FTP',
    'start'                 => 'Запустить',
    'stop'                  => 'Остановить',
    'default_vsftpd'        => 'Восстановить стандартный vsftpd.conf',
    'default_pureftpd'      => 'Восстановить стандартный pure-ftpd.conf',
    'default_proftpd'      => 'Восстановить стандартный proftpd.conf',
    'homedir_user'      => 'Домашний каталог пользователя',
    'delete_homedir_user'=>'Удалить корневой каталог пользователя',
    'ftp_path'=>'Домашний каталог',
    "ftp_quota_use"=>"Использовано",
    "ftp_quota_avail"=>"Доступно",
    "ftp_change_pass"=>"Сменить пароль",
    "ftp_change_pass_placeholder"=>"Введите новый пароль",
    "ftp_change_quota"=>"Сменить квоту",
    "ftp_change_quota_placeholder"=>"Введите размер квоты",
    "ftp_change_currennt_quota"=>"Текущая квота",
    "ftp_action"=>"Действия",
    "ftp_error_add_user_exist"=>"Пользователем с таким именем существует",
    "ftp_success_add_user"=>"Пользователь добавлен",
    "ftp_deleted"=>"Удален",
    "ftp_installed"=>"Установлен",
    "ftp_reinstalled"=>"Переустановлен",
    "ftp_install"=>"Установить",
    "ftp_reinstall"=>"Переустановить",
    "ftp_delete"=>"Удалить",
    "ftp_start"=>"Запустить",
    "ftp_stop"=>"Остановить",
    "ftp_restart"=>"Перезапустить",
    "ftp_stat"=>"Статус",
    "ftp_server"=>"ФТП сервер",
    "ftp_stat_started"=>"Запущен",
    "ftp_stat_started_failed"=>"Запуск с ошибкой",
    "ftp_stat_stopped"=>"Остановлен",
    "ftp_stat_restarted"=>"Перезапущен успешно",
    "ftp_process_launched"=>"Операция запущена, пожалуйста подождите...",
    "ftp_process_finished"=>"Операция завершена.",
    "ftp_configure_share"=>"Настроить",
    "ftp_conf_edit"=>"Редактировать настройки",
    "ftp_conf_save"=>"Сохранить",
	"ftp_conf_save_file"=>"Сохранить в файл",
	"ftp_conf_save_success"=>"Сохранено успешно",
    "ftp_restore_default_settings"=>"Восстановить стандартные настройки",
    "ftp_restore_default_settings_success"=>"Стандартные настройки восстановлены",
    "ftp_repairmyconf"=>"Восстановить мои настройки",
    "ftp_repairmyconf_success"=>"Мои настройки восстановлены",

    "ftp_login"=>"Логин",
    "ftp_path"=>"Домашняя папка",
    "ftp_usage"=>"Использовано",
    "ftp_quota"=>"Квота",
    "ftp_action"=>"Действия",
    "ftp_search_user"=>"Найти",
    "ftp_accounts"=>"ФТП аккаунты",
    "ftp_search_user_holder"=>"Введите логин",
    "ftp_pagesize"=>"Количество аккаунтов на странице",

    "ftp_useradd"=>"Добавить пользователя ФТП",
    "ftp_pass_new"=>"Пароль",
    "ftp_homedir"=>"Домашняя папка",
    "ftp_newuser_add"=>"Добавить ФТП аккаунт",
    "ftp_newuser_add_success"=>"Пользователь добавлен",
    "ftp_edit_user_sub"=>"Редактировать пользователя",
    "ftp_delete_user_sub"=>"Удалить",
    "ftp_edit_user_quota"=>"Изменить квоту",
    "ftp_edit_user_pass"=>"Изменить пароль",
    "ftp_edit_user_quota_title"=>"ФТП квота",
    "ftp_edit_user_quota_mb"=>"Мб",
    "ftp_edit_user_quota_cancel"=>"Отменить",
    "ftp_edit_user_quota_file"=>"Изменить квоту на файлы",

    "ftp_edit_pass_enter"=>"Пароль",
    "ftp_edit_pass_enter_again"=>"Повторите пароль",
    "ftp_edit_pass_strength_pass"=>"Надежность пароля",
    "ftp_edit_cancel"=>"Отменить",
    "ftp_del_user"=>"Удалить пользователя",
    "ftp_del_homedir"=>"Удалить домашнюю папку пользователя",
    "ftp_del_user_cancel"=>"Отменить",
    "ftp_del_user_confirm"=>"Удалить",
	"ftp_del_user_process"=>"Удаляется...",
    "ftp_config_ftp_client"=>"Настроить ФТП клиент",
    
    "ftp_count_accept"=>"Применить",
    "ftp_user_exist"=>"Пользователь уже существует",
    "ftp_import_ok"=>"Импорт выполнен успешно",
    "ftp_import_failed"=>"Импорт выполнен с ошибкой",

    "ftp_selectftpacc"=>"Выберите пользователя",

    "ftp_searchftpacc"=>"Введите имя пользователя",

    "ftp_addaftpsubacc"=>"Добавить ФТП субаккаунт",

    "ftp_noftpins"=>"ФТП сервер не установлен. Обратитесь к администратору",

    "ftp_user_login_new_wrong"=>"Неверный формат логина пользователя",
    "ftp_user_login_new_wrong_null"=>"Введите логин",
    "ftp_user_login_pass_null"=>"Введите пароль",
    "ftp_user_userdir_null"=>"Введите домашнюю папку",
    "ftp_user_userdir_wrong"=>"Неверный формат домашней папки",

    "ftp_user_quota_null"=>"Введите размер квоты",
    "ftp_user_quota_wrong"=>"Неверный формат квоты. Должно быть целое число",

    "ftp_user_add_ok"=>"Пользователь успешно добавлен",

    "ftp_generatelog_userfolder"=>"Сгенерить логи",
    "ftp_generatelog_ok"=>"Логи сгенерированы успешно",
    "ftp_cron_run_failed"=>"Внимание! CROND не запущен на сервере. Модуль может работать некорректно. Установите и запустите crond для корректной работы.",

    "ftp_suspended_acc"=>"Добавление, редактирование, удаление ФТП аккаунтов заблокировано. Пожалуйста, обратитесь к администратору.",
    "ftp_setting"=>"Настройка ФТП сервера",
    "ftp_not_instaled"=>"не установлен",
    "ftp_p_f"=>"pure-ftpd",
    "ftp_proftpd"=>"proftpd",
    "ftp_det"=>"Подробнее",
    "ftp_hide"=>"Скрыть",	
    "ftp_ns"=>"Не выбран",		
    "ftp_f_e"=>"Для экспертов",		
    "ftp_f_l"=>"Для пользователей",		//Для лилок
    "ftp_y"=>"yes",		
    "ftp_n"=>"no",		
    "ftp_on"=>"on",		
  "ftp_off"=>"off",

    "ftp_pass_change_ok"=>"Пароль успешно изменен",
    "ftp_quota_change_ok"=>"Квота успешно изменена",

    "ftp_adduser_failed_overlimit"=>"Превышен лимит ФТП аккаунтов. Максильное количество ФТП аккаунтов ",

    "ftp_nousersadded"=>"Пользователи не созданы",
	"ftp_noaccounts"=>"Нет аккаунтов",
    "ftp_not_passwd_for_passwd"=>"Пароли не совпадают",
    "ftp_main_ftpacc"=>"Главный ФТП аккаунт. Удаление невозможно",
    "ftp_quota_not_use"=>"Квота не используется",
    "ftp_quota_hint"=>"Для безлимитной квоты введите 0",
    "ftp_user_readonly"=>"Только чтение",
    "ftp_user_readonly_res_ok_save"=>"Доступ для фтп-аккаунта изменен успешно",
    "ftp_pathMainFTP"=>"Домашняя папка главного ФТП аккаунта",
    "ftp_remove_user_error"=>"Ошибка удаления файлов. В данной директории находятся сайты ",
    "ftpChangePassMain"=>"Внимание! Смена пароля главного фтп аккаунта также приведет к установке такого же нового пароля на вход в панель.",
	
);

?>