<?php
$lang = array(
    "hashmon"=>"Контроль хеш сумм",
    "hashmon_path"=>"Каталог мониторинга",
    "hashmon_addnewmon"=>"Редактирование задания мониторинга",
    "hashmon_addnewmonbtn"=>"Добавить",
    "hashmon_period_run"=>"Период запуска",
    "hashmon_period_run_day"=>"Ежедневно",
    "hashmon_period_run_week"=>"Еженедельно",
    "hashmon_period_run_month"=>"Ежемесячно",
    "hashmon_period_run_time"=>"Время запуска",
    "hashmon_period_run_time_hh"=>"чч",
    "hashmon_period_run_time_mm"=>"мм",
    "hashmon_period_run_time_weeksel"=>"Выберите дни недели для запуска",
    "hashmon_period_run_time_weeksel_mon"=>"Пн",
    "hashmon_period_run_time_weeksel_tue"=>"Вт",
    "hashmon_period_run_time_weeksel_wed"=>"Ср",
    "hashmon_period_run_time_weeksel_tue"=>"Чт",
    "hashmon_period_run_time_weeksel_fri"=>"Пт",
    "hashmon_period_run_time_weeksel_sat"=>"Сб",
    "hashmon_period_run_time_weeksel_sun"=>"Вс",
    "hashmon_period_run_time_datesel"=>"Укажите даты для запуска",
    "hashmon_period_run_time_datesel_del"=>"Удалить",
    "hashmon_period_run_time_datesel_add"=>"Добавить дату запуска",
    "hashmon_period_run_time_sendemailafterscan"=>"Отправить емейл после завершения",
    "hashmon_period_run_time_status"=>"Статус",
    "hashmon_run_includeonly"=>"Искать только",
    "hashmon_run_includeonly_placeholder"=>"Укажите расширения файлов через , ; или пробел. Например: php,txt; sh py. Указать каталог: dir:/home/folder. Допускается запись в несколько строк",
    "hashmon_run_includeonly_placeholder_full"=>"Укажите расширения файлов через , ; или пробел.<br/>Например: php,txt; sh py.<br/>Указать каталог: dir:/home/folder. <br/>Указать каталог с поиском выбранных расширений: dir:/folder/||txt||php<br/>Допускается запись в несколько строк",
    "hashmon_run_exclude"=>"Исключить файлы",
    "hashmon_run_exclude_placeholder"=>"Укажите расширения файлов через  , ; или пробел. Например: php,txt; sh py.",

    "hashmon_createhash"=>"Создать снимок",
    "hashmon_hashlist_path"=>"Путь",
    "hashmon_hashlist_date"=>"Время создания",
    "hashmon_hashlist_mainhash"=>"Основной",
    "hashmon_hashlist_option"=>"Опции",
    "hashmon_hashlist_delete"=>"Удалить",
    "hashmon_hashlist_select"=>"Выбрать для сравнения",

    "hashmon_wrongdir"=>"Указана неверная директория",
    "hashmon_pleasewait"=>"Пожалуйста, подождите",
    "hashmon_nofindbymask"=>"По заданному фильтру мониторинга файлы не найдены",
    "hashmon_findbymask"=>"Снимок создан",
    "hashmon_pathnotexist"=>"Указанной директории не существует",
    "hashmon_option_removehash"=>"Удалить снимок",
    "hashmon_option_setmain"=>"Назначить снимок основным",
    "hashmon_option_viewhash"=>"Просмотреть снимок",
    "hashmon_option_denydeletehash"=>"Вы не являетесь владельцем данного снимка",
    "hashmon_option_comparehash"=>"Сравнить",
    "hashmon_option_uncheck"=>"Убрать выделение",
    "hashmon_option_complete_compare"=>"Сравнение выполнено успешно",
    "hashmon_hashlist_no"=>"Снимки еще не создавались",
    "hashmon_hashlist_table_title"=>"Список снимков",
    "hashmon_comphash_table_title"=>"Список выполняемых процессов сравнения снимков",
    "hashmon_comphash_table_title_noproc"=>"Нет запущенных процессов",
    "hashmon_comphash_table_title_captch1"=>"Снимок 1",
    "hashmon_comphash_table_title_captch2"=>"Снимок 2",
    "hashmon_comphash_table_title_captch_createtime"=>"Время создания",
    "hashmon_comphash_table_title_comp_starttime"=>"Время запуска ",
    "hashmon_comphash_table_title_comp_completeperc"=>"Выполнено: ",

    "hashmon_comphash_table_title_finish"=>"Список завершенных сравнений снимков",
    "hashmon_stop_comp"=>"Остановить",

    "hashmon_comphash_table_compared_no"=>"Нет выполненных сравнений снимков",
    "hashmon_comphash_table_compared_view"=>"Просмотреть результат",
    "hashmon_comphash_table_compared_manage"=>"Управление",
    "hashmon_comphash_table_compared_remove_rescomp"=>"Удалить",
    "hashmon_comphash_table_compared_view_rescomp"=>"Просмотреть",
    "hashmon_comphash_table_compared_del_deny"=>"Нет прав для удаления результата",
    "hashmon_comphash_table_compared_view_deny"=>"Нет прав для просмотра результата",

    "hashmon_comphash_table_compared_view_title"=>"Просмотр результата сравнения снимков",
    "hashmon_comphash_table_compared_view_newin"=>"Новые файлы: ",
    "hashmon_comphash_table_compared_view_remove"=>"Удаленные файлы: ",
    "hashmon_comphash_table_compared_view_newin_not"=>"не обнаружены",
    "hashmon_comphash_table_compared_view_diff"=>"Разница в файлах между снимками: ",
    "hashmon_comphash_table_compared_view_diff_no"=>"файлы не найдены",
    "hashmon_comphash_seldomain"=>"Выберите домен",
    "hashmon_comphash_nodomainuser"=>"Нет доменов",

    "hashmon_add2cronjobs"=>"Добавить задание",
    "hashmon_updatecronjobs"=>"Обновить",
    "hashmon_removecronjobs"=>"Отменить",
    "hashmon_namejob"=>"Имя задания",
    "hashmon_namejob_exist"=>"Задание с указанным именем уже существует. Придумайте другое.",
    "hashmon_namejob_exist_noedit"=>"Задание с указанным именем не существует.",
    "hashmon_namejob_empty"=>"Имя задания не может быть пустым.",
    "hashmon_wrongdir_format"=>"Неверный формат директории для сканирования",
    "hashmon_wrong_namejob"=>"Неверный формат имени задания",
    "hashmon_wrong_findonlywith"=>"Неверный формат поля Искать только с расширением",
    "hashmon_wrong_findonlywithout"=>"Неверный формат поля Исключить файлы с расширением, папки",
    "hashmon_wrong_period"=>"Неверный формат Период",
    "hashmon_wrong_timehourmin"=>"Неверный формат Время запуска",
    "hashmon_wrong_weekdays"=>"Неверный формат Дни недели",
    "hashmon_wrong_numbermonth"=>"Неверный формат Даты запуска",
    "hashmon_job_save_complete"=>"Успешно сохранено",
    "hashmon_job_list"=>"Список заданий мониторинга",

    "hashmon_job_listtable_title_name"=>"Имя",
    "hashmon_job_listtable_title_stat"=>"Статус",
    "hashmon_job_listtable_title_timerun"=>"Время запуска",
    "hashmon_job_listtable_title_opt"=>"Опции",

    "hashmon_job_listtable_title_nojobsadd"=>"Задания мониторинга не добавлены",
    "hashmon_job_notifyemail"=>"Емейл для уведомлений",
    "hashmon_job_notifyemail_hint"=>"После завершения работы задания мониторинга будет отправлено сообщение на указанный емейл со статистикой измененных, удаленных и добавленных файлов",
    "hashmon_job_notifyemail_format"=>"Введите емейлы через ;, или пробел",
    "hashmon_job_selmaincapt"=>"Выберите базовый снимок",
    "hashmon_job_selmaincapt_hint"=>"С выбранным снимком будет выполнено сравнение на обнаружение новых, удаленных и измененных файлов.<br/>Если еще нет снимка, пожалуйста сначала создайте его перед добавлением задания мониторинга",
    "hashmon_delcapt_comp_succ"=>"Сравнение снимков удалено.",
    "hashmon_emaillistnotify_wrong"=>"Неверный формат поле емейл",
    "hashmon_notexistmaincapt"=>"Выбранный главный снимок не существует",
    "hashmon_job_status"=>"Активно",
    
    'hashmon_period_intime' => ' в ',
    'hashmon_period_ondays' => ' по числам ',
    'hashmon_period_day' => 'Ежедневно',
    'hashmon_period_week' => 'Еженедельно',
    'hashmon_period_month' => 'Ежемесячно',
    'hashmon_weekly_short_arr' => array('Пн','Вт','Ср','Чт','Пт','Сб','Вс'),
    'hashmon_job_runnow' => 'Выполнить',
    'hashmon_job_edit' => 'Редактировать',
    'hashmon_job_remove' => 'Удалить',
    'hashmon_tablejob_title_maincapt' => 'Базовый снимок',
    'hashmon_tablejob_removedeny' => 'У вас нет прав на удаление данного задания мониторинга',
    'hashmon_tablejob_removeok' => 'Задание удалено',
    'hashmon_email_erorr_send' => 'Ошибка отправки письма со статистикой мониторинга',
    'hashmon_email_res_monit' => 'Результат мониторинга директории ',
    'hashmon_hash_removerow_selected' => 'Удалить отмеченные',
    'hashmon_denyusespecsymbol' => 'В имени задания запрещено использовать символы _ и пробел',
    'hashmon_oraddjob' => 'или',
    'hashmon_oraddjob_btn' => 'Добавить задание',
    'hashmon_firstcreatehash' => 'Снимков нет. Сначала создайте снимок',
    'hashmon_selallcheck' => 'Выбрать все',
    'hashmon_oraddjob_timet' => 'Добавить задание в расписание',
    'hashmon_timettitle' => 'Расписание',
    'hashmon_sel2capt2comp' => 'Выберите 2 снимка для сравнения',
    
    

);

?>