<?php

$lang = array(
    'index_logout'		=> 'Выйти',
    'index_home'		=> 'Главная',
    'index_search'		=> 'Поиск',
	'index_quick_search' => 'Быстрый поиск',
	'index_section_search' => 'Поиск по разделам',

    'index_control'		=> 'Управление',
    'index_conf_server'		=> 'Настройка сервера',
    'index_host_acct'		=> 'Хост-аккаунты',
    'index_groups_acct'		=> 'Группы хост-аккаунтов',
    'index_plans_acct'		=> 'Тарифы хост-аккаунтов',
    'index_manage_ip'		=> 'Менеджер IP адресов',
    'index_manage_mem'		=> 'Менеджер ресурсов',
    'index_update'		=> 'Обновление',
    'index_reboot'		=> 'Перезагрузка сервера',

    'index_www'			=> 'Вебсервер',
    'index_www_install'		=> 'Установка вебсервера',
    'index_php_install'		=> 'Установка и настройка PHP',
    'index_php_delete'		=> 'Удаление вебсервера и PHP',

    'index_pass_folder'		=> 'Пароль на директорию',
    'index_jmp_http'		=> 'Переадресация HTTP',
    'index_jmp_sites'		=> 'Переадресация сайтов',
    'index_apacserver_optimization' => 'Оптимизация работы сайта',
	'index_apacserver_error_pages' => 'Страницы ошибок',
	'index_webserver_config' => 'Индивидуальная донастройка виртхостов',

    'index_databases'		=> 'База данных',
    'index_mysql_db'		=> 'Управление MySQL/MariaDB',
    'index_phpmyadmin'		=> 'Управление PHPMyAdmin',

    'index_email'		=> 'Почта',
    'index_email_down'		=> 'Сервис исходящей почты',
    'index_email_up'		=> 'Сервис входящей почты',
    'index_more_install'		=> 'Массовая установка сервисов',
    'index_init_mail'		=> 'Настройка почтового сервиса',
    'index_control_queue'		=> 'Управление очередью',
    'index_control_spf'		=> 'Управление SPF',
    'index_control_dmarc'		=> 'Управление DMARC',
    'index_mail_acct'		=> 'Почтовые аккаунты',
    'index_jmp_mail'		=> 'Перенаправление почты',
    'index_control_opendkim'		=> 'Управление Opendkim',
    'index_control_clamv'		=> 'Управление Clamav',
    'index_control_spam'		=> 'Управление Spamassassin',
    'index_auto_answer'		=> 'Автоответчик',
    'index_mail_filtet'		=> 'Фильтрация почты',
    'index_mail_statistic'		=> 'Статистика писем',
    'index_mail_default'		=> 'Почтовый ящик по умолчанию',

    'index_dns'				=> 'Сервер имен',
    'index_dns_control_zone'		=> 'Управление DNS зонами',
    'index_dns_ns'		=> 'Неймсерверы',
    'index_dns_init_claster'		=> 'Кластер DNS',

    'index_application'			=> 'Приложения',
    'index_application_manager'		=> 'Менеджер приложений',
    'index_autoinit_cms'		=> 'Автоустановщик CMS',
	'index_user_cms'		=> 'Установить CMS пользователю',
    'index__file_manager'		=> 'Файловый менеджер',
    'index_ssh'				=> 'SSH сервер',
    'index_cron'			=> 'CRON',
    'index_ftp'				=> 'FTP сервер',

    'index_static'		=> 'Статистика',
    'index_manage_proc'		=> 'Менеджер процессов',
    'index_top'			=> 'TOP',
    'index_trafic_use'		=> 'Использование трафика',
    'index_average_load'		=> 'Средняя нагрузка',
    'index_static_processing'		=> 'Средства обработки статистики',
    'index_logging'		=> 'Логирование',
    'index_monitoring'		=> 'Мониторинг сервисов',
    'index_mysql_process'	=> 'MySQL Processlist',
    'index_status_web'		=> 'Статус вебсервера',
	'index_hardware_info' => 'Информация о сервере',
    'index_smart_mon' => 'S.M.A.R.T мониторинг',

    'index_cert_ssl'			=> 'Сертификаты SSL',
    'index_cert_service'		=> 'Сертификаты сервисов',
    'index_cert_user'			=> 'Пользовательские сертификаты',

    'index_backup'			=> 'Резервное копирование',
    'index_config_backup'		=> 'Настройка бэкапов',
    'index_jmp_server'			=> 'Трансферы между серверами',

    'index_network'			=> 'Сеть',
    'index_network_tools'		=> 'Управление IPTables',
    'index_stat_connect'		=> 'Мониторинг коннектов',
	'index_csf'				=> 'CSF Firewall',
	'index_speedtest' => 'Скорость канала сервера',

    'index_security'			=> 'Безопасность',
    'index_antivirus'			=> 'Антивирус',
    'index_mod_security'	=> 'Управление ModSecurity',

    'index_general'			=> 'Основное',
    'index_general_info'		=> 'Общая информация',

    'index_webwww'			=> 'WWW',
    'index_web_sites'			=> 'Сайты',
    'index_web_virthost'			=> 'Дополнительная настройка сайтов',
    'index_cloudflare'			=> 'Cloudflare',
    'index_black_domain'			=> 'Запрещенные домены',
    'index_dns_editing'			=> 'DNS редактор',

    'index_ftp_section'			=> 'FTP',
    'index_ftp_section_acct'		=> 'FTP аккаунты',

    'index_webserver_control'		=> 'Управление вебсервером',

    'index_section_mail'		=> 'Почта',
    'index_section_mailbox'		=> 'Почтовые ящики',
    'index_section_jmp_mail'		=> 'Почтовые перенаправления',
    'index_section_spf'			=> 'SPF',
    'index_section_dkim'		=> 'DKIM',
    'index_section_dmarc'		=> 'DMARC',

    'index_section_cert'		=> 'Сертификаты',
    'index_control_ssl'			=> 'Управление SSL',

    'index_sect_bd'			=> 'БД',
    'index_sect_bd_mysql'		=> 'База данных MySQL',
    'index_sect_bd_myadmin'		=> 'PHPMyAdmin',

    'index_sect_tools'			=> 'Утилиты',
    'index_sect_tools_cron'		=> 'CRON задания',
    'index_sect_tools_backup'		=> 'Резервное копирование',
    'index_sect_tools_fmanager'		=> 'Файловый менеджер',
    'index_sect_tools_cms'		=> 'Автоустановщик CMS',

    'index_sect_info'			=> 'Информация',
    'index_sect_info_monitor'		=> 'Мониторинг сервисов',
    'index_sect_info_log'		=> 'Логи',
    'index_sect_info_ns'		=> 'Наймсерверы по умолчанию',
    'index_sect_info_php'		=> 'Настройки PHP',
    'index_sect_info_usage'		=> 'Использование трафика',
    'index_sect_info_average'		=> 'Средняя нагрузка',
    'index_sect_info_stat'		=> 'Средства статистики',

    'index_brainy_tel'		=> '',
    'index_brainy_msg'		=> '',

    'index_topinfo_ip'			=> 'Все IP пользователя',
    'index_topinfo_unlim'		=> 'неограниченно',
    'index_topinfo_unlimited'	=> '&#8734',
    'webhost_configurator'		=> 'Индивидуальная донастройка виртхостов',
    'index_blacklist'		=> 'Проверка сервера в черных списках',
    'index_mail_mailing'		=> 'Почтовая рассылка',

    'index_databases_postgresql'		=> 'База данных PostgreSQL',

    'index_LogStatDom'		=> 'Управление логированием сайтов',

    'index_cluster'		=> 'Кластер',
    'index_cluster_server'		=> 'Кластер серверов',
    'index_cluster_ip'		=> 'Кластер IP',
    'indexRouteMail'		=> 'Маршрутизация почты',
    'index_cluster_mysql'		=> 'Кластер Базы данных',

    'index_controlpanel'		=> 'Панель управления сервером',
    'index_close'		=> 'Закрыть',
	'index_stopautorefresh' => 'Остановить автообновление',
    'index_continueautorefresh' => 'Продолжить автообновление',
    'index_method_withname' => 'Метод с именем ',
    'index_notexistforjquery' => ' не существует для jQuery.tooltip',
    'index_date_fullJan' => 'Январь',
    'index_date_fullFeb' => 'Февраль',
    'index_date_fullMar' => 'Март',
    'index_date_fullApr' => 'Апрель',
    'index_date_fullMay' => 'Май',
    'index_date_fullJun' => 'Июнь',
    'index_date_fullJul' => 'Июль',
    'index_date_fullAug' => 'Август',
    'index_date_fullSep' => 'Сентябрь',
    'index_date_fullOct' => 'Октябрь',
    'index_date_fullNov' => 'Ноябрь',
    'index_date_fullDec' => 'Декабрь',
    'index_date_fullJan_short' => 'Янв',
    'index_date_fullFeb_short' => 'Фев',
    'index_date_fullMar_short' => 'Мар',
    'index_date_fullApr_short' => 'Апр',
    'index_date_fullMay_short' => 'Май',
    'index_date_fullJun_short' => 'Июн',
    'index_date_fullJul_short' => 'Июл',
    'index_date_fullAug_short' => 'Авг',
    'index_date_fullSep_short' => 'Сен',
    'index_date_fullOct_short' => 'Окт',
    'index_date_fullNov_short' => 'Ноя',
    'index_date_fullDec_short' => 'Дек',
    'index_date_mon' => 'понедельник',
    'index_date_tue' => 'вторник',
    'index_date_wed' => 'среда',
    'index_date_thu' => 'четверг',
    'index_date_fri' => 'пятница',
    'index_date_sat' => 'суббота',
    'index_date_sun' => 'воскресенье',
    'index_date_mon_short' => 'пнд',
    'index_date_tue_short' => 'втр',
    'index_date_wed_short' => 'срд',
    'index_date_thu_short' => 'чтв',
    'index_date_fri_short' => 'птн',
    'index_date_sat_short' => 'сбт',
    'index_date_sun_short' => 'вск',
    'index_date_mon_min' => 'Пн',
    'index_date_tue_min' => 'Вт',
    'index_date_wed_min' => 'Ср',
    'index_date_thu_min' => 'Чт',
    'index_date_fri_min' => 'Пт',
    'index_date_sat_min' => 'Сб',
    'index_date_sun_min' => 'Вс',
    'index_date_ready' => 'Готово',
    'index_date_prev' => 'Пред',
    'index_date_next' => 'След',
    'index_date_today' => 'Сегодня',
    'index_sect_graphs' => 'Графики Мониторинга',

);
?>
