<?php

$lang = array(
    'network_tools'		=> 'Сетевые инструменты',
    'network_tools_monit_connect'		=> 'Мониторинг коннектов',
    'msg_menu_iptables'		=> 'IPTABLES',
    'msg_menu_network'		=> 'NETWORK',
    'msg_addrules_iptables'	=> 'Добавить новое правило:',
    'btn_addrules_iptables'	=> 'Добавить правило',
    'btn_save_iptables'		=> 'Сохранить все изменения',
    'btn_restore_iptables'	=> 'Восстановить конфигурацию правил',
    'msg_iptables_add'		=> 'Операция добавления выполнена успешно',
    'msg_iptables_delete'	=> 'Операция удаления выполнена успешно',
    'msg_iptables_save'		=> 'Операция сохранения правил выполнена успешно',
    'msg_iptables_restore'	=> 'Операция востановления правил выполнена успешно',
    'command_iptables_start'	=> 'Старт',
    'command_iptables_stop'	=> 'Стоп',
    'command_iptables_restart'	=> 'Перезапустить',
    'tpl_title_connect'		=> 'Общее количество соединений:',
    'tpl_title_connect_syn'	=> 'Всего соединений в состоянии SYN_RECEIVED:',
    'tpl_title_connect_port'	=> 'Всего соединений на выбранный порт:',
    'tpl_title_net_status'	=> 'Статус последней операции: ',
    'tpl_title_block_size'	=> 'Заблокировать все IP, количество соединений у которых более:',
    'tpl_btn_list_show_hide'	=> 'Показать/скрыть список IP',
    'tpl_btn_list_hideact'	=> 'Скрыть список IP',
    'tpl_netstat_iptables_link'	=> 'Заблокировать IP через iptables',
    'tpl_btn_block_size'	=> 'Запустить вручную',
    'msg_netstat_status_null'	=> 'Нечего блокировать',
    'msg_netstat_block_onlyip'	=> ' - заблокирован указанный IP',
    'msg_netstat_block_size'	=> ' - IP адрес заблокирован',
    'btn_run_check_start'	=> 'Запустить скрипт',
    'btn_run_check_stop'	=> 'Остановить скрипт',
    'msg_run_check_stop'	=> 'Не работает',
    'btn_stop_start_log'	=> 'Открыть/Закрыть журнал',
    'btn_update_log'		=> 'Обновить информацию журнала',
    'msg_start_script_info'	=> 'Или запустить скрипт с периодом (в секундах)',
    'msg_checked_log_value'	=> 'Включить логирование',
    'msg_run_script_status'	=> 'Статус скрипта: ',
    'msg_run_script_start'	=> 'работает',
    'msg_run_script_stop'	=> 'не работает',
    'msg_info_first_line'	=> 'информация о работе',
    'networktools_allports'	=> 'Все',
    'networktools_rule_wrongformat'	=> 'Неверный формат правила',
    'networktools_th_name'	=> 'Название',
    'networktools_th_connect'	=> 'Количество <br/>соединений',
    'networktools_th_manage'	=> 'Управление',
    'networktools_delete_rules'	=> 'Удалить правило',	
    'networktools_get_list_ip'	=> 'Показать список IP',	
    'networktools_close_journal'	=> 'Закрыть журнал',	
    'networktools_period_works_script'	=> 'Период работы скрипта',	
    'networktools_start_one'	=> 'Запустить единоразово',	
    'networktools_start_timer'	=> 'Запустить по таймеру',	
    'networktools_open_journal'	=> 'Открыть журнал',	
    'networktools_num_connect'	=> 'Количество соединений',	
    'networktools_not_connect'	=> 'Нет соединений',	
    'networktools_port'	=> 'Порт',	
    'networktools_confirm_lock_ip'	=> 'Подтвердите блокирование ip',	
    'networktools_confirm_lock_ip_2'	=> 'Заблокировать подсеть x.x.x.x/24',
    'networktools_noactiveconnsuchtype'=>'Нет активных соединений данного типа',
	
);

?>