<?php
$lang = array(
    'packet_manager2'	=> 'Пакетный менеджер',
    'package_installed'		=> 'Установлен',
    'package_working'		=> 'Работает',
    'package_control'		=> 'Управление',	
    'package_start'			=> 'Старт',
    'package_stop'			=> 'Стоп',
    'package_restart'		=> 'Перезапустить',
    'package_kill'			=> 'Принудительно остановить',
    'package_autoload'		=> 'Автозагрузка',	
    'package_reinstall'		=> 'Переустановить',
    'package_delete'		=> 'Удалить',	
    'package_setting'		=> 'Настроить',	
    'package_repare_standart_conf'		=> 'Восстановить стандартные настройки',	
    'package_error_parameters'		=> 'Ошибка параметров',	
    'package_error_parameters_config'		=> 'Данная команда не найдена в файле конфигурации',	
    'package_error_comand_os'		=> 'Не найдена команда для данной операционной системы',	
    'package_successfully'		=> 'Успешно выполнено.',	
    'package_not_file_config'		=> 'Отсутствует файл конфигурации',	
    'package_editable_conf'		=> 'Редактировать ',	
    'package_manager_for_user'		=> 'Для пользователей',	
    'package_manager_for_expert'		=> 'Для экспертов',	
    'package_manager_save'		=> 'Сохранить',	
    'package_error_config'		=> 'Ошибка конфигурации',	
    'package_not_file_repair_conf'		=> 'Файл для восстановления не найден.',	
    'package_confirm'		=> 'Подтвердите данное действие',	
    'package_install_version'		=> 'Установленная версия ',	
    'package_packet'		=> 'Пакет',
    'roundAvailNewVersionNot' => 'Уже установлена самая последняя версия Roundcube',
    'packet_manager_please_wait_password' => 'Выполняется изменение пароля mysql. Пожалуйста, подождите.',
	
);
