<?php
$lang = array(
	'php_ini'		=> 'Конфигурация user.ini',
	'php_ini_select_sites'		=> 'Выбор сайта',
	'php_ini_add_user_ini'		=> 'Добавить user.ini',
	'php_ini_edit_user_ini'		=> 'Редактировать user.ini',
	'php_ini_add_user_htaccess'		=> 'Добавить user_htaccess',
	'php_ini_edit_user_htaccess'		=> 'Редактировать user_htaccess',
	'php_ini_bridget_php'		=> 'Мост php',
	'php_ini_php_version'		=> 'Версия php',
	'php_ini_save'		=> 'Сохранить',
	'php_ini_cuccesfylly'		=> 'Настройки применены',
	'php_ini_select_user'		=> 'Выбор пользователя',
	'php_ini_not_int'		=> 'Значение должно быть числом без пробелов и заканчиваться ',
	'php_ini_not_switch'		=> 'Значение должно быть On или Off',	
	'php_ini_not_unfortunately'		=> 'К сожаленью версия php 5.2 не поддерживает пользовательские настройки с мостом ',
	'php_ini_remove_ini'		=> 'Удалить ini файл',	
	'php_ini_remove_ini_succ'		=> 'Файл с настройками удален',
	'php_ini_remove_ini_not'		=> 'Файл с настройками нет',
	'php_ini_not_domain'		=> 'У пользователя нет сайтов',
	'php_ini_not_int_val'		=> 'Значение должно быть числом',
	'php_ini_not_char'		=> 'В строке запрещенные символы',
	'php_ini_not_str_char'		=> 'Попытка ввести запрещенные символы',	
	'php_ini_placeholder'=> 'По умолчанию',	
	'php_ini_dont_literal'=> 'Укажите в параметре memory_limit значения M (мегабайт)',	
	'php_ini_exceed_limit'=> 'Превышение лимита.<br>Пользователю установлен лимит - ',	
	'php_ini_globalphp_inishort'=> 'Конфигурация php.ini',	

	
);