<?php

$lang = array(
    //client
    'tpl_c_serv_control_select_ip' => 'Выбор IP',
    'tpl_c_serv_control_select_php' => 'Выбор версии PHP/NodeJS',
    'tpl_c_serv_control_all_sites' => 'Все сайты',
    'tpl_c_serv_control_bridge' => 'Мост',
    'tpl_c_serv_control_ver_php' => 'Версия PHP',
    'tpl_c_serv_control_control' => 'Управление',

    //server
    'tpl_s_serv_control_php' => 'PHP',
    'tpl_s_serv_control_delete' => 'Удаление',
    'tpl_s_serv_control_reinstall' => 'Переустановить',
    'tpl_s_serv_control_status' => 'Статус сервера',
    'tpl_s_serv_control_more' => 'Подробнее',
    'tpl_s_serv_control_hide' => 'Скрыть',
    'tpl_s_serv_control_choose_bridge' => 'Возможность выбрать мост',
    'tpl_s_serv_control_yes' => 'Да',
    'tpl_s_serv_control_no' => 'Нет',
    'tpl_s_serv_control_available_bridges' => 'Доступные мосты',
    'tpl_s_serv_control_default_bridge' => 'Мост по умолчанию',
    'tpl_s_serv_control_choose_php' => 'Возможность выбрать версию PHP',
    'tpl_s_serv_control_available_php' => 'Доступные версии PHP',
    'tpl_s_serv_control_default_php' => 'Версия PHP по умолчанию',
    'tpl_s_serv_control_apply' => 'Применить',
    'tpl_s_serv_control_save_config' => 'Сохранить текущую конфигурацию',
    'tpl_s_serv_control_load_config' => 'Загрузить текущую конфигурацию',
    'tpl_s_serv_control_cancel' => 'Отмена',
    'tpl_s_serv_control_params_config' => 'Параметры сохраненной конфигурации',

    'tpl_s_serv_control_open_bridge' => 'Открытые мосты',
    'tpl_s_serv_control_open_php' => 'Открытые версии PHP',
    'tpl_s_serv_control_default_bridge' => 'Мост по умолчанию',
    'tpl_s_serv_control_default_php' => 'PHP по умолчанию',
    'tpl_s_serv_control_select_bridge' => 'Возможность выбрать мост',
    'tpl_s_serv_control_select_php' => 'Возможность выбрать PHP',

    'tpl_s_serv_control_delete_conf' => 'Удалить сохраненную конфигурацию',
    'tpl_s_serv_control_action' => 'Действие',
    'tpl_s_serv_control_edit_php_ini' => 'Редактирование основных опций php.ini',
    'tpl_s_serv_control_edit_beginners' => 'Для начинающих',
    'tpl_s_serv_control_edit_experts' => 'Для экспертов',
    'tpl_s_serv_control_save' => 'Сохранить',
    'tpl_s_serv_control_ver_select' => 'Выбор версии',

    'tpl_c_serv_control_control_fpm' => 'Управление fpm',
    'tpl_c_serv_control_start' => 'Старт',
    'tpl_c_serv_control_stop' => 'Стоп',
    'tpl_c_serv_control_restart' => 'Перезапустить',
    'tpl_c_serv_control_force_restart' => 'Перезапустить принудительно',

    'tpl_c_serv_control_client_options' => 'Клиентские опции',

    'tpl_c_serv_control_connect_php_php' => 'Поключить PHP как mod_php',
    'tpl_c_serv_control_connect_php_cgi' => 'Поключить PHP как cgi',
    'tpl_c_serv_control_connect_php_fcgi' => 'Поключить PHP как fcgi',
    'tpl_c_serv_control_connect_php_suphp' => 'Поключить PHP как suphp',
    'tpl_c_serv_control_connect_php_ruid2' => 'Поключить PHP как ruid2',
    'tpl_c_serv_control_connect_php_fpm' => 'Поключить PHP как fpm',
    'tpl_c_serv_control_connection' => 'Подключение',
    'tpl_c_serv_control_additions' => 'Дополнения',
    'tpl_c_serv_control_additions_connection' => 'Подключение дополненияй',

    'tpl_s_serv_control_name' => 'Имя',
    'tpl_s_serv_control_stat' => 'Статус',
    'tpl_s_serv_control_install' => 'Установить',
    'tpl_s_serv_control_del' => 'Удалить',
    'tpl_s_serv_control_hookup' => 'Подключить',
    'tpl_s_serv_control_select_all' => 'Выбрать всё',
    'tpl_s_serv_control_cancel_all' => 'Деактивировать всё',
    'tpl_s_serv_control_connected' => 'Подключено',


    'tpl_s_serv_control_save_config_php' => 'Сохранить текущую конфигурацию php',
    'tpl_s_serv_control_load_config_php' => 'Загрузить текущую конфигурацию php',
    'tpl_s_serv_control_version_selection' => 'Выбор версии',

    'tpl_s_serv_control_control_fpm' => 'Управление fpm',

    'tpl_s_serv_control_command_already_done' => 'Команда уже была успешно выполнена',

    'tpl_s_serv_control_isntall_megapack' => 'Установка готовых связок',
    'tpl_s_serv_control_isntall_megapack_select_webserver' => 'Выберите веб-сервер',

    'tpl_s_serv_control_isntall_megapack_select_php' => 'Выберите версию php',
    'server_control_mess_repo_update' => 'Список расширений php обновляется',
    'server_control_mess_repo_update_ok' => 'Список расширений php успешно обновлен',

    'server_control_n' => 'Виртхосты перестроены успешно.',
    'server_control_n_f_u' => 'There is no data for user',
    'server_control_n_f_a' => 'Алиас поля заполнены неправильно. Пожалуйста, используйте только буквы, цифры, тире и точек. ',
	'server_control_n_f_e' => 'Алиас уже существует в основном домене',
	'server_control_are' => 'Алиас уже существует',
	'server_control_alias_alredy_domain' => ' алиас прописан в поле Домен.',	
	'server_control_c' => 'Dir field completed incorrectly. Please use only letters, numbers, dash and slash.',
	'server_control_d_f' => 'Domain field completed incorrectly. Please use only letters, numbers, dash and dot.',
	'server_control_d_c' => 'Dir field should be completed',
	'server_control_dom_c' => 'Domain field should be completed',
	'server_control_dom_a_f' => 'Alias field completed incorrectly. Please use only letters, numbers, space, semicolon, coma, dash and dot.',
	'server_control_dom_a_a_e' => 'Alias already exists',
	'server_control_dom_d_f_c' => 'Поле директория неправильно заполненные. Пожалуйста, используйте только буквы, цифры, тире и косую черту.',
	'server_control_dom_d_f_i' => 'Поле домен заполнено неправильно. Пожалуйста, используйте только буквы, цифры, тире и точку.',
	'server_control_dom_d_f_s' => 'Поле директория должно быть заполненым',
	'server_control_dom_d_f_s_c' => 'Поле домен должно быть заполненым',
	'server_control_i_s' => 'Установка завершена успешно',
	'server_control_i_ns' => 'Установка завершена с ошибкой',
	'server_control_i' => 'Идет установка',
	'server_control_s_a' => 'Настройки применены',
	'server_control_i_d' => 'Идет удаление',
	'server_control_d_s' => 'Удаление завершено успешно',
	'server_control_d_a' => 'Удаление завершено с ошибкой',
	'server_control_c_o' => 'Конфигурация опций сохранена',
	'server_control_c_d' => 'Сохранённая конфигурация удалена',
	'server_control_o' => 'Обработка',
	'server_control_i_i' => 'Подключение...',
	'server_control_r_h' => 'Идет процесс перестройки виртуальных хостов.',
	'server_control_z_v' => 'Запрос выполняется',
	'server_control_r_o' => 'Редактирование основных опций php.ini',
	'server_control_f_u' => 'Для Пользователей',
	'server_control_f_e' => 'Для экспертов',
	'server_control_s_v' => 'Выбор версии',
	'server_control_w_s' => 'Веб-сервер',
	'server_control_a_2' => 'apache2.2',
	'server_control_a_24' => 'apache2.4',
	'server_control_ng' => 'nginx',
	'server_control_a_n' => 'apache2.2+nginx',
	'server_control_a24_n' => 'apache2.4+nginx',
	'server_control_ko' => 'Клиентские опции',
	'server_control_start' => 'start',
	'server_control_stop' => 'stop',
	'server_control_restart' => 'restart',
	'server_control_frestart' => 'force restart',
	'server_control_m_f' => 'Управление fpm',
	'server_control_s_w' => 'Выбор версии',
	'server_control_save' => 'Сохранить',
	'server_control_r_i' => 'Переустановить',
	'server_control_m_d' => 'Мост по умолчанию:',
	'server_control_v_php' => 'Версия php по умолчанию:',
	'server_control_prim' => 'Применить',
	'server_control_s_m' => 'Возможность выбрать мост:',
	'server_control_y' => 'yes',
	'server_control_no' => 'no',
	'server_control_sv_php' => 'Возможность выбрать версию php:',
	'server_control_d_m' => 'Доступные мосты:',
	'server_control_d_v_php' => 'Доступные версии php:',
	'server_control_i_php_m' => 'Подключить php как mod_php',
	'server_control_i_php_c' => 'Подключить php как cgi',
	'server_control_i_php_f' => 'Подключить php как fcgi',
	'server_control_i_php_su' => 'Подключить php как suphp',
	'server_control_i_php_ruid' => 'Подключить php как mod_ruid2',
	'server_control_i_php_fpm' => 'Подключить php как fpm',
	'server_control_u_cache' => 'Обновить список php расширений',
	'server_control_dop' => 'Дополнения',
	'server_control_name' => 'Имя',
	'server_control_status' => 'Статус',
	'server_control_install' => 'Установить',
	'server_control_del' => 'Удалить',
	'server_control_sel_all' => 'Выбрать всё',
	'server_control_podcl' => 'Подключить',
	'server_control_ins' => 'Установлено',
	'server_control_pod' => 'Подключено',
	'server_control_s_t_c' => 'Сохранить текущую конфигурацию php',
	'server_control_l_t_c' => 'Загрузить сохранённую конфигурацию php',
	'server_control_i_php7' => 'Подключение дополнений php 7.0',
	'server_control_mark_all' => 'Отметить все',
	'server_control_deactivate_all' => 'Деактивировать все',
	'server_control_to_applay' => 'Применить',
	'server_control_supl_php' => 'Дополнения php 7.0',
	'server_control_supl56' => 'Подключение дополнений php 5.6',
	'server_control_supl_php56' => 'Дополнения php 5.6',
	'server_control_proceccing' => 'Обработка',
	'server_control_supl55' => 'Дополнения php 5.5',
	'server_control_supl54' => 'Подключение дополнений php 5.4',
	'server_control_supl_54' => 'Дополнения php 5.4',
	'server_control_supl53' => 'Подключение дополнений php 5.3',
	'server_control_supl_53' => 'Дополнения php 5.3',
	'server_control_supl52' => 'Подключение дополнений php 5.2',
	'server_control_supl_52' => 'Дополнения php 5.2',
	'server_control_installing' => 'Идет установка',
	'server_control_installing_s' => 'Установка завершена успешно',
	'server_control_installing_e' => 'Установка завершена с ошибкой',
	'server_control_d_s_e' => 'Домен успешно отредактирован',
	'server_control_s_added' => 'Домен был успешно добавлен',
	'server_control_d_already' => 'Домен уже существует',
	'server_control_not_start' => 'There is no server-status module for this type of webserver',
	'server_control_s_ok' => 'Остановка',
	'server_control_start_ok' => 'Запуск',
	'server_control_domain_sus_delete' => 'Домен успешно удален',
	'server_control_not_version_aiab' => 'Смена версии недоступна',
	'server_control_ability_bridg' => 'Возможность выбрать мост:',
	'server_control_ability_php' => 'Возможность выбрать php:',
	'server_control_key_loaded' => 'Ключ загружен',
	'server_control_csr_created' => 'CSR создан',
	'server_control_error' => 'Error',
	'server_control_error_read_file' => 'Error reading file',
	'server_control_key_created' => 'Key created',
	'server_control_edit' => 'Редактировать',
	'server_control_select_bridg' => 'Выбор моста:',
	'server_control_not_domain' => 'Домен не найден.',
	'server_control_not_paf_domain' => 'Поле домен должно быть заполненым',
	'server_control_is_not_ip' => 'Этот ip адрес вам не принадлежит',
	'server_control_error_dir' => 'Ошибка при изменении директории каталога',
	'server_control_not_bridg' => 'Моста такого не существует. Доступные мосты - ',
	'server_control_not_php' => 'Версии php такой нет. Доступные версии - ',
	'server_control_phpvers_default' => 'Домен успешно отредактирован. Php по умолчанию - ',
	'server_control_phpvers_default1' => 'Домен успешно добавлен. Php по умолчанию - ',
	'server_control_all_version' => '. Доступные версии - ',
	'server_control_bridg_default' => 'Домен успешно отредактирован. Мост по умолчанию - ',
	'server_control_bridg_default1' => 'Домен успешно Добавлен. Мост по умолчанию - ',
	'server_control_not_root' => 'У вас не достаточно прав. Уберите поле user_edit',
	'server_control_list_domain' => 'Получен список доменов.',
	'server_control_email_exist' => 'На данном домене есть почтовые аккаунты. Сначала удалите их.',

	'server_control_error_user' => 'Ошибка параметров',
	'server_control_err_ip' => 'Ошибка в IP адресах. Возможно, они не определены.',

	'server_control_overlimit_domains' => 'Достигнут лимит на количество сайтов. Максимальное количество сайтов ',

	'server_control_overlimit_dnz_zones' => 'Достигнут лимит на количество DNS зон. Максимальное количество DNS зон ',
	'server_control_alias_alr_exist' => 'Алиас уже существует.',

	'server_control_label_sel_admin' => 'Имя пользователя',
	'server_control_please_wait' => 'Пожалуйста, подождите',
	'server_control_pleas_wait_adding' => 'Подождите, идет добавление',

	'server_control_no_site_added' => 'Сайты еще не добавлены',
	'server_control_user_notselect' => 'Указанному критерию поиска доменов нет',
	'server_control_seluserplease' => 'Пожалуйста, выберите пользователя',
	'server_control_selversion' => 'Выбор версии',
	'server_control_fpm_restart_all' => 'Выполнить на все FPM',
    'server_control_viewprogress' => 'Просмотреть процесс',
    'server_control_stopprogress' => 'Остановить установку',
    'server_control_processrun' => 'Выполняется установка...',
    'server_control_warning' => 'Остановка процесса установки php может привести к некорректной работе php. Пожалуйста, подтвердите остановку процесса.',
    'server_control_warning_yesstop' => 'Остановить',
    'server_control_warning_nocont' => 'Продолжить',
    'server_control_pleaseselectphp' => 'Выберите версию php',
    'server_control_pleaseselectphp_all_install' => 'Все версии php уже установлены',
    'server_control_pleaseselectphp_reinstall' => 'Выберите версию php для переустановки',
    'server_control_pleaseselectphp_all_reinstall' => 'Ни одна версия php еще не установлена',

    'server_control_configsaveok' => 'Настройки применены',
    'server_control_warning_mega' => 'Остановка процесса установки связки может привести к некорректной работе php и вебсервера. Пожалуйста, подтвердите остановку процесса.',
    'server_control_extensionphptitletable' => 'Расширения PHP',
	'server_control_sel_bridge' => 'Выбор моста:',
	'server_control_demo_message' => 'Извините, в демо версии данное действие отключено.',
    'server_control_nothingtodel' => 'Выберите что нужно удалить.',
    'server_control_nothingtodel_notinstall' => 'Ничего не установлено. Пожалуйста, установите необходимый набор связок на вкладке Веб-сервер',

    'server_control_fpm_startok' => 'Успешный запуск',
    'server_control_fpm_ok_mess' => 'успешный',
    'server_control_star' => 'Символ * доступен только в Алиасах',

    'server_control_confirmdeldom' => 'Подтвердите удаление домена ',
    'server_control_confirmdeldom_withfiles' => 'Удалить файлы и папку домена',

    'server_control_deldomadeny' => 'Вы не имеет прав на удаление указанного домена.',

    'server_control_mod_modsec' => 'Управление ModSecurity',
    'server_control_mod_modsec_check_label' => 'Активировать',
    'server_control_defaulthint_stat_modsec' => 'Статус mod_security не был конфигурирован',

    'server_control_mod_modsec_stat_change' => 'Статус ModSecurity изменен',
    'server_control_mod_modsec_stat_off' => 'ModSecurity отключен. Пожалуйста, обратитесь к администратору сервера.',

    'server_controlAliasHint' => 'Поле необязательно для ввода. Для ввода нескольких алиасов разделите пробелом, переносом строки, запятой или ;',
    'server_statLogDomains' => 'Статус логирования доменов',
    'server_control_seluserLogs' => 'Выберите пользователя',
    'server_control_LogDomain' => 'Домен',
    'server_control_LogDomainAccess' => 'Логи доступа',
    'server_control_LogDomainError' => 'Логи ошибок',
    'server_control_LogDomainDomainNotExist' => 'У пользователя нет доменов',
    'server_control_LogDomainDomainWrongUsername' => 'Неверное имя пользователя',
    'server_control_LogDomainDomainSetOk' => 'Статус логирования изменен успешно',
    'server_control_MenuStatusLog' => 'Управление статусом логирования',
    'server_control_hintLogAccess' => 'Статус логирования access_log /etc/httpd/vhost_logs/domain_access и/или /etc/nginx/vhost_logs/domain_access',
    'server_control_hintLogError' => 'Статус логирования error_log /etc/httpd/vhost_logs/domain_error и/или /etc/nginx/vhost_logs/domain_error',
	'server_control_logs' => 'Логи',
    "server_tcp_socket_err_create" => "Ошибка создания сокета",
    "server_tcp_socket_err_conn" => "Ошибка соединения сокета",
    "server_showAll" => "Показать все",
    "server_listDomColUser" => "Пользователь",
    "server_hintDenyEditBridgeRoot" => "Редактирование моста недоступно так как для пользователя включен jailphp. Отлючить jailphp можно <a target=``_blank`` href=``index.php?do=hostacc&subaction=jail``>здесь</a>",
    'server_control_captionDomain' => 'Домен',
    'server_control_captionDomainHolder' => 'Введите домен или алиас',
    'server_controlAllVersionPhps' => 'Все версии php',
    'server_controlAllUsers' => 'Все пользователи',
    'server_controlFilterDoms' => 'Поиск: ',
    'server_controlpath_config' => 'Путь к файлу конфигураци',
    'server_control_dont_user_jail' => 'Выбранный пользователь не помещен в Jail PHP',
    'server_control_dont_file_config' => 'Файл конфигурации php.ini, не найден.',
    'server_control_extensions_php_user_jail' => 'Расширения для пользователей jail',
    'server_control_whait_reinstall_php' => 'Ожидайте идет установка php',
    'server_control_whait_delete_php' => 'Ожидайте идет удаление php',
    'server_control_whait_reinstall_webserver' => 'Ожидайте идет установка связки',
    'server_control_error_directive' => 'Ошибка ввода значения директивы ',
    'server_control_error_paramert' => 'Ошибка параметров.',
    'server_control_error_pm_start_servers' => 'pm.start_servers должен быть не меньше pm.min_spare_servers и не больше pm.max_spare_server',
    'server_control_error_pm_start_servers2' => 'pm.min_spare_servers должен быть не больше pm.max_spare_server',
    'server_control_error_rm_sites' => 'Ошибка удаления сайта, В директории сайта находятся другие сайты хостаккаунта.',
    'server_control_warning_delete' => 'Остановка процесса Удаления php, или вебсервера может привести к некорректной работе php и вебсервера. Пожалуйста, подтвердите остановку процесса.',
    'server_control_stopprogress_delete' => 'Остановить удаление',		
    'server_forbidden_add_subdomain' => 'Запретить добавление субдоменов другим хост-аккаунтам',
    'server_forbidden_add_subdomain_message' => 'Ошибка добавления субдомена, коренной домен использует другой хост-аккаунт',
	'server_control_error_aliases' => 'Алиасы заполнены неправильно. Поле алиас должно содержать валидный домен.',
    'server_forbidden_add_subdomainHintEdit' => 'В случае включения запрета действие начинается с момента установки - с добавленными раньше субдоменами изменения выполнены не будут',
	'server_control_erroractmpm'=>'Произошла ошибка при активации нового MPM ',
    'server_control_setupdefaultmpm'=>' установлен по умолчанию.',
    'server_control_applysuccesscurap'=>' успешно применен для текущего Apache.',
    'server_control_adddomain'=>'Добавить сайт',
	'server_control_configfpm_phpcgi'=>'Настройка параметров FPM пулов для PHP CGI',
    'server_control_areaapplyvalues'=>'Область применения этих значений - все сайты указанного хост-аккаунта.',
	'server_control_bridgerules'=>'Мост mod_php работает только с MPM Prefork. Протокол http2 работает только с MPM Worker и Event.',
	'server_control_usempm'=>'Использовать MPM модуль Apache',
    'server_defaultpage_title'=>'Страница по умолчанию',
    'server_defaultpage_managebrainy'=>'Данный сервер управляется панелью управления BrainyCP. Если вы ожидаете увидеть сайт, то возможно вы:',
    'server_defaultpage_notadddomain'=>'не добавили доменное имя в раздел Сайты;',
    'server_defaultpage_notclearcache'=>'не очистили кеш Вашего браузера;',
    'server_defaultpage_wrongip'=>'привязали домен к неверному айпи адресу.',
    'server_defaultpage_yourhostingpanel'=>'Панель управления Вашим хостингом — ',
	'server_sitecreateok'=>'Ваш сайт был успешно создан',
	'server_domaincreateok'=>'Ваш домен успешно создан',
	'server_replacefielindextostartwork'=>'Замените данный файл index.html в папке домена на свои файлы и ваш сайт начнет работать.',
    'server_sitesuspmessage'=>'Ваш сайт на аккаунте',
	'server_seitesuspmess2'=>'был заблокирован',
	'server_panelcaption'=>'Панель управления',
	'server_locksiteextend'=>'Вы видите данную страницу, так как Ваш сайт был заблокирован. Обратитесь к администратору сервера за подробной информацией.',
	'server_loginotheruser'=>'Войти под другим пользователем',
    'server_panelsuspmessage'=>'Ваш аккаунт',
    'server_lockpanelextend'=>'Вы видите данную страницу, так как Ваш аккаунт был заблокирован. Обратитесь к администратору сервера за подробной информацией.',

    'js_nodejs_action' => 'NodeJS приложение на этом порту будет перезапущено',
    'web_nodejs_app_ok' => 'Приложение NodeJS было успешно перезапущено, порт приложения: ',
    'web_nodejs_app_err' => 'Произошла ошибка при перезапуске NodeJS приложения с портом: ',
    'web_nodejs_app_no' => 'Не удалось обнаружить приложение NodeJS с портом ',
    'server_defaultpage_emptycert' => 'Нет сертификата, при использовании протокола https.',

);

?>
