<?php

$lang = array(
    'speedtest' => 'Скорость канала сервера',
	'speedtest_header'	=> 'Скорость канала сервера',
	'speedtest_check_btn'	=> 'Проверить скорость до данной точки',
    'speedtest_choose_server'=>'Выберите сервер',
    'speedtest_check_speed'=>'Проверка скорости',
    'closest_server'=>'Ближайший сервер',
    'Kiev' => 'Киев',
    'Ukraine' => 'Украина',
    'Moscow' => 'Москва',
    'Russian_Federation' => 'Россия',
    'Russian Federation' => 'Россия',
    'Petersburg' => 'Санкт-Петербург',
    'Chelyabinsk' => 'Челябинск',
    'Vladivostok' => 'Владивосток',
    'Vilnius' => 'Вильнюс',
    'Lithuania' => 'Литва',
    'Riga' => 'Рига',
    'Latvia' => 'Латвия',
    'Tallinn' => 'Таллин',
    'Estonia' => 'Эстония',
    'Prague' => 'Прага',
    'Czech_Republic' => 'Чехия',
    'Kazakhstan' => 'Казахстан',
    'Astana' => 'Астана',
    'Minsk' => 'Минск',
    'Belarus' => 'Беларусь',
    'Tashkent' => 'Ташкент',
    'Uzbekistan' => 'Узбекистан',
    'Paris' => 'Париж',
    'France' => 'Франция',
    'Rome' => 'Рим',
    'Italy' => 'Италия',
    'London' => 'Лондон',
    'Great_Britain' => 'Великобритания',
    'Amsterdam' => 'Амстердам',
    'Netherlands' => 'Нидерланды',
    'Toronto' => 'Торонто',
    'Canada' => 'Канада',
    'Berlin' => 'Берлин',
    'Germany' => 'Германия',
    'Dubai' => 'Дубаи',
    'United_Arab_Emirates' => 'ОАЭ',
    'Beijing' => 'Пекин',
    'China' => 'Китай',
    'New_Delhi' => 'Нью-Дели',
    'India' => 'Индия',
    'Washington' => 'Вашингтон',
    'United_States' => 'США',
    'New_York_City' => 'Нью-Йорк',
    'Poland' => 'Польша',
    'Moldova' => 'Молдавия',
    'Romania' => 'Румыния',
    'Slovakia' => 'Словакия',
    'Hungary' => 'Венгрия',
    'Bulgaria' => 'Болгария',
    'Czech Republic' => 'Чехия',
    'Serbia' => 'Сербия',
    'Estonia' => 'Эстония',
    'Kharkiv' => 'Харьков',
    'Lviv' => 'Львов',
    'Odessa' => 'Одесса',
    'Belgorod' => 'Белгород',
    'Rostov-on-Don' => 'Ростов-на-Дону',
    'Lublin' => 'Люблин',
    'Wroclaw' => 'Врослав',
    'Poznan' => 'Познань',
    'Krakow' => 'Краков',

	

);

?>